using Dapper;
using Npgsql;
using PlantaoPro.Application.Administrativo360;

namespace PlantaoPro.Infrastructure.Administrativo360;

public abstract class Adm360Repository
{
    private readonly string connectionString;
    protected Adm360Repository(string connectionString) => this.connectionString = connectionString;
    protected NpgsqlConnection Connection() => new(connectionString);
}

public sealed class ComprasRepository : Adm360Repository, IComprasRepository
{
    private sealed class ReceivingRow { public Guid ProdutoId { get; set; } public bool ControlaLote { get; set; } public bool Inspecao { get; set; } public decimal Saldo { get; set; } }
    public ComprasRepository(string connectionString) : base(connectionString) { }
    public async Task<IReadOnlyList<PedidoResumo>> ListarAsync(Guid tenantId, string? fornecedor, string? situacao, DateOnly? inicio, DateOnly? fim, CancellationToken ct)
    {
        await using var cn = Connection();
        return (await cn.QueryAsync<PedidoResumo>(new CommandDefinition(@"select p.id,p.numero,f.nome fornecedor,p.situacao,
            (select coalesce(sum(i.quantidade*i.preco_unitario-i.desconto),0) from plantaopro.adm360_pedido_itens i where i.pedido_id=p.id)+p.frete total,p.created_at criadoem
            from plantaopro.adm360_pedidos p join plantaopro.adm360_parceiros f on f.id=p.fornecedor_id and f.tenant_id=p.tenant_id
            where p.tenant_id=@tenantId and (@fornecedor is null or f.nome ilike '%'||@fornecedor||'%') and (@situacao is null or p.situacao=@situacao)
            and (@inicio is null or p.created_at::date>=@inicio) and (@fim is null or p.created_at::date<=@fim) order by p.created_at desc", new { tenantId, fornecedor, situacao, inicio, fim }, cancellationToken: ct))).AsList();
    }
    public async Task<Guid> CriarAsync(Guid tenantId, Guid usuarioId, CriarPedidoCommand c, CancellationToken ct)
    {
        if (c.Frete < 0 || c.Itens.Count == 0 || c.Itens.Any(x => x.Quantidade <= 0 || x.PrecoUnitario < 0 || x.Desconto < 0)) throw new ArgumentException("Informe itens positivos e valores não negativos.");
        await using var cn=Connection(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(ct);
        var fornecedor=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_parceiros where id=@id and tenant_id=@tenantId and ativo and fornecedor)",new{id=c.FornecedorId,tenantId},tx,cancellationToken:ct));
        if(!fornecedor) throw new ArgumentException("Fornecedor inativo ou não acessível.");
        var produtos=await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from plantaopro.adm360_produtos where tenant_id=@tenantId and ativo and id=any(@ids)",new{tenantId,ids=c.Itens.Select(x=>x.ProdutoId).Distinct().ToArray()},tx,cancellationToken:ct));
        if(produtos!=c.Itens.Select(x=>x.ProdutoId).Distinct().Count()) throw new ArgumentException("Há produto inativo ou não acessível.");
        var id=Guid.NewGuid();
        await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_pedidos(id,tenant_id,numero,fornecedor_id,previsao,frete,created_by) values(@id,@tenantId,'PC-'||nextval('plantaopro.adm360_pedido_numero'),@FornecedorId,@Previsao,@Frete,@usuarioId)",new{id,tenantId,c.FornecedorId,c.Previsao,c.Frete,usuarioId},tx,cancellationToken:ct));
        foreach(var item in c.Itens) await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_pedido_itens(id,tenant_id,pedido_id,produto_id,quantidade,preco_unitario,desconto) values(gen_random_uuid(),@tenantId,@id,@ProdutoId,@Quantidade,@PrecoUnitario,@Desconto)",new{tenantId,id,item.ProdutoId,item.Quantidade,item.PrecoUnitario,item.Desconto},tx,cancellationToken:ct));
        await tx.CommitAsync(ct); return id;
    }
    public async Task AprovarAsync(Guid tenantId, Guid usuarioId, Guid pedidoId, string key, CancellationToken ct)
    {
        await using var cn=Connection(); var changed=await cn.ExecuteAsync(new CommandDefinition(@"update plantaopro.adm360_pedidos set situacao='APROVADO',aprovado_em=now(),aprovado_por=@usuarioId,versao=versao+1,idempotency_key=@key
          where id=@pedidoId and tenant_id=@tenantId and situacao='RASCUNHO' and not exists(select 1 from plantaopro.adm360_pedidos x where x.tenant_id=@tenantId and x.idempotency_key=@key and x.id<>@pedidoId)",new{tenantId,usuarioId,pedidoId,key},cancellationToken:ct));
        if(changed==0 && !await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_pedidos where id=@pedidoId and tenant_id=@tenantId and idempotency_key=@key and situacao<>'RASCUNHO')",new{tenantId,pedidoId,key},cancellationToken:ct))) throw new InvalidOperationException("Pedido não está disponível para aprovação.");
    }
    public async Task<Guid> ReceberAsync(Guid tenantId, Guid usuarioId, ConfirmarRecebimentoCommand c, CancellationToken ct)
    {
        await using var cn=Connection(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        var existing=await cn.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from plantaopro.adm360_recebimentos where tenant_id=@tenantId and idempotency_key=@key",new{tenantId,key=c.IdempotencyKey},tx,cancellationToken:ct)); if(existing.HasValue){await tx.CommitAsync(ct);return existing.Value;}
        var status=await cn.ExecuteScalarAsync<string?>(new CommandDefinition("select situacao from plantaopro.adm360_pedidos where id=@id and tenant_id=@tenantId for update",new{id=c.PedidoId,tenantId},tx,cancellationToken:ct));
        if(status is not ("APROVADO" or "PARCIAL")) throw new InvalidOperationException("Somente pedido aprovado ou parcial pode ser recebido.");
        var rid=Guid.NewGuid(); await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_recebimentos(id,tenant_id,pedido_id,documento,idempotency_key,confirmado_em,created_by) values(@rid,@tenantId,@PedidoId,@Documento,@key,now(),@usuarioId)",new{rid,tenantId,c.PedidoId,c.Documento,key=c.IdempotencyKey,usuarioId},tx,cancellationToken:ct));
        foreach(var item in c.Itens){
            if(item.Quantidade<=0) throw new ArgumentException("Quantidade recebida deve ser positiva.");
            var row=await cn.QuerySingleOrDefaultAsync<ReceivingRow>(new CommandDefinition(@"select i.produto_id ProdutoId,p.controla_lote ControlaLote,p.exige_inspecao Inspecao,i.quantidade-i.quantidade_recebida Saldo from plantaopro.adm360_pedido_itens i join plantaopro.adm360_produtos p on p.id=i.produto_id and p.tenant_id=i.tenant_id where i.id=@id and i.pedido_id=@PedidoId and i.tenant_id=@tenantId for update",new{id=item.PedidoItemId,c.PedidoId,tenantId},tx,cancellationToken:ct));
            if(row is null || row.ProdutoId==Guid.Empty || item.Quantidade>row.Saldo) throw new InvalidOperationException("Quantidade excede o saldo autorizado do pedido.");
            if(row.ControlaLote&&string.IsNullOrWhiteSpace(item.Lote)) throw new ArgumentException("Lote é obrigatório para produto controlado.");
            var localOk=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_locais where id=@id and tenant_id=@tenantId and ativo)",new{id=item.LocalId,tenantId},tx,cancellationToken:ct)); if(!localOk) throw new ArgumentException("Local não pertence à organização.");
            var condicao=item.Validade.HasValue&&item.Validade.Value<DateOnly.FromDateTime(DateTime.UtcNow)?"VENCIDO":row.Inspecao?"QUARENTENA":"LIBERADO";
            var loteId=await cn.ExecuteScalarAsync<Guid>(new CommandDefinition(@"insert into plantaopro.adm360_lotes(id,tenant_id,produto_id,codigo,validade) values(gen_random_uuid(),@tenantId,@produto,@lote,@validade) on conflict(tenant_id,produto_id,codigo) do update set validade=coalesce(plantaopro.adm360_lotes.validade,excluded.validade) returning id",new{tenantId,produto=row.ProdutoId,lote=item.Lote??"SEM-LOTE",validade=item.Validade},tx,cancellationToken:ct));
            var ri=Guid.NewGuid(); await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_recebimento_itens(id,tenant_id,recebimento_id,pedido_item_id,produto_id,lote_id,local_id,quantidade,condicao) values(@ri,@tenantId,@rid,@PedidoItemId,@produto,@loteId,@LocalId,@Quantidade,@condicao); update plantaopro.adm360_pedido_itens set quantidade_recebida=quantidade_recebida+@Quantidade where id=@PedidoItemId",new{ri,tenantId,rid,item.PedidoItemId,produto=row.ProdutoId,loteId,item.LocalId,item.Quantidade,condicao},tx,cancellationToken:ct));
            await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_movimentos(id,tenant_id,produto_id,lote_id,local_id,tipo,condicao,quantidade,origem_tipo,origem_id,idempotency_key,created_by) values(gen_random_uuid(),@tenantId,@produto,@loteId,@LocalId,'ENTRADA',@condicao,@Quantidade,'RECEBIMENTO',@ri,@key,@usuarioId)",new{tenantId,produto=row.ProdutoId,loteId,item.LocalId,item.Quantidade,condicao,ri,key=$"{c.IdempotencyKey}:{item.PedidoItemId}",usuarioId},tx,cancellationToken:ct));
        }
        await cn.ExecuteAsync(new CommandDefinition("update plantaopro.adm360_pedidos p set situacao=case when exists(select 1 from plantaopro.adm360_pedido_itens i where i.pedido_id=p.id and i.quantidade_recebida<i.quantidade) then 'PARCIAL' else 'RECEBIDO' end,versao=versao+1 where id=@PedidoId",new{c.PedidoId},tx,cancellationToken:ct));
        await tx.CommitAsync(ct); return rid;
    }
}

public sealed class EstoqueRepository : Adm360Repository, IEstoqueRepository
{
    public EstoqueRepository(string cs):base(cs){}
    public async Task<IReadOnlyList<SaldoEstoque>> ConsultarAsync(Guid tenantId,string? busca,string? condicao,Guid? localId,CancellationToken ct){await using var cn=Connection();return(await cn.QueryAsync<SaldoEstoque>(new CommandDefinition("select produto_id ProdutoId,produto,lote_id LoteId,lote,validade,local_id LocalId,local,condicao,fisico,reservado,disponivel from plantaopro.adm360_saldos where tenant_id=@tenantId and (@busca is null or produto ilike '%'||@busca||'%' or lote ilike '%'||@busca||'%') and (@condicao is null or condicao=@condicao) and (@localId is null or local_id=@localId) order by produto,validade nulls last",new{tenantId,busca,condicao,localId},cancellationToken:ct))).AsList();}
    public async Task TransferirAsync(Guid tenantId,Guid usuarioId,TransferirCommand c,CancellationToken ct)
    {
        if(c.Quantidade<=0||string.IsNullOrWhiteSpace(c.Motivo))throw new ArgumentException("Quantidade positiva e motivo são obrigatórios.");
        await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        if(await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_movimentos where tenant_id=@tenantId and idempotency_key=@key)",new{tenantId,key=c.IdempotencyKey},tx,cancellationToken:ct))){await tx.CommitAsync(ct);return;}
        var locais=await cn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from plantaopro.adm360_locais where tenant_id=@tenantId and ativo and id=any(@ids)",new{tenantId,ids=new[]{c.OrigemId,c.DestinoId}},tx,cancellationToken:ct));if(locais!=2||c.OrigemId==c.DestinoId)throw new ArgumentException("Origem e destino devem ser locais distintos da organização.");
        await cn.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@lock,0))",new{lock=$"{tenantId}:{c.ProdutoId}:{c.LoteId}:{c.OrigemId}"},tx,cancellationToken:ct));
        var available=await cn.ExecuteScalarAsync<decimal>(new CommandDefinition("select coalesce(disponivel,0) from plantaopro.adm360_saldos where tenant_id=@tenantId and produto_id=@ProdutoId and lote_id=@LoteId and local_id=@OrigemId and condicao='LIBERADO'",new{tenantId,c.ProdutoId,c.LoteId,c.OrigemId},tx,cancellationToken:ct));if(available<c.Quantidade)throw new InvalidOperationException("Saldo disponível insuficiente para transferência.");
        var op=Guid.NewGuid();foreach(var leg in new[]{(c.OrigemId,-c.Quantidade,"TRANSFERENCIA_SAIDA"),(c.DestinoId,c.Quantidade,"TRANSFERENCIA_ENTRADA")})await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_movimentos(id,tenant_id,produto_id,lote_id,local_id,tipo,condicao,quantidade,motivo,origem_tipo,origem_id,idempotency_key,created_by) values(gen_random_uuid(),@tenantId,@ProdutoId,@LoteId,@local,@tipo,'LIBERADO',@qty,@Motivo,'TRANSFERENCIA',@op,@key,@usuarioId)",new{tenantId,c.ProdutoId,c.LoteId,local=leg.Item1,qty=leg.Item2,tipo=leg.Item3,c.Motivo,op,key=$"{c.IdempotencyKey}:{leg.Item3}",usuarioId},tx,cancellationToken:ct));
        await tx.CommitAsync(ct);
    }
    public async Task ReservarAsync(Guid tenantId,Guid usuarioId,ReservarCommand c,CancellationToken ct)
    {
        if(c.Quantidade<=0)throw new ArgumentException("Quantidade deve ser positiva.");await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        if(await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_reservas where tenant_id=@tenantId and idempotency_key=@key)",new{tenantId,key=c.IdempotencyKey},tx,cancellationToken:ct))){await tx.CommitAsync(ct);return;}
        await cn.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@lock,0))",new{lock=$"{tenantId}:{c.ProdutoId}:{c.LoteId}:{c.LocalId}"},tx,cancellationToken:ct));
        if(await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_inventarios where tenant_id=@tenantId and local_id=@LocalId and situacao in ('ABERTO','CONTAGEM','REVISAO'))",new{tenantId,c.LocalId},tx,cancellationToken:ct)))throw new InvalidOperationException("Movimentação bloqueada: há inventário em contagem neste local.");
        var available=await cn.ExecuteScalarAsync<decimal>(new CommandDefinition("select coalesce(disponivel,0) from plantaopro.adm360_saldos where tenant_id=@tenantId and produto_id=@ProdutoId and lote_id=@LoteId and local_id=@LocalId and condicao='LIBERADO'",new{tenantId,c.ProdutoId,c.LoteId,c.LocalId},tx,cancellationToken:ct));if(available<c.Quantidade)throw new InvalidOperationException("Quantidade solicitada excede o estoque disponível.");
        await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_reservas(id,tenant_id,produto_id,lote_id,local_id,quantidade,origem_tipo,origem_id,idempotency_key,created_by) values(gen_random_uuid(),@tenantId,@ProdutoId,@LoteId,@LocalId,@Quantidade,@Origem,@OrigemId,@key,@usuarioId)",new{tenantId,c.ProdutoId,c.LoteId,c.LocalId,c.Quantidade,c.Origem,c.OrigemId,key=c.IdempotencyKey,usuarioId},tx,cancellationToken:ct));await tx.CommitAsync(ct);
    }
}

public sealed class QualidadeRepository : Adm360Repository, IQualidadeRepository
{
    private sealed class InspectionRow { public Guid ProdutoId { get; set; } public Guid LoteId { get; set; } public Guid LocalId { get; set; } public decimal Pendente { get; set; } public string Condicao { get; set; } = string.Empty; }
    public QualidadeRepository(string cs):base(cs){}
    public async Task<IReadOnlyList<InspecaoPendente>> PendentesAsync(Guid tenantId,CancellationToken ct){await using var cn=Connection();return(await cn.QueryAsync<InspecaoPendente>(new CommandDefinition(@"select r.id RecebimentoItemId,p.nome Produto,l.codigo Lote,r.quantidade Recebida,r.quantidade-r.quantidade_decidida Pendente,o.nome Local from plantaopro.adm360_recebimento_itens r join plantaopro.adm360_produtos p on p.id=r.produto_id join plantaopro.adm360_lotes l on l.id=r.lote_id join plantaopro.adm360_locais o on o.id=r.local_id where r.tenant_id=@tenantId and r.condicao in ('QUARENTENA','VENCIDO') and r.quantidade_decidida<r.quantidade order by r.created_at",new{tenantId},cancellationToken:ct))).AsList();}
    public async Task DecidirAsync(Guid tenantId,Guid usuarioId,DecidirInspecaoCommand c,CancellationToken ct)
    {
        if(c.Aprovada<0||c.Reprovada<0||c.Aprovada+c.Reprovada<=0||(c.Reprovada>0&&string.IsNullOrWhiteSpace(c.Justificativa)))throw new ArgumentException("Decisão inválida; reprovação exige justificativa.");
        await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        if(await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_inspecoes where tenant_id=@tenantId and idempotency_key=@key)",new{tenantId,key=c.IdempotencyKey},tx,cancellationToken:ct))){await tx.CommitAsync(ct);return;}
        var r=await cn.QuerySingleOrDefaultAsync<InspectionRow>(new CommandDefinition("select produto_id ProdutoId,lote_id LoteId,local_id LocalId,quantidade-quantidade_decidida Pendente,condicao Condicao from plantaopro.adm360_recebimento_itens where id=@id and tenant_id=@tenantId for update",new{id=c.RecebimentoItemId,tenantId},tx,cancellationToken:ct));if(r is null || r.ProdutoId==Guid.Empty||c.Aprovada+c.Reprovada>r.Pendente)throw new InvalidOperationException("Decisão excede o saldo pendente da inspeção.");if(r.Condicao=="VENCIDO"&&c.Aprovada>0)throw new InvalidOperationException("Material vencido não pode ser liberado.");
        var iid=Guid.NewGuid();await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_inspecoes(id,tenant_id,recebimento_item_id,aprovada,reprovada,justificativa,destino,idempotency_key,decidido_por,decidido_em) values(@iid,@tenantId,@RecebimentoItemId,@Aprovada,@Reprovada,@Justificativa,@Destino,@key,@usuarioId,now());update plantaopro.adm360_recebimento_itens set quantidade_decidida=quantidade_decidida+@total where id=@RecebimentoItemId",new{iid,tenantId,c.RecebimentoItemId,c.Aprovada,c.Reprovada,c.Justificativa,c.Destino,key=c.IdempotencyKey,usuarioId,total=c.Aprovada+c.Reprovada},tx,cancellationToken:ct));
        foreach(var leg in new[]{("QUARENTENA",-c.Aprovada), ("LIBERADO",c.Aprovada), ("QUARENTENA",-c.Reprovada), ("REPROVADO",c.Reprovada)})if(leg.Item2!=0)await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_movimentos(id,tenant_id,produto_id,lote_id,local_id,tipo,condicao,quantidade,motivo,origem_tipo,origem_id,idempotency_key,created_by) values(gen_random_uuid(),@tenantId,@produto,@lote,@local,'INSPECAO',@condicao,@qty,@Justificativa,'INSPECAO',@iid,@key,@usuarioId)",new{tenantId,produto=r.ProdutoId,lote=r.LoteId,local=r.LocalId,condicao=leg.Item1,qty=leg.Item2,c.Justificativa,iid,key=$"{c.IdempotencyKey}:{leg.Item1}:{leg.Item2}",usuarioId},tx,cancellationToken:ct));
        await tx.CommitAsync(ct);
    }
}

public sealed class ColetaRepository : Adm360Repository, IColetaRepository
{
 public ColetaRepository(string cs):base(cs){}
 public async Task<IReadOnlyList<TarefaColeta>> TarefasAsync(Guid tenantId,Guid usuarioId,CancellationToken ct){await using var cn=Connection();return(await cn.QueryAsync<TarefaColeta>(new CommandDefinition("select id,tipo,descricao,situacao from plantaopro.adm360_tarefas_coleta where tenant_id=@tenantId and (atribuida_a is null or atribuida_a=@usuarioId) and situacao='ABERTA' order by created_at",new{tenantId,usuarioId},cancellationToken:ct))).AsList();}
 public async Task RegistrarAsync(Guid tenantId,Guid usuarioId,RegistrarLeituraCommand c,CancellationToken ct){if(c.Quantidade<=0)throw new ArgumentException("Quantidade deve ser positiva.");await using var cn=Connection();var affected=await cn.ExecuteAsync(new CommandDefinition(@"insert into plantaopro.adm360_leituras(id,tenant_id,tarefa_id,scan_id,codigo,lote,quantidade,created_by) select gen_random_uuid(),@tenantId,@TarefaId,@ScanId,@Codigo,@Lote,@Quantidade,@usuarioId where exists(select 1 from plantaopro.adm360_tarefas_coleta where id=@TarefaId and tenant_id=@tenantId and situacao='ABERTA' and (atribuida_a is null or atribuida_a=@usuarioId)) on conflict(tenant_id,scan_id) do nothing",new{tenantId,c.TarefaId,c.ScanId,c.Codigo,c.Lote,c.Quantidade,usuarioId},cancellationToken:ct));if(affected==0&&!await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_leituras where tenant_id=@tenantId and scan_id=@ScanId)",new{tenantId,c.ScanId},cancellationToken:ct)))throw new UnauthorizedAccessException("Tarefa inexistente ou não autorizada.");}
}

public sealed class InventarioRepository : Adm360Repository, IInventarioRepository
{
 public InventarioRepository(string cs):base(cs){}
 public async Task<IReadOnlyList<InventarioResumo>> ListarAsync(Guid tenantId,CancellationToken ct){await using var cn=Connection();return(await cn.QueryAsync<InventarioResumo>(new CommandDefinition("select i.id,l.nome local,i.escopo,i.situacao,i.created_at CriadoEm from plantaopro.adm360_inventarios i join plantaopro.adm360_locais l on l.id=i.local_id and l.tenant_id=i.tenant_id where i.tenant_id=@tenantId order by i.created_at desc",new{tenantId},cancellationToken:ct))).AsList();}
 public async Task<Guid> AbrirAsync(Guid tenantId,Guid usuarioId,AbrirInventarioCommand c,CancellationToken ct){if(string.IsNullOrWhiteSpace(c.Escopo))throw new ArgumentException("Informe o escopo da contagem.");await using var cn=Connection();var id=Guid.NewGuid();var n=await cn.ExecuteAsync(new CommandDefinition(@"insert into plantaopro.adm360_inventarios(id,tenant_id,local_id,situacao,escopo,created_by) select @id,@tenantId,@LocalId,'CONTAGEM',trim(@Escopo),@usuarioId where exists(select 1 from plantaopro.adm360_locais where id=@LocalId and tenant_id=@tenantId and ativo) and not exists(select 1 from plantaopro.adm360_inventarios where tenant_id=@tenantId and local_id=@LocalId and situacao in ('ABERTO','CONTAGEM','REVISAO'))",new{id,tenantId,c.LocalId,c.Escopo,usuarioId},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Local inválido ou já bloqueado por outro inventário.");return id;}
 public async Task ContarAsync(Guid tenantId,Guid usuarioId,Guid inventarioId,ContarInventarioCommand c,CancellationToken ct){if(c.Quantidade<0)throw new ArgumentException("Quantidade contada não pode ser negativa.");await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var local=await cn.ExecuteScalarAsync<Guid?>(new CommandDefinition("select local_id from plantaopro.adm360_inventarios where id=@inventarioId and tenant_id=@tenantId and situacao='CONTAGEM' for update",new{inventarioId,tenantId},tx,cancellationToken:ct));if(!local.HasValue)throw new InvalidOperationException("Inventário não está em contagem.");var expected=await cn.ExecuteScalarAsync<decimal>(new CommandDefinition("select coalesce(sum(fisico),0) from plantaopro.adm360_saldos where tenant_id=@tenantId and local_id=@local and produto_id=@ProdutoId and lote_id=@LoteId",new{tenantId,local,c.ProdutoId,c.LoteId},tx,cancellationToken:ct));await cn.ExecuteAsync(new CommandDefinition(@"insert into plantaopro.adm360_inventario_itens(id,tenant_id,inventario_id,produto_id,lote_id,esperado,contado) values(gen_random_uuid(),@tenantId,@inventarioId,@ProdutoId,@LoteId,@expected,@Quantidade) on conflict(tenant_id,inventario_id,produto_id,lote_id) do update set contado=excluded.contado",new{tenantId,inventarioId,c.ProdutoId,c.LoteId,expected,c.Quantidade},tx,cancellationToken:ct));await tx.CommitAsync(ct);}
 public async Task AprovarAsync(Guid tenantId,Guid usuarioId,Guid inventarioId,string justificativa,string key,CancellationToken ct){if(string.IsNullOrWhiteSpace(justificativa))throw new ArgumentException("Ajuste exige justificativa.");await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);var inv=await cn.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select local_id from plantaopro.adm360_inventarios where id=@inventarioId and tenant_id=@tenantId and situacao in ('CONTAGEM','REVISAO') for update",new{inventarioId,tenantId},tx,cancellationToken:ct));if(inv is null){if(await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.adm360_inventarios where id=@inventarioId and tenant_id=@tenantId and idempotency_aprovacao=@key and situacao='APROVADO')",new{inventarioId,tenantId,key},tx,cancellationToken:ct))){await tx.CommitAsync(ct);return;}throw new InvalidOperationException("Inventário não pode ser aprovado.");}var itens=(await cn.QueryAsync<dynamic>(new CommandDefinition("select produto_id,lote_id,contado-esperado diferenca from plantaopro.adm360_inventario_itens where tenant_id=@tenantId and inventario_id=@inventarioId and contado is not null",new{tenantId,inventarioId},tx,cancellationToken:ct))).ToList();foreach(var i in itens)if((decimal)i.diferenca!=0)await cn.ExecuteAsync(new CommandDefinition("insert into plantaopro.adm360_movimentos(id,tenant_id,produto_id,lote_id,local_id,tipo,condicao,quantidade,motivo,origem_tipo,origem_id,idempotency_key,created_by) values(gen_random_uuid(),@tenantId,@produto,@lote,@local,'AJUSTE','LIBERADO',@qty,@justificativa,'INVENTARIO',@inventarioId,@ikey,@usuarioId)",new{tenantId,produto=(Guid)i.produto_id,lote=(Guid)i.lote_id,local=(Guid)inv.local_id,qty=(decimal)i.diferenca,justificativa,inventarioId,ikey=$"{key}:{i.produto_id}:{i.lote_id}",usuarioId},tx,cancellationToken:ct));await cn.ExecuteAsync(new CommandDefinition("update plantaopro.adm360_inventarios set situacao='APROVADO',motivo_ajuste=@justificativa,idempotency_aprovacao=@key,versao=versao+1 where id=@inventarioId and tenant_id=@tenantId",new{justificativa,key,inventarioId,tenantId},tx,cancellationToken:ct));await tx.CommitAsync(ct);}
 public async Task CancelarAsync(Guid tenantId,Guid usuarioId,Guid inventarioId,string motivo,CancellationToken ct){if(string.IsNullOrWhiteSpace(motivo))throw new ArgumentException("Cancelamento exige motivo.");await using var cn=Connection();var n=await cn.ExecuteAsync(new CommandDefinition("update plantaopro.adm360_inventarios set situacao='CANCELADO',motivo_ajuste=@motivo,versao=versao+1 where id=@inventarioId and tenant_id=@tenantId and situacao in ('ABERTO','CONTAGEM','REVISAO')",new{tenantId,inventarioId,motivo},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Inventário não pode ser cancelado.");}
}
