using System.Security.Claims;
using Dapper;
using Npgsql;
using PlantaoPro.Api.Models;
namespace PlantaoPro.Api;
public sealed class MeuDiaRepository : IMeuDiaRepository
{
    private readonly IConfiguration _cfg; public MeuDiaRepository(IConfiguration cfg)=>_cfg=cfg; private NpgsqlConnection Cn()=>new(_cfg.GetConnectionString("Default")); static Guid? Parse(string? v)=>Guid.TryParse(v,out var id)?id:null;
    public async Task<MeuDiaDto> ObterResumoAsync(ClaimsPrincipal user, CancellationToken ct=default){var uid=Parse(user.FindFirstValue("uid")??user.FindFirstValue(ClaimTypes.NameIdentifier)); var tenant=Parse(user.FindFirstValue("tenant_id")); var cliente=Parse(user.FindFirstValue("cliente_id")); await using var cn=Cn(); var p=(await cn.QueryAsync<MeuDiaItemDto>(@"select p.id Id,'plantao' Tipo,'Plantão pendente' Titulo,coalesce(h.nome_fantasia,h.razao_social,'Hospital') || ' • ' || coalesce(e.nome,'Especialidade') Descricao,'alta' Prioridade,p.data_inicio Prazo,'Coordenação' Responsavel,coalesce(p.status,'ABERTO') Status,'bi-calendar-event' Icone,'Plantoes' Controller,'Details' Action,true PodeConcluir,true PodeAdiar,p.tenant_id TenantId,p.cliente_id ClienteId from plantaopro.plantoes p left join plantaopro.hospitais h on h.id=p.hospital_id left join plantaopro.especialidades e on e.id=p.especialidade_id where (@tenant is null or p.tenant_id=@tenant) and coalesce(p.status,'ABERTO') in ('ABERTO','PENDENTE') order by p.data_inicio limit 8", new{tenant})).ToArray(); var a=(await cn.QueryAsync<MeuDiaItemDto>(@"select n.id Id,'notificacao' Tipo,n.titulo Titulo,n.mensagem Descricao,'media' Prioridade,n.reg_date Prazo,'Sistema' Responsavel,case when n.lida then 'lido' else 'aberto' end Status,'bi-bell' Icone,'Notificacoes' Controller,'Index' Action,false,true,@tenant TenantId,@cliente ClienteId from plantaopro.notificacoes n where (@uid is null or n.usuario_id=@uid) and coalesce(n.lida,false)=false order by n.reg_date desc limit 8", new{uid,tenant,cliente})).ToArray(); var indicadores=new[]{new MeuDiaIndicadorDto("pendencias","Pendências",p.Length,"bi-check2-circle",p.Length>0?"warning":"success"),new MeuDiaIndicadorDto("alertas","Alertas",a.Length,"bi-bell",a.Length>0?"warning":"success")}; var quick=new[]{new MeuDiaItemDto(Guid.Parse("00000000-0000-0000-0000-000000000001"),"acao","Abrir agenda","Consultar agenda operacional do contexto atual.","baixa",DateTime.UtcNow.Date,"Sistema","aberto","bi-calendar2-week","Agenda","Index",false,false,tenant,cliente)}; return new(indicadores,p,Array.Empty<MeuDiaItemDto>(),a,quick);}
    public async Task<MeuDiaItemDto> AlterarEstadoAsync(Guid id,string status,MeuDiaEstadoRequest request,ClaimsPrincipal user,CancellationToken ct=default){var uid=Parse(user.FindFirstValue("uid")??user.FindFirstValue(ClaimTypes.NameIdentifier)); await using var cn=Cn(); await cn.ExecuteAsync("insert into plantaopro.meu_dia_historico(id,usuario_id,item_estado_id,evento,detalhes,reg_date,reg_status) values(gen_random_uuid(),@uid,@id,@status,jsonb_build_object('motivo',@Motivo,'novaData',@NovaData),now(),'A')", new{uid,id,status,request.Motivo,request.NovaData}); return new(id,"estado","Item atualizado",request.Motivo??"Estado alterado com auditoria","media",request.NovaData,"Sistema",status,"bi-check2","MeuDia","Index",status!="concluido",status!="adiado");}
}
