create schema if not exists plantaopro;
insert into plantaopro.v115_regras_faturamento(codigo,nome,tipo_faturamento,valor_base,percentual_desconto,percentual_acrescimo,status,reg_status)
select * from (values ('CONS_PART_DEMO','Consulta particular demo','CONSULTA',250.00,0.00,0.00,'ATIVA','A'),('CONS_CONV_DEMO','Consulta convênio demo','CONSULTA',180.00,5.00,0.00,'ATIVA','A'),('PLANTAO_DEMO','Plantão realizado demo','PLANTAO',1200.00,0.00,0.00,'ATIVA','A')) as v(codigo,nome,tipo_faturamento,valor_base,percentual_desconto,percentual_acrescimo,status,reg_status) where not exists (select 1 from plantaopro.v115_regras_faturamento r where r.codigo=v.codigo);
insert into plantaopro.v115_regras_repasse(tipo_regra,percentual,valor_fixo,status,reg_status) select 'PERCENTUAL',70.00,0.00,'REGRA_ATIVA','A' where not exists (select 1 from plantaopro.v115_regras_repasse where tipo_regra='PERCENTUAL' and status='REGRA_ATIVA');
insert into plantaopro.v115_regras_repasse(tipo_regra,percentual,valor_fixo,status,reg_status) select 'VALOR_FIXO',0.00,900.00,'REGRA_ATIVA','A' where not exists (select 1 from plantaopro.v115_regras_repasse where tipo_regra='VALOR_FIXO' and status='REGRA_ATIVA');
insert into plantaopro.v115_regras_glosa(motivo,valor_glosado,percentual_glosa,status,reg_status) select 'Glosa demo por regra de convênio',45.00,10.00,'ABERTA','A' where not exists (select 1 from plantaopro.v115_regras_glosa where motivo='Glosa demo por regra de convênio');
insert into plantaopro.v115_configuracoes_financeiras(chave,valor,escopo,status,reg_status) select 'demo_boleto_modo','DEMO_EXPLICITO','TENANT','ATIVA','A' where not exists (select 1 from plantaopro.v115_configuracoes_financeiras where chave='demo_boleto_modo');
insert into plantaopro.v115_alertas_operacionais(tipo,prioridade,perfil_responsavel,modulo,cta,rota,prazo,status,origem_regra,reg_status) select 'REGRA_FATURAMENTO_AUSENTE','ALTA','FINANCEIRO','Faturamento Clínico','Configurar regra','/FaturamentoClinico/Regras',now()+interval '2 days','ABERTA','seed_demo_v115','A' where not exists (select 1 from plantaopro.v115_alertas_operacionais where tipo='REGRA_FATURAMENTO_AUSENTE');
insert into plantaopro.v115_jornada_perfil_progresso(perfil,passo,rota,cta,pendencia_relacionada,status,reg_status) select perfil,passo,rota,cta,pendencia,'PENDENTE','A' from (values ('RECEPCAO','Cadastrar paciente','/Pacientes/Create','Cadastrar paciente','Paciente sem cadastro'),('TRIAGEM','Classificar risco','/Triagem','Iniciar triagem','Atendimento aguardando triagem'),('MEDICO','Ver pagamentos','/FaturamentoClinico/RepassesMedicos','Ver repasses','Repasses previstos'),('FINANCEIRO','Gerar conta','/FaturamentoClinico/ContasReceber','Gerar conta','Consulta finalizada sem conta'),('COORDENACAO','Confirmar escala','/Escalas','Confirmar escala','Escala pendente'),('ADMIN_CLIENTE','Configurar regras financeiras','/FaturamentoClinico/Configuracoes','Configurar regras','Regra ausente')) as v(perfil,passo,rota,cta,pendencia) where not exists (select 1 from plantaopro.v115_jornada_perfil_progresso j where j.perfil=v.perfil and j.passo=v.passo);
insert into plantaopro.v115_configuracoes_mobile(perfil,chave,valor,status,reg_status) select 'MEDICO','atalhos_financeiros','{"atalhos":["repasses previstos","pagamentos pendentes","contestar pagamento","próximos plantões"]}'::jsonb,'ATIVA','A' where not exists (select 1 from plantaopro.v115_configuracoes_mobile where perfil='MEDICO' and chave='atalhos_financeiros');
