services:
  api:
    build:
      context: .
      dockerfile: Backend/Presentation/BarberSync.Api/Dockerfile
    ports: ["8080:8080"]
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
  adminweb:
    build:
      context: .
      dockerfile: Web/BarberSync.AdminWeb/Dockerfile
    ports: ["8081:8080"]
    environment:
      ASPNETCORE_URLS: http://+:8080
      ApiSettings__BaseUrl: http://api:8080
    depends_on: [api]
  publicweb:
    build:
      context: .
      dockerfile: Web/BarberSync.PublicWeb/Dockerfile
    ports: ["8082:8080"]
    environment:
      ASPNETCORE_URLS: http://+:8080
      ApiSettings__BaseUrl: http://api:8080
    depends_on: [api]
  kioskweb:
    build:
      context: .
      dockerfile: Web/BarberSync.KioskWeb/Dockerfile
    ports: ["8083:8080"]
    environment:
      ASPNETCORE_URLS: http://+:8080
      ApiSettings__BaseUrl: http://api:8080
    depends_on: [api]
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports: ["5341:80"]
