using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantaoPro.Api.Clinical;
using PlantaoPro.Api.Data;
using PlantaoPro.Api.Models;

namespace PlantaoPro.Api.Controllers;

[ApiController,Authorize(Policy="Consulta.VerDadosSensiveis"),Route("api/pacientes/{pacienteId:guid}")]
public sealed class ProntuarioController : ControllerBase
{
    private readonly ILongitudinalService service; private readonly ILongitudinalRepository repo; private readonly ICurrentUserService user; private readonly IClinicalAccessService access; private readonly IAuditService audit;
    public ProntuarioController(ILongitudinalService service,ILongitudinalRepository repo,ICurrentUserService user,IClinicalAccessService access,IAuditService audit){this.service=service;this.repo=repo;this.user=user;this.access=access;this.audit=audit;}
    private Guid Tenant=>user.ClienteId??user.TenantId??Guid.Empty; private IActionResult Out<T>(ApiResponse<T> r)=>StatusCode(r.StatusCode,r);
    private ApiResponse<T>? Guard<T>(bool write=false){var a=access.Authorize(write);return a.Success?null:ApiResponse<T>.Fail(a.Message,a.StatusCode);}
    private Task Audit(Guid p,string action,Guid? id=null)=>audit.RegistrarAsync(user.UserId,Tenant,"prontuario",id??p,action,new{pacienteId=p,entidadeId=id,resultado="SUCESSO"},true,HttpContext.Connection.RemoteIpAddress?.ToString(),string.Join(',',user.Roles));
    [HttpGet("prontuario")] public async Task<IActionResult> Prontuario(Guid pacienteId,CancellationToken ct)=>Out(await service.ProntuarioAsync(pacienteId,ct));
    [HttpGet("timeline")] public async Task<IActionResult> Timeline(Guid pacienteId,CancellationToken ct)=>Out(await service.TimelineAsync(pacienteId,ct));
    [HttpGet("problemas")] public async Task<IActionResult> Problemas(Guid pacienteId,CancellationToken ct){var g=Guard<IReadOnlyList<PacienteProblemaDto>>();return g is null?Out(ApiResponse<IReadOnlyList<PacienteProblemaDto>>.Ok(await repo.ProblemasAsync(Tenant,pacienteId,ct))):Out(g);}
    [HttpPost("problemas")] public async Task<IActionResult> CriarProblema(Guid pacienteId,CriarProblemaRequest r,CancellationToken ct){var g=Guard<PacienteProblemaDto>(true);if(g is not null)return Out(g);var x=await repo.CriarProblemaAsync(Tenant,pacienteId,r,user.UserId,ct);await Audit(pacienteId,"PROBLEMA_ALTERAR",x?.Id);return x is null?Out(ApiResponse<PacienteProblemaDto>.Fail("Paciente ou CID inválido.",422)):StatusCode(201,ApiResponse<PacienteProblemaDto>.Ok(x));}
    [HttpPut("problemas/{id:guid}")] public async Task<IActionResult> AtualizarProblema(Guid pacienteId,Guid id,AtualizarProblemaRequest r,CancellationToken ct){var g=Guard<bool>(true);if(g is not null)return Out(g);var ok=await repo.AtualizarProblemaAsync(Tenant,pacienteId,id,r,user.UserId,ct);if(ok)await Audit(pacienteId,"PROBLEMA_ALTERAR",id);return Out(ok?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("O registro foi alterado em outra sessão. Recarregue os dados antes de salvar.",409));}
    [HttpPost("problemas/{id:guid}/resolver")] public async Task<IActionResult> Resolver(Guid pacienteId,Guid id,ResolverProblemaRequest r,CancellationToken ct){var g=Guard<bool>(true);if(g is not null)return Out(g);var ok=await repo.ResolverProblemaAsync(Tenant,pacienteId,id,r,user.UserId,ct);if(ok)await Audit(pacienteId,"PROBLEMA_RESOLVER",id);return Out(ok?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("O registro foi alterado em outra sessão. Recarregue os dados antes de salvar.",409));}
    [HttpGet("alergias")] public async Task<IActionResult> Alergias(Guid pacienteId,CancellationToken ct){var g=Guard<IReadOnlyList<PacienteAlergiaDto>>();return g is null?Out(ApiResponse<IReadOnlyList<PacienteAlergiaDto>>.Ok(await repo.AlergiasAsync(Tenant,pacienteId,ct))):Out(g);}
    [HttpPost("alergias")] public async Task<IActionResult> CriarAlergia(Guid pacienteId,CriarAlergiaRequest r,CancellationToken ct){var g=Guard<PacienteAlergiaDto>(true);if(g is not null)return Out(g);var x=await repo.CriarAlergiaAsync(Tenant,pacienteId,r,user.UserId,ct);await Audit(pacienteId,"ALERGIA_ALTERAR",x?.Id);return StatusCode(201,ApiResponse<PacienteAlergiaDto>.Ok(x!));}
    [HttpPut("alergias/{id:guid}")] public async Task<IActionResult> AtualizarAlergia(Guid pacienteId,Guid id,AtualizarAlergiaRequest r,CancellationToken ct){var g=Guard<bool>(true);if(g is not null)return Out(g);var ok=await repo.AtualizarAlergiaAsync(Tenant,pacienteId,id,r,user.UserId,ct);if(ok)await Audit(pacienteId,"ALERGIA_ALTERAR",id);return Out(ok?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("O registro foi alterado em outra sessão. Recarregue os dados antes de salvar.",409));}
    [HttpGet("medicamentos")] public async Task<IActionResult> Medicamentos(Guid pacienteId,CancellationToken ct){var g=Guard<IReadOnlyList<PacienteMedicamentoDto>>();return g is null?Out(ApiResponse<IReadOnlyList<PacienteMedicamentoDto>>.Ok(await repo.MedicamentosAsync(Tenant,pacienteId,ct))):Out(g);}
    [HttpPost("medicamentos")] public async Task<IActionResult> CriarMedicamento(Guid pacienteId,CriarMedicamentoUsoRequest r,CancellationToken ct){var g=Guard<PacienteMedicamentoDto>(true);if(g is not null)return Out(g);var x=await repo.CriarMedicamentoAsync(Tenant,pacienteId,r,user.UserId,ct);await Audit(pacienteId,"MEDICAMENTO_ALTERAR",x?.Id);return StatusCode(201,ApiResponse<PacienteMedicamentoDto>.Ok(x!));}
    [HttpPut("medicamentos/{id:guid}")] public async Task<IActionResult> AtualizarMedicamento(Guid pacienteId,Guid id,AtualizarMedicamentoUsoRequest r,CancellationToken ct){var g=Guard<bool>(true);if(g is not null)return Out(g);var ok=await repo.AtualizarMedicamentoAsync(Tenant,pacienteId,id,r,user.UserId,ct);if(ok)await Audit(pacienteId,"MEDICAMENTO_ALTERAR",id);return Out(ok?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("O registro foi alterado em outra sessão. Recarregue os dados antes de salvar.",409));}
    [HttpGet("exames")] public async Task<IActionResult> Exames(Guid pacienteId,CancellationToken ct){var g=Guard<IReadOnlyList<SolicitacaoExameDto>>();return g is null?Out(ApiResponse<IReadOnlyList<SolicitacaoExameDto>>.Ok(await repo.ExamesAsync(Tenant,pacienteId,ct))):Out(g);}
    [HttpGet("encaminhamentos")] public async Task<IActionResult> Encaminhamentos(Guid pacienteId,CancellationToken ct){var g=Guard<IReadOnlyList<EncaminhamentoClinicoDto>>();return g is null?Out(ApiResponse<IReadOnlyList<EncaminhamentoClinicoDto>>.Ok(await repo.EncaminhamentosAsync(Tenant,pacienteId,ct))):Out(g);}
}

[ApiController,Authorize(Policy="Consulta.VerDadosSensiveis"),Route("api/exames/solicitacoes")]
public sealed class ExamesController : ControllerBase
{
    private readonly ILongitudinalRepository repo;private readonly ICurrentUserService user;private readonly IClinicalAccessService access;public ExamesController(ILongitudinalRepository r,ICurrentUserService u,IClinicalAccessService a){repo=r;user=u;access=a;}private Guid T=>user.ClienteId??user.TenantId??Guid.Empty;private IActionResult O<TV>(ApiResponse<TV> r)=>StatusCode(r.StatusCode,r);
    [HttpGet]public async Task<IActionResult> List(CancellationToken ct){var a=access.Authorize();return a.Success?O(ApiResponse<IReadOnlyList<SolicitacaoExameDto>>.Ok(await repo.ExamesAsync(T,null,ct))):O(ApiResponse<IReadOnlyList<SolicitacaoExameDto>>.Fail(a.Message,a.StatusCode));}
    [HttpGet("{id:guid}")]public async Task<IActionResult> Get(Guid id,CancellationToken ct){var x=await repo.ExameAsync(T,id,ct);return O(x is null?ApiResponse<SolicitacaoExameDto>.Fail("Solicitação não encontrada.",404):ApiResponse<SolicitacaoExameDto>.Ok(x));}
    [HttpPost("{id:guid}/cancelar")]public async Task<IActionResult> Cancel(Guid id,CancellationToken ct)=>O(await repo.CancelarExameAsync(T,id,user.UserId,ct)?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("Solicitação não encontrada ou não pode ser cancelada.",409));
    [HttpPost("{id:guid}/resultado")]public async Task<IActionResult> Result(Guid id,RegistrarResultadoExameRequest r,CancellationToken ct){var x=await repo.ResultadoAsync(T,id,r,user.UserId,ct);return x is null?O(ApiResponse<ResultadoExameDto>.Fail("Solicitação não encontrada ou cancelada.",409)):StatusCode(201,ApiResponse<ResultadoExameDto>.Ok(x));}
}

[ApiController,Authorize(Policy="Consulta.Editar"),Route("api/consultas/{consultaId:guid}")]
public sealed class ConsultaLongitudinalController:ControllerBase
{private readonly ILongitudinalRepository repo;private readonly ICurrentUserService user;public ConsultaLongitudinalController(ILongitudinalRepository r,ICurrentUserService u){repo=r;user=u;}private Guid T=>user.ClienteId??user.TenantId??Guid.Empty;
 [HttpPost("exames")]public async Task<IActionResult> Exames(Guid consultaId,CriarSolicitacaoExamesRequest r,CancellationToken ct){var x=await repo.CriarExamesAsync(T,consultaId,r,user.UserId,ct);return x is null?NotFound(ApiResponse<SolicitacaoExameDto>.Fail("Consulta não encontrada.",404)):StatusCode(201,ApiResponse<SolicitacaoExameDto>.Ok(x));}
 [HttpPost("encaminhamentos")]public async Task<IActionResult> Encaminhamento(Guid consultaId,CriarEncaminhamentoClinicoRequest r,CancellationToken ct){var x=await repo.CriarEncaminhamentoAsync(T,consultaId,r,user.UserId,ct);return x is null?NotFound(ApiResponse<EncaminhamentoClinicoDto>.Fail("Consulta não encontrada.",404)):StatusCode(201,ApiResponse<EncaminhamentoClinicoDto>.Ok(x));}}

[ApiController,Authorize(Policy="Consulta.VerDadosSensiveis"),Route("api/documentos")]
public sealed class DocumentosClinicosController:ControllerBase
{private readonly ILongitudinalRepository repo;private readonly ICurrentUserService user;private readonly IClinicalDocumentSignatureProvider signature;public DocumentosClinicosController(ILongitudinalRepository r,ICurrentUserService u,IClinicalDocumentSignatureProvider s){repo=r;user=u;signature=s;}private Guid T=>user.ClienteId??user.TenantId??Guid.Empty;
 [HttpGet("{id:guid}")]public async Task<IActionResult> Get(Guid id,CancellationToken ct){var x=await repo.DocumentoAsync(T,id,ct);return x is null?NotFound(ApiResponse<DocumentoClinicoDto>.Fail("Documento não encontrado.",404)):Ok(ApiResponse<DocumentoClinicoDto>.Ok(x));}
 [HttpPost]public async Task<IActionResult> Create(CriarDocumentoClinicoRequest r,CancellationToken ct){var x=await repo.CriarDocumentoAsync(T,r,user.UserId,signature.InitialStatus,ct);return x is null?UnprocessableEntity(ApiResponse<DocumentoClinicoDto>.Fail("Paciente ou consulta inválida.",422)):StatusCode(201,ApiResponse<DocumentoClinicoDto>.Ok(x));}
 [HttpPost("{id:guid}/cancelar")]public async Task<IActionResult> Cancel(Guid id,CancelarDocumentoClinicoRequest r,CancellationToken ct){var ok=await repo.CancelarDocumentoAsync(T,id,r,user.UserId,ct);return StatusCode(ok?200:409,ok?ApiResponse<bool>.Ok(true):ApiResponse<bool>.Fail("O registro foi alterado em outra sessão. Recarregue os dados antes de salvar.",409));}}
