using System.Collections.Concurrent;
using Microsoft.AspNetCore.Mvc;

namespace PlantaoPro.Api.Controllers;

[ApiController]
public sealed class V112HomologationController : ControllerBase
{
    private static readonly V112Store Store = new();

    [HttpGet("api/customers")] public IActionResult Customers([FromQuery] string? q, [FromQuery] string? status, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) => Ok(Store.Page(Store.Customers.Values.Where(x => Store.Match(q, x.Name, x.Document, x.Email) && Store.Status(status, x.Active)), page, pageSize));
    [HttpGet("api/customers/{id:guid}")] public IActionResult Customer(Guid id) => Store.Customers.TryGetValue(id, out var item) ? Ok(item) : NotFound(new { error = "Cliente não encontrado" });
    [HttpPost("api/customers")] public IActionResult CreateCustomer([FromBody] CustomerDto dto) { var item = dto with { Id = Guid.NewGuid(), Active = true, CreatedAt = DateTime.UtcNow }; Store.Customers[item.Id] = item; Store.Audit("customers", item.Id, "create"); return Created($"/api/customers/{item.Id}", item); }
    [HttpPut("api/customers/{id:guid}")] public IActionResult UpdateCustomer(Guid id, [FromBody] CustomerDto dto) { if (!Store.Customers.ContainsKey(id)) return NotFound(); Store.Customers[id] = dto with { Id = id, UpdatedAt = DateTime.UtcNow }; Store.Audit("customers", id, "update"); return Ok(Store.Customers[id]); }
    [HttpDelete("api/customers/{id:guid}")] public IActionResult DeleteCustomer(Guid id) { if (!Store.Customers.TryGetValue(id, out var item)) return NotFound(); Store.Customers[id] = item with { Active = false, UpdatedAt = DateTime.UtcNow }; Store.Audit("customers", id, "inactive"); return Ok(Store.Customers[id]); }

    [HttpGet("api/products")] public IActionResult Products([FromQuery] string? q, [FromQuery] string? status, [FromQuery] bool? critical, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) { var items = Store.Products.Values.Where(x => Store.Match(q, x.Name, x.Code) && Store.Status(status, x.Active)).Select(x => x with { Balance = Store.Balance(x.Id) }); if (critical == true) items = items.Where(x => x.Balance <= x.MinimumStock); return Ok(Store.Page(items, page, pageSize)); }
    [HttpGet("api/products/{id:guid}")] public IActionResult Product(Guid id) => Store.Products.TryGetValue(id, out var item) ? Ok(item with { Balance = Store.Balance(id) }) : NotFound();
    [HttpPost("api/products")] public IActionResult CreateProduct([FromBody] ProductDto dto) { var item = dto with { Id = Guid.NewGuid(), Active = true, CreatedAt = DateTime.UtcNow }; Store.Products[item.Id] = item; Store.Audit("products", item.Id, "create"); return Created($"/api/products/{item.Id}", item); }
    [HttpPut("api/products/{id:guid}")] public IActionResult UpdateProduct(Guid id, [FromBody] ProductDto dto) { if (!Store.Products.ContainsKey(id)) return NotFound(); Store.Products[id] = dto with { Id = id, UpdatedAt = DateTime.UtcNow }; Store.Audit("products", id, "update"); return Ok(Store.Products[id]); }
    [HttpDelete("api/products/{id:guid}")] public IActionResult DeleteProduct(Guid id) { if (!Store.Products.TryGetValue(id, out var item)) return NotFound(); Store.Products[id] = item with { Active = false, UpdatedAt = DateTime.UtcNow }; Store.Audit("products", id, "inactive"); return Ok(Store.Products[id]); }

    [HttpGet("api/inventory/balance")] public IActionResult Balance() => Ok(Store.Products.Values.Select(p => new { productId = p.Id, p.Code, p.Name, balance = Store.Balance(p.Id), minimumStock = p.MinimumStock, critical = Store.Balance(p.Id) <= p.MinimumStock }));
    [HttpGet("api/inventory/movements")] public IActionResult Movements() => Ok(Store.InventoryMovements.OrderByDescending(x => x.CreatedAt));
    [HttpPost("api/inventory/entries")] public IActionResult Entry([FromBody] InventoryEntryDto dto) { if (!Store.Products.ContainsKey(dto.ProductId)) return BadRequest(new { error = "Produto inválido" }); var mov = new InventoryMovementDto(Guid.NewGuid(), dto.ProductId, dto.Quantity, "ENTRY", dto.Note ?? "Entrada v1.12", DateTime.UtcNow); Store.InventoryMovements.Add(mov); Store.Audit("inventory", mov.Id, "entry"); return Ok(mov); }

    [HttpGet("api/orders")] public IActionResult Orders() => Ok(Store.Orders.Values.OrderByDescending(x => x.CreatedAt));
    [HttpGet("api/orders/{id:guid}")] public IActionResult Order(Guid id) => Store.Orders.TryGetValue(id, out var o) ? Ok(o) : NotFound();
    [HttpPost("api/orders")] public IActionResult CreateOrder([FromBody] CreateOrderDto dto) { if (!Store.Customers.ContainsKey(dto.CustomerId)) return BadRequest(new { error = "Cliente inválido" }); var order = new OrderDto(Guid.NewGuid(), dto.CustomerId, "DRAFT", [], 0, DateTime.UtcNow, null); Store.Orders[order.Id] = order; Store.Audit("orders", order.Id, "create"); return Created($"/api/orders/{order.Id}", order); }
    [HttpPost("api/orders/{id:guid}/items")] public IActionResult AddItem(Guid id, [FromBody] OrderItemDto dto) { if (!Store.Orders.TryGetValue(id, out var o) || !Store.Products.TryGetValue(dto.ProductId, out var p)) return NotFound(); var item = dto with { Id = Guid.NewGuid(), UnitPrice = dto.UnitPrice <= 0 ? p.Price : dto.UnitPrice }; var items = o.Items.Append(item).ToList(); Store.Orders[id] = o with { Items = items, Total = items.Sum(i => i.Quantity * i.UnitPrice) }; return Ok(Store.Orders[id]); }
    [HttpDelete("api/orders/{id:guid}/items/{itemId:guid}")] public IActionResult RemoveItem(Guid id, Guid itemId) { if (!Store.Orders.TryGetValue(id, out var o)) return NotFound(); var items = o.Items.Where(i => i.Id != itemId).ToList(); Store.Orders[id] = o with { Items = items, Total = items.Sum(i => i.Quantity * i.UnitPrice) }; return Ok(Store.Orders[id]); }
    [HttpPost("api/orders/{id:guid}/confirm")] public IActionResult Confirm(Guid id) { if (!Store.Orders.TryGetValue(id, out var o)) return NotFound(); var missing = o.Items.FirstOrDefault(i => Store.Balance(i.ProductId) < i.Quantity); if (missing is not null) return BadRequest(new { error = "Estoque insuficiente", missing.ProductId }); foreach (var i in o.Items) Store.InventoryMovements.Add(new(Guid.NewGuid(), i.ProductId, -i.Quantity, "ORDER_CONFIRM", $"Pedido {id}", DateTime.UtcNow)); Store.Orders[id] = o with { Status = "CONFIRMED", UpdatedAt = DateTime.UtcNow }; var t = new TaskDto(Guid.NewGuid(), id, "Separar pedido", "PENDING", null, [], DateTime.UtcNow, null); Store.Tasks[t.Id] = t; return Ok(Store.Orders[id]); }
    [HttpPost("api/orders/{id:guid}/cancel")] public IActionResult Cancel(Guid id) { if (!Store.Orders.TryGetValue(id, out var o)) return NotFound(); Store.Orders[id] = o with { Status = "CANCELED", UpdatedAt = DateTime.UtcNow }; return Ok(Store.Orders[id]); }

    [HttpGet("api/tasks/my")] public IActionResult MyTasks([FromQuery] string? status) => Ok(Store.Tasks.Values.Where(t => string.IsNullOrWhiteSpace(status) || t.Status.Equals(status, StringComparison.OrdinalIgnoreCase)));
    [HttpGet("api/tasks/{id:guid}")] public IActionResult TaskById(Guid id) => Store.Tasks.TryGetValue(id, out var t) ? Ok(t) : NotFound();
    [HttpPost("api/tasks/{id:guid}/claim")] public IActionResult Claim(Guid id) { if (!Store.Tasks.TryGetValue(id, out var t)) return NotFound(); Store.Tasks[id] = t with { Owner = "homologador", Status = "CLAIMED" }; return Ok(Store.Tasks[id]); }
    [HttpPost("api/tasks/{id:guid}/comments")] public IActionResult Comment(Guid id, [FromBody] CommentDto dto) { if (!Store.Tasks.TryGetValue(id, out var t)) return NotFound(); Store.Tasks[id] = t with { Comments = t.Comments.Append(dto.Text).ToList() }; return Ok(Store.Tasks[id]); }
    [HttpPost("api/tasks/{id:guid}/complete")] public IActionResult Complete(Guid id) { if (!Store.Tasks.TryGetValue(id, out var t)) return NotFound(); Store.Tasks[id] = t with { Status = "DONE", UpdatedAt = DateTime.UtcNow }; return Ok(Store.Tasks[id]); }

    [HttpGet("api/billing/invoices")] public IActionResult Invoices() => Ok(Store.Invoices.Values);
    [HttpGet("api/billing/titles")] public IActionResult Titles() => Ok(Store.Titles.Values);
    [HttpPost("api/billing/invoices/from-order/{orderId:guid}")] public IActionResult Invoice(Guid orderId) { if (!Store.Orders.TryGetValue(orderId, out var o) || o.Status != "CONFIRMED") return BadRequest(new { error = "Pedido não confirmado" }); var inv = new InvoiceDto(Guid.NewGuid(), orderId, o.Total, "ISSUED", DateTime.UtcNow); Store.Invoices[inv.Id] = inv; return Ok(inv); }
    [HttpPost("api/billing/invoices/{invoiceId:guid}/titles")] public IActionResult Title(Guid invoiceId) { if (!Store.Invoices.TryGetValue(invoiceId, out var inv)) return NotFound(); var title = new TitleDto(Guid.NewGuid(), invoiceId, inv.Amount, "OPEN", false, DateTime.UtcNow.AddDays(7)); Store.Titles[title.Id] = title; return Ok(title); }
    [HttpPost("api/billing/titles/{titleId:guid}/fake-boleto")] public IActionResult Boleto(Guid titleId) { if (!Store.Titles.TryGetValue(titleId, out var t)) return NotFound(); Store.Titles[titleId] = t with { FakeBoleto = true }; var ev = new OutboxDto(Guid.NewGuid(), "BILLING_BOLETO_FAKE", titleId.ToString(), "PENDING", null, DateTime.UtcNow); Store.Outbox[ev.Id] = ev; return Ok(new { title = Store.Titles[titleId], outbox = ev }); }

    [HttpGet("api/outbox")] public IActionResult Outbox() => Ok(Store.Outbox.Values.OrderByDescending(x => x.CreatedAt));
    [HttpPost("api/outbox/{id:guid}/process")] public IActionResult Process(Guid id) { if (!Store.Outbox.TryGetValue(id, out var e)) return NotFound(); Store.Outbox[id] = e with { Status = "PROCESSED", Error = null }; Store.OutboxLog.Add(new(Guid.NewGuid(), id, "PROCESSED", "Envio fake registrado", DateTime.UtcNow)); return Ok(Store.Outbox[id]); }
    [HttpPost("api/outbox/{id:guid}/retry")] public IActionResult Retry(Guid id) => Process(id);

    [HttpGet("api/templates")] public IActionResult Templates() => Ok(Store.Templates);
    [HttpGet("api/templates/{id}")] public IActionResult Template(string id) => Store.Templates.FirstOrDefault(t => t.Id == id) is { } t ? Ok(t) : NotFound();
    [HttpPost("api/templates/{id}/install")] public IActionResult Install(string id) { var template = Store.Templates.FirstOrDefault(t => t.Id == id); if (template is null) return NotFound(); var inst = new TemplateInstallDto(Guid.NewGuid(), id, DateTime.UtcNow, "INSTALLED"); Store.TemplateInstalls.Add(inst); return Ok(inst); }

    [HttpGet("api/dashboard")] public IActionResult Dashboard() => Ok(Store.Dashboard());
    [HttpGet("api/journey/what-to-do-now")] public IActionResult WhatNow() => Ok(Store.NextAction());
    [HttpGet("api/journey/progress")] public IActionResult Progress() => Ok(Store.Progress());
    [HttpGet("api/journey/recommended-actions")] public IActionResult Recommended() => Ok(Store.Recommended());
    [HttpPost("api/journey/recommended-actions/{id}/complete")] public IActionResult CompleteRecommended(string id) { Store.CompletedActions.Add(id); return Ok(Store.NextAction()); }
    [HttpPost("api/journey/recommended-actions/{id}/dismiss")] public IActionResult DismissRecommended(string id) { Store.CompletedActions.Add("dismissed:" + id); return Ok(Store.NextAction()); }
    [HttpPost("api/journey/steps/{stepId}/complete")] public IActionResult CompleteStep(string stepId) { Store.CompletedActions.Add("step:" + stepId); return Ok(Store.Progress()); }
    [HttpGet("api/activities")] public IActionResult Activities() => Ok(Store.Activities());
    [HttpGet("api/demo/status")] public IActionResult DemoStatus() => Ok(Store.Demo());
    [HttpPost("api/demo/run-step/{stepCode}")] public IActionResult RunStep(string stepCode) => Ok(Store.RunStep(stepCode));
    [HttpPost("api/demo/run-all")] public IActionResult RunAll() => Ok(Store.RunAll());
    [HttpGet("api/homologation/status")] public IActionResult Homologation() => Ok(Store.Homologation());
    [HttpPost("api/homologation/run-all")] public IActionResult HomologationRunAll() => Ok(Store.Homologation());
    [HttpPost("api/homologation/run-check/{checkCode}")] public IActionResult HomologationCheck(string checkCode) => Ok(Store.Homologation().FirstOrDefault(x => x.Code == checkCode) ?? new CheckDto(checkCode, "UNKNOWN", "Check não cadastrado", null, "/homologation"));
    [HttpGet("api/validation/worker/status")] public IActionResult Worker() => Ok(new { status = "READY", pending = Store.Outbox.Values.Count(x => x.Status == "PENDING"), processed = Store.Outbox.Values.Count(x => x.Status == "PROCESSED"), logs = Store.OutboxLog.Count });
}

public sealed record CustomerDto(Guid Id, string Name, string Document, string Email, bool Active, DateTime CreatedAt, DateTime? UpdatedAt);
public sealed record ProductDto(Guid Id, string Code, string Name, decimal Price, decimal MinimumStock, bool Active, decimal Balance, DateTime CreatedAt, DateTime? UpdatedAt);
public sealed record InventoryEntryDto(Guid ProductId, decimal Quantity, string? Note);
public sealed record InventoryMovementDto(Guid Id, Guid ProductId, decimal Quantity, string Type, string Note, DateTime CreatedAt);
public sealed record CreateOrderDto(Guid CustomerId);
public sealed record OrderItemDto(Guid Id, Guid ProductId, decimal Quantity, decimal UnitPrice);
public sealed record OrderDto(Guid Id, Guid CustomerId, string Status, List<OrderItemDto> Items, decimal Total, DateTime CreatedAt, DateTime? UpdatedAt);
public sealed record TaskDto(Guid Id, Guid OrderId, string Title, string Status, string? Owner, List<string> Comments, DateTime CreatedAt, DateTime? UpdatedAt);
public sealed record CommentDto(string Text);
public sealed record InvoiceDto(Guid Id, Guid OrderId, decimal Amount, string Status, DateTime CreatedAt);
public sealed record TitleDto(Guid Id, Guid InvoiceId, decimal Amount, string Status, bool FakeBoleto, DateTime DueDate);
public sealed record OutboxDto(Guid Id, string Type, string PayloadRef, string Status, string? Error, DateTime CreatedAt);
public sealed record OutboxLogDto(Guid Id, Guid OutboxId, string Status, string Detail, DateTime CreatedAt);
public sealed record TemplateDto(string Id, string Name, string Description);
public sealed record TemplateInstallDto(Guid Id, string TemplateId, DateTime InstalledAt, string Status);
public sealed record CheckDto(string Code, string Status, string Detail, string? Error, string OpenUrl);

internal sealed class V112Store
{
    public ConcurrentDictionary<Guid, CustomerDto> Customers { get; } = new(); public ConcurrentDictionary<Guid, ProductDto> Products { get; } = new(); public ConcurrentDictionary<Guid, OrderDto> Orders { get; } = new(); public ConcurrentDictionary<Guid, TaskDto> Tasks { get; } = new(); public ConcurrentDictionary<Guid, InvoiceDto> Invoices { get; } = new(); public ConcurrentDictionary<Guid, TitleDto> Titles { get; } = new(); public ConcurrentDictionary<Guid, OutboxDto> Outbox { get; } = new(); public ConcurrentBag<InventoryMovementDto> InventoryMovements { get; } = new(); public ConcurrentBag<OutboxLogDto> OutboxLog { get; } = new(); public ConcurrentBag<TemplateInstallDto> TemplateInstalls { get; } = new(); public ConcurrentBag<string> CompletedActions { get; } = new();
    public List<TemplateDto> Templates { get; } = [new("pedido-faturamento", "Pedido ao Faturamento", "Gera fatura e título a partir de pedido confirmado"), new("separacao-pedido", "Separação de Pedido", "Cria tarefa operacional de separação"), new("entrega-pod", "Entrega com POD", "Configura evidência de entrega"), new("cobranca-vencido", "Cobrança de Título Vencido", "Cria outbox de cobrança")];
    public bool Match(string? q, params string?[] values) => string.IsNullOrWhiteSpace(q) || values.Any(v => (v ?? "").Contains(q, StringComparison.OrdinalIgnoreCase)); public bool Status(string? s, bool active) => string.IsNullOrWhiteSpace(s) || (active ? "ACTIVE" : "INACTIVE").Equals(s, StringComparison.OrdinalIgnoreCase); public object Page<T>(IEnumerable<T> items, int page, int pageSize) { var list = items.ToList(); return new { page = Math.Max(1, page), pageSize = Math.Clamp(pageSize, 1, 100), total = list.Count, items = list.Skip((Math.Max(1, page) - 1) * Math.Clamp(pageSize, 1, 100)).Take(Math.Clamp(pageSize, 1, 100)) }; } public decimal Balance(Guid productId) => InventoryMovements.Where(m => m.ProductId == productId).Sum(m => m.Quantity); public void Audit(string module, Guid id, string action) => CompletedActions.Add($"audit:{module}:{action}:{id}");
    public object Dashboard() => new { activeCustomers = Customers.Values.Count(x => x.Active), activeProducts = Products.Values.Count(x => x.Active), criticalStock = Products.Values.Count(x => Balance(x.Id) <= x.MinimumStock), draftOrders = Orders.Values.Count(x => x.Status == "DRAFT"), confirmedOrders = Orders.Values.Count(x => x.Status == "CONFIRMED"), pendingTasks = Tasks.Values.Count(x => x.Status != "DONE"), overdueTasks = 0, issuedInvoices = Invoices.Count, openTitles = Titles.Values.Count(x => x.Status == "OPEN"), overdueTitles = Titles.Values.Count(x => x.DueDate < DateTime.UtcNow && x.Status == "OPEN"), fakeBoletos = Titles.Values.Count(x => x.FakeBoleto), pendingOutbox = Outbox.Values.Count(x => x.Status == "PENDING"), errorOutbox = Outbox.Values.Count(x => x.Status == "ERROR"), journeyProgress = Progress(), nextAction = NextAction() };
    public object NextAction() { if (Customers.IsEmpty) return new { code = "CREATE_CUSTOMER", label = "Criar cliente", url = "/customers/create" }; if (Products.IsEmpty) return new { code = "CREATE_PRODUCT", label = "Criar produto", url = "/products/create" }; if (Products.Values.Any(p => Balance(p.Id) <= 0)) return new { code = "REGISTER_STOCK", label = "Registrar estoque", url = "/inventory/entry" }; if (Orders.IsEmpty) return new { code = "CREATE_ORDER", label = "Criar pedido", url = "/orders/create" }; if (Orders.Values.Any(o => o.Status == "DRAFT")) return new { code = "CONFIRM_ORDER", label = "Confirmar pedido", url = "/orders" }; if (Tasks.Values.Any(t => t.Status != "DONE")) return new { code = "COMPLETE_TASK", label = "Concluir tarefa", url = "/tasks/my" }; if (Invoices.IsEmpty) return new { code = "GENERATE_INVOICE", label = "Gerar fatura", url = "/billing/invoices" }; if (Titles.IsEmpty) return new { code = "GENERATE_TITLE", label = "Gerar título", url = "/billing/titles" }; if (Titles.Values.Any(t => !t.FakeBoleto)) return new { code = "GENERATE_FAKE_BOLETO", label = "Gerar boleto fake", url = "/billing/titles" }; if (Outbox.Values.Any(o => o.Status == "PENDING")) return new { code = "PROCESS_OUTBOX", label = "Processar outbox", url = "/connect/outbox" }; return new { code = "FOLLOW_DASHBOARD", label = "Acompanhar dashboard", url = "/dashboard" }; }
    public object Progress() => new { completed = new[] { !Customers.IsEmpty, !Products.IsEmpty, Products.Values.Any(p => Balance(p.Id) > 0), !Orders.IsEmpty, Orders.Values.Any(o => o.Status == "CONFIRMED"), Tasks.Values.Any(t => t.Status == "DONE"), !Invoices.IsEmpty, !Titles.IsEmpty, Titles.Values.Any(t => t.FakeBoleto), Outbox.Values.Any(o => o.Status == "PROCESSED") }.Count(x => x), total = 10 }; public object Recommended() => new[] { NextAction() }; public object Activities() => new[] { "Dashboard", "Atividades", "Demo", "Homologação", "Jornada", "Clientes", "Produtos", "Estoque", "Pedidos", "Minhas tarefas", "Faturamento", "Outbox", "Templates" }.Select(m => new { module = m, status = "FUNCTIONAL", requiredPermission = "homologacao.v112", actionUrl = "/" + m.ToLowerInvariant().Replace(" ", "-") }); public object Demo() => new[] { "customer", "product", "stock", "order", "confirmation", "task", "invoice", "title", "fake-boleto", "outbox", "dashboard", "journey" }.Select(c => new { code = c, status = "READY", nextAction = NextAction() }); public object RunStep(string stepCode) => new { stepCode, status = "OK", nextAction = NextAction() }; public object RunAll() => new { status = "OK", timeline = Demo(), nextAction = NextAction() }; public List<CheckDto> Homologation() => [.. new[] { "database", "scriptcompleto", "api", "web", "worker", "activities", "demo", "dashboard", "journey", "customers", "products", "inventory", "orders", "tasks", "billing", "outbox", "templates" }.Select(c => new CheckDto(c, "READY", "Check v1.12 disponível para validação funcional", null, c == "outbox" ? "/connect/outbox" : "/" + c))];
}
