using Dapper;
using Npgsql;

namespace PlantaoPro.Api.Clinical;

public interface ILongitudinalRepository
{
    Task<PacienteIdentificacaoDto?> PacienteAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<bool> PossuiVinculoAssistencialAsync(Guid tenantId, Guid pacienteId, Guid userId, CancellationToken ct);
    Task<ResumoClinicoDto> ResumoAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<IReadOnlyList<TimelineClinicaDto>> TimelineAsync(Guid tenantId, Guid pacienteId, string? tipo, int page, int pageSize, CancellationToken ct);
    Task<IReadOnlyList<PacienteProblemaDto>> ProblemasAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<PacienteProblemaDto?> CriarProblemaAsync(Guid tenantId, Guid pacienteId, CriarProblemaRequest request, Guid? userId, CancellationToken ct);
    Task<bool> AtualizarProblemaAsync(Guid tenantId, Guid pacienteId, Guid id, AtualizarProblemaRequest request, Guid? userId, CancellationToken ct);
    Task<bool> ResolverProblemaAsync(Guid tenantId, Guid pacienteId, Guid id, ResolverProblemaRequest request, Guid? userId, CancellationToken ct);
    Task<IReadOnlyList<PacienteAlergiaDto>> AlergiasAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<PacienteAlergiaDto?> CriarAlergiaAsync(Guid tenantId, Guid pacienteId, CriarAlergiaRequest request, Guid? userId, CancellationToken ct);
    Task<bool> AtualizarAlergiaAsync(Guid tenantId, Guid pacienteId, Guid id, AtualizarAlergiaRequest request, Guid? userId, CancellationToken ct);
    Task<IReadOnlyList<PacienteMedicamentoDto>> MedicamentosAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<PacienteMedicamentoDto?> CriarMedicamentoAsync(Guid tenantId, Guid pacienteId, CriarMedicamentoUsoRequest request, Guid? userId, CancellationToken ct);
    Task<bool> AtualizarMedicamentoAsync(Guid tenantId, Guid pacienteId, Guid id, AtualizarMedicamentoUsoRequest request, Guid? userId, CancellationToken ct);
    Task<SolicitacaoExameDto?> CriarExamesAsync(Guid tenantId, Guid consultaId, CriarSolicitacaoExamesRequest request, Guid? userId, CancellationToken ct);
    Task<IReadOnlyList<SolicitacaoExameDto>> ExamesAsync(Guid tenantId, Guid? pacienteId, CancellationToken ct);
    Task<SolicitacaoExameDto?> ExameAsync(Guid tenantId, Guid id, CancellationToken ct);
    Task<bool> CancelarExameAsync(Guid tenantId, Guid id, Guid? userId, CancellationToken ct);
    Task<ResultadoExameDto?> ResultadoAsync(Guid tenantId, Guid id, RegistrarResultadoExameRequest request, Guid? userId, CancellationToken ct);
    Task<EncaminhamentoClinicoDto?> CriarEncaminhamentoAsync(Guid tenantId, Guid consultaId, CriarEncaminhamentoClinicoRequest request, Guid? userId, CancellationToken ct);
    Task<IReadOnlyList<EncaminhamentoClinicoDto>> EncaminhamentosAsync(Guid tenantId, Guid pacienteId, CancellationToken ct);
    Task<bool> CancelarEncaminhamentoAsync(Guid tenantId, Guid id, Guid? userId, CancellationToken ct);
    Task<DocumentoClinicoDto?> CriarDocumentoAsync(Guid tenantId, CriarDocumentoClinicoRequest request, Guid? userId, string assinaturaStatus, CancellationToken ct);
    Task<DocumentoClinicoDto?> DocumentoAsync(Guid tenantId, Guid id, CancellationToken ct);
    Task<bool> CancelarDocumentoAsync(Guid tenantId, Guid id, CancelarDocumentoClinicoRequest request, Guid? userId, CancellationToken ct);
}

public sealed class LongitudinalRepository : ILongitudinalRepository
{
    private sealed record ConsultaExameContexto(Guid PacienteId, Guid? MedicoId, Guid? UnidadeId);
    private sealed record SolicitacaoExameItemRow(Guid ItemId, string? Codigo, string Nome, string Tipo, string? Observacao, string Status);
    private readonly string connectionString;
    public LongitudinalRepository(IConfiguration cfg) => connectionString = cfg.GetConnectionString("Default") ?? throw new InvalidOperationException("ConnectionStrings:Default não configurada.");
    private NpgsqlConnection Connection() => new(connectionString);
    private static CommandDefinition Cmd(string sql, object? value, CancellationToken ct, NpgsqlTransaction? tx = null) => new(sql, value, tx, cancellationToken: ct);

    public async Task<bool> PossuiVinculoAssistencialAsync(Guid t, Guid p, Guid userId, CancellationToken ct)
    {
        await using var cn = Connection();
        const string sql = @"
            select exists (
                select 1
                  from plantaopro.consultas c
                  join plantaopro.medicos m on m.id = c.medico_id and m.reg_status = 'A'
                 where c.cliente_id = @t and c.paciente_id = @p and c.reg_status = 'A'
                   and m.usuario_id = @userId
            )
            ";
        return await cn.ExecuteScalarAsync<bool>(Cmd(sql, new { t, p, userId }, ct));
    }

    public async Task<PacienteIdentificacaoDto?> PacienteAsync(Guid t, Guid p, CancellationToken ct)
    { await using var cn=Connection(); return await cn.QuerySingleOrDefaultAsync<PacienteIdentificacaoDto>(Cmd("select p.id,p.nome,p.nome_social NomeSocial,p.data_nascimento DataNascimento,p.sexo_genero SexoGenero,u.nome Unidade,p.telefone,p.email,coalesce(cv.nome,pl.nome) Convenio from plantaopro.pacientes p left join plantaopro.unidades u on u.id=p.unidade_id left join lateral (select pc.convenio_id,pc.plano_saude_id from plantaopro.paciente_convenios pc where pc.paciente_id=p.id and pc.cliente_id=p.cliente_id and pc.reg_status='A' order by pc.principal desc,pc.reg_date desc limit 1) pc on true left join plantaopro.convenios cv on cv.id=pc.convenio_id left join plantaopro.planos_saude pl on pl.id=pc.plano_saude_id where p.id=@p and p.cliente_id=@t and p.reg_status='A'",new{t,p},ct)); }

    public async Task<IReadOnlyList<PacienteProblemaDto>> ProblemasAsync(Guid t, Guid p, CancellationToken ct)
    { await using var cn=Connection(); return (await cn.QueryAsync<PacienteProblemaDto>(Cmd("select x.id,x.cid_id CidId,c.codigo CidCodigo,x.descricao,x.status,x.data_inicio DataInicio,x.data_resolucao DataResolucao,x.observacao,x.origem_consulta_id OrigemConsultaId,x.versao,x.criado_em CriadoEm,x.atualizado_em AtualizadoEm from plantaopro.paciente_problemas x left join plantaopro.cid_tabela c on c.id=x.cid_id where x.tenant_id=@t and x.paciente_id=@p and x.reg_status='A' order by (x.status='ATIVO') desc,x.data_inicio desc",new{t,p},ct))).AsList(); }
    public async Task<IReadOnlyList<PacienteAlergiaDto>> AlergiasAsync(Guid t, Guid p, CancellationToken ct)
    { await using var cn=Connection(); return (await cn.QueryAsync<PacienteAlergiaDto>(Cmd("select id,tipo,substancia,descricao,gravidade,reacao,status,confirmada,origem_consulta_id OrigemConsultaId,versao,registrado_em RegistradoEm from plantaopro.paciente_alergias where tenant_id=@t and paciente_id=@p and reg_status='A' order by (status='ATIVA') desc,registrado_em desc",new{t,p},ct))).AsList(); }
    public async Task<IReadOnlyList<PacienteMedicamentoDto>> MedicamentosAsync(Guid t, Guid p, CancellationToken ct)
    { await using var cn=Connection(); return (await cn.QueryAsync<PacienteMedicamentoDto>(Cmd("select id,medicamento_id MedicamentoId,medicamento_descricao MedicamentoDescricao,dose,frequencia,via,inicio_em InicioEm,fim_em FimEm,status,origem,consulta_id ConsultaId,prescricao_id PrescricaoId,observacao,versao,created_at CriadoEm from plantaopro.paciente_medicamentos_uso where tenant_id=@t and paciente_id=@p and reg_status='A' order by (status='EM_USO') desc,created_at desc",new{t,p},ct))).AsList(); }

    public async Task<ResumoClinicoDto> ResumoAsync(Guid t, Guid p, CancellationToken ct)
    {
        await using var cn=Connection(); await cn.OpenAsync(ct);
        var problemas=await ProblemasAsync(t,p,ct); var alergias=await AlergiasAsync(t,p,ct); var medicamentos=await MedicamentosAsync(t,p,ct); var exames=await ExamesAsync(t,p,ct); var encaminhamentos=await EncaminhamentosAsync(t,p,ct);
        var consultas=(await cn.QueryAsync<ConsultaLongitudinalDto>(Cmd("select c.id,coalesce(c.finalizada_em,c.inicio_em,c.reg_date) Data,c.status,m.nome Profissional,u.nome Unidade from plantaopro.consultas c left join plantaopro.medicos m on m.id=c.medico_id left join plantaopro.unidades u on u.id=c.unidade_id where c.cliente_id=@t and c.paciente_id=@p and c.reg_status='A' order by Data desc limit 10",new{t,p},ct))).AsList();
        var triagens=(await cn.QueryAsync<TriagemLongitudinalDto>(Cmd("select x.id,x.created_at Data,x.classificacao_risco ClassificacaoRisco,u.nome Profissional from plantaopro.triagens x left join plantaopro.usuarios u on u.id=x.enfermeiro_id where x.cliente_id=@t and x.paciente_id=@p and x.reg_status='A' order by x.created_at desc limit 10",new{t,p},ct))).AsList();
        var prescricoes=(await cn.QueryAsync<PrescricaoLongitudinalDto>(Cmd("select x.id,coalesce(x.finalizada_em,x.reg_date) Data,x.status,m.nome Profissional,count(i.id)::int QuantidadeItens from plantaopro.prescricoes x left join plantaopro.medicos m on m.id=x.medico_id left join plantaopro.prescricao_itens i on i.prescricao_id=x.id and i.reg_status='A' where x.cliente_id=@t and x.paciente_id=@p and x.reg_status='A' group by x.id,m.nome order by Data desc limit 10",new{t,p},ct))).AsList();
        var resultados=(await cn.QueryAsync<ResultadoExameDto>(Cmd("select id,solicitacao_id SolicitacaoId,item_id ItemId,paciente_id PacienteId,tipo,resumo,resultado_textual ResultadoTextual,realizado_em RealizadoEm,liberado_em LiberadoEm,profissional_responsavel ProfissionalResponsavel,documento_id DocumentoId,created_at CriadoEm from plantaopro.resultados_exames where tenant_id=@t and paciente_id=@p order by created_at desc limit 10",new{t,p},ct))).AsList();
        var documentos=(await cn.QueryAsync<DocumentoClinicoDto>(Cmd("select id,paciente_id PacienteId,consulta_id ConsultaId,tipo,titulo,conteudo,status,versao,emitido_por EmitidoPor,emitido_em EmitidoEm,motivo_cancelamento MotivoCancelamento,hash_documento HashDocumento,assinatura_status AssinaturaStatus,created_at CriadoEm,updated_at AtualizadoEm from plantaopro.documentos_clinicos where tenant_id=@t and paciente_id=@p order by created_at desc limit 10",new{t,p},ct))).AsList();
        var alertas=alergias.Where(x=>x.Status=="ATIVA").Select(x=>new AlertaClinicoDto("ALERGIA",$"Alergia a {x.Substancia}",x.Gravidade)).Concat(problemas.Where(x=>x.Status=="ATIVO").Select(x=>new AlertaClinicoDto("PROBLEMA",x.Descricao,"ATENCAO"))).ToList();
        return new(problemas.Where(x=>x.Status=="ATIVO").ToList(),alergias.Where(x=>x.Status=="ATIVA").ToList(),medicamentos.Where(x=>x.Status=="EM_USO").ToList(),consultas,triagens,prescricoes,exames.Where(x=>x.Status is not ("RESULTADO_DISPONIVEL" or "CANCELADO")).ToList(),resultados,encaminhamentos.Where(x=>x.Status is not ("CONCLUIDO" or "CANCELADO")).ToList(),documentos,alertas);
    }

    public async Task<IReadOnlyList<TimelineClinicaDto>> TimelineAsync(Guid t, Guid p, string? tipo, int page, int pageSize, CancellationToken ct)
    { await using var cn=Connection(); const string sql=@"select id,'CONSULTA' Tipo,coalesce(finalizada_em,inicio_em,reg_date) Data,null::text Profissional,null::text Unidade,'Consulta' Titulo,case when status='FINALIZADA' then 'Atendimento finalizado' else 'Atendimento clínico' end ResumoSeguro,id EntidadeId,'CONSULTA' EntidadeTipo,true PermiteDetalhes from plantaopro.consultas where cliente_id=@t and paciente_id=@p and reg_status='A'
union all select id,'TRIAGEM',created_at,null,null,'Triagem','Classificação de risco registrada',id,'TRIAGEM',true from plantaopro.triagens where cliente_id=@t and paciente_id=@p and reg_status='A'
union all select id,'ALERGIA',registrado_em,null,null,'Alergia registrada',substancia,id,'ALERGIA',true from plantaopro.paciente_alergias where tenant_id=@t and paciente_id=@p and reg_status='A'
union all select id,'MEDICAMENTO',created_at,null,null,'Medicamento em uso',medicamento_descricao,id,'MEDICAMENTO',true from plantaopro.paciente_medicamentos_uso where tenant_id=@t and paciente_id=@p and reg_status='A'
union all select id,'EXAME_SOLICITADO',solicitado_em,null,null,'Exames solicitados','Solicitação clínica de exames',id,'EXAME',true from plantaopro.solicitacoes_exames where tenant_id=@t and paciente_id=@p
union all select id,'EXAME_RESULTADO',created_at,null,null,'Resultado disponível',resumo,id,'RESULTADO_EXAME',true from plantaopro.resultados_exames where tenant_id=@t and paciente_id=@p
union all select id,'ENCAMINHAMENTO',criado_em,null,null,'Encaminhamento',motivo,id,'ENCAMINHAMENTO',true from plantaopro.encaminhamentos_clinicos where tenant_id=@t and paciente_id=@p
union all select id,case when tipo='ATESTADO' then 'ATESTADO' else 'DOCUMENTO' end,created_at,null,null,titulo,case when status='CANCELADO' then 'Documento cancelado' else 'Documento clínico emitido' end,id,'DOCUMENTO',true from plantaopro.documentos_clinicos where tenant_id=@t and paciente_id=@p) select * from eventos where (@tipo is null or Tipo=@tipo) order by Data desc limit @pageSize offset @offset"; page=Math.Max(1,page); pageSize=Math.Clamp(pageSize,1,100); var offset=(page-1)*pageSize; tipo=string.IsNullOrWhiteSpace(tipo)?null:tipo.Trim().ToUpperInvariant(); return (await cn.QueryAsync<TimelineClinicaDto>(Cmd("with eventos as ("+sql,new{t,p,tipo,pageSize,offset},ct))).AsList(); }

    public async Task<PacienteProblemaDto?> CriarProblemaAsync(Guid t,Guid p,CriarProblemaRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();var id=Guid.NewGuid();await cn.ExecuteAsync(Cmd("insert into plantaopro.paciente_problemas(id,tenant_id,cliente_id,paciente_id,cid_id,descricao,status,data_inicio,observacao,origem_consulta_id,criado_por) values(@id,@t,@t,@p,@CidId,@Descricao,'ATIVO',coalesce(@DataInicio,current_date),@Observacao,@OrigemConsultaId,@u)",new{id,t,p,u,r.CidId,r.Descricao,r.DataInicio,r.Observacao,r.OrigemConsultaId},ct));return (await ProblemasAsync(t,p,ct)).Single(x=>x.Id==id);}
    public async Task<bool> AtualizarProblemaAsync(Guid t,Guid p,Guid id,AtualizarProblemaRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.paciente_problemas set descricao=@Descricao,status=@Status,data_inicio=@DataInicio,data_resolucao=@DataResolucao,observacao=@Observacao,versao=versao+1,atualizado_por=@u,atualizado_em=now() where id=@id and tenant_id=@t and paciente_id=@p and versao=@Versao and reg_status='A'",new{t,p,id,u,r.Descricao,r.Status,r.DataInicio,r.DataResolucao,r.Observacao,r.Versao},ct))==1;}
    public async Task<bool> ResolverProblemaAsync(Guid t,Guid p,Guid id,ResolverProblemaRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.paciente_problemas set status='RESOLVIDO',data_resolucao=coalesce(@DataResolucao,current_date),observacao=coalesce(@Observacao,observacao),versao=versao+1,atualizado_por=@u,atualizado_em=now() where id=@id and tenant_id=@t and paciente_id=@p and versao=@Versao and status='ATIVO' and reg_status='A'",new{t,p,id,u,r.DataResolucao,r.Observacao,r.Versao},ct))==1;}
    public async Task<PacienteAlergiaDto?> CriarAlergiaAsync(Guid t,Guid p,CriarAlergiaRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();var id=Guid.NewGuid();await cn.ExecuteAsync(Cmd("insert into plantaopro.paciente_alergias(id,tenant_id,paciente_id,tipo,substancia,descricao,gravidade,reacao,status,confirmada,origem_consulta_id,registrado_por) values(@id,@t,@p,@Tipo,@Substancia,@Descricao,@Gravidade,@Reacao,'ATIVA',@Confirmada,@OrigemConsultaId,@u)",new{id,t,p,u,r.Tipo,r.Substancia,r.Descricao,r.Gravidade,r.Reacao,r.Confirmada,r.OrigemConsultaId},ct));return (await AlergiasAsync(t,p,ct)).Single(x=>x.Id==id);}
    public async Task<bool> AtualizarAlergiaAsync(Guid t,Guid p,Guid id,AtualizarAlergiaRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.paciente_alergias set tipo=@Tipo,substancia=@Substancia,descricao=@Descricao,gravidade=@Gravidade,reacao=@Reacao,status=@Status,confirmada=@Confirmada,versao=versao+1,atualizado_por=@u,atualizado_em=now() where id=@id and tenant_id=@t and paciente_id=@p and versao=@Versao and reg_status='A'",new{t,p,id,u,r.Tipo,r.Substancia,r.Descricao,r.Gravidade,r.Reacao,r.Status,r.Confirmada,r.Versao},ct))==1;}
    public async Task<PacienteMedicamentoDto?> CriarMedicamentoAsync(Guid t,Guid p,CriarMedicamentoUsoRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();var id=Guid.NewGuid();await cn.ExecuteAsync(Cmd("insert into plantaopro.paciente_medicamentos_uso(id,tenant_id,paciente_id,medicamento_id,medicamento_descricao,dose,frequencia,via,inicio_em,status,origem,consulta_id,prescricao_id,observacao,created_by) values(@id,@t,@p,@MedicamentoId,@MedicamentoDescricao,@Dose,@Frequencia,@Via,@InicioEm,'EM_USO',@Origem,@ConsultaId,@PrescricaoId,@Observacao,@u)",new{id,t,p,u,r.MedicamentoId,r.MedicamentoDescricao,r.Dose,r.Frequencia,r.Via,r.InicioEm,r.Origem,r.ConsultaId,r.PrescricaoId,r.Observacao},ct));return (await MedicamentosAsync(t,p,ct)).Single(x=>x.Id==id);}
    public async Task<bool> AtualizarMedicamentoAsync(Guid t,Guid p,Guid id,AtualizarMedicamentoUsoRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.paciente_medicamentos_uso set medicamento_descricao=@MedicamentoDescricao,dose=@Dose,frequencia=@Frequencia,via=@Via,inicio_em=@InicioEm,fim_em=@FimEm,status=@Status,observacao=@Observacao,versao=versao+1,updated_by=@u,updated_at=now() where id=@id and tenant_id=@t and paciente_id=@p and versao=@Versao and reg_status='A'",new{t,p,id,u,r.MedicamentoDescricao,r.Dose,r.Frequencia,r.Via,r.InicioEm,r.FimEm,r.Status,r.Observacao,r.Versao},ct))==1;}

    public async Task<SolicitacaoExameDto?> CriarExamesAsync(Guid t,Guid consultaId,CriarSolicitacaoExamesRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);var contexto=await cn.QuerySingleOrDefaultAsync<ConsultaExameContexto>(Cmd("select paciente_id PacienteId,medico_id MedicoId,unidade_id UnidadeId from plantaopro.consultas where id=@consultaId and cliente_id=@t and reg_status='A'",new{consultaId,t},ct,tx));if(contexto is null || contexto.PacienteId==Guid.Empty)return null;var id=Guid.NewGuid();await cn.ExecuteAsync(Cmd("insert into plantaopro.solicitacoes_exames(id,tenant_id,paciente_id,consulta_id,medico_id,unidade_id,status,prioridade,indicacao_clinica,observacoes,created_by) values(@id,@t,@PacienteId,@consultaId,@MedicoId,@UnidadeId,'SOLICITADO',@Prioridade,@IndicacaoClinica,@Observacoes,@u)",new{id,t,consultaId,u,contexto.PacienteId,contexto.MedicoId,contexto.UnidadeId,r.Prioridade,r.IndicacaoClinica,r.Observacoes},ct,tx));foreach(var item in r.Itens)await cn.ExecuteAsync(Cmd("insert into plantaopro.solicitacao_exame_itens(solicitacao_id,codigo,nome,tipo,observacao,status) values(@id,@Codigo,@Nome,@Tipo,@Observacao,'SOLICITADO')",new{id,item.Codigo,item.Nome,item.Tipo,item.Observacao},ct,tx));await tx.CommitAsync(ct);return await ExameAsync(t,id,ct);}
    private const string ExameSelect = "select s.id,s.paciente_id PacienteId,s.consulta_id ConsultaId,s.medico_id MedicoId,s.unidade_id UnidadeId,s.status,s.prioridade,s.indicacao_clinica IndicacaoClinica,s.observacoes,s.solicitado_em SolicitadoEm,s.realizado_em RealizadoEm,i.id ItemId,i.codigo,i.nome,i.tipo,i.observacao,i.status from plantaopro.solicitacoes_exames s left join plantaopro.solicitacao_exame_itens i on i.solicitacao_id=s.id";
    private static async Task<IReadOnlyList<SolicitacaoExameDto>> MapearExamesAsync(NpgsqlConnection cn, CommandDefinition command){var lookup=new Dictionary<Guid,SolicitacaoExameDto>();await cn.QueryAsync<SolicitacaoExameDto,SolicitacaoExameItemRow,SolicitacaoExameDto>(command,(s,i)=>{if(!lookup.TryGetValue(s.Id,out var found)){found=s;found.Itens=new List<SolicitacaoExameItemDto>();lookup.Add(s.Id,found);}if(i is not null&&i.ItemId!=Guid.Empty)((List<SolicitacaoExameItemDto>)found.Itens).Add(new(i.ItemId,i.Codigo,i.Nome,i.Tipo,i.Observacao,i.Status));return found;},splitOn:"ItemId");return lookup.Values.ToList();}
    public async Task<IReadOnlyList<SolicitacaoExameDto>> ExamesAsync(Guid t,Guid? p,CancellationToken ct){await using var cn=Connection();return await MapearExamesAsync(cn,Cmd(ExameSelect+" where s.tenant_id=@t and (@p is null or s.paciente_id=@p) order by s.solicitado_em desc limit 100",new{t,p},ct));}
    public async Task<SolicitacaoExameDto?> ExameAsync(Guid t,Guid id,CancellationToken ct){await using var cn=Connection();return (await MapearExamesAsync(cn,Cmd(ExameSelect+" where s.tenant_id=@t and s.id=@id",new{t,id},ct))).SingleOrDefault();}
    public async Task<bool> CancelarExameAsync(Guid t,Guid id,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.solicitacoes_exames set status='CANCELADO',cancelado_em=now(),updated_by=@u,updated_at=now() where id=@id and tenant_id=@t and status not in ('REALIZADO','RESULTADO_DISPONIVEL','CANCELADO')",new{t,id,u},ct))==1;}
    public async Task<ResultadoExameDto?> ResultadoAsync(Guid t,Guid id,RegistrarResultadoExameRequest r,Guid? u,CancellationToken ct)
    {
        await using var cn=Connection(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(ct);
        const string sql="insert into plantaopro.resultados_exames(id,tenant_id,solicitacao_id,item_id,paciente_id,tipo,resumo,resultado_textual,realizado_em,liberado_em,profissional_responsavel,documento_id,created_by) select gen_random_uuid(),s.tenant_id,s.id,@ItemId,s.paciente_id,@Tipo,@Resumo,@ResultadoTextual,@RealizadoEm,@LiberadoEm,@ProfissionalResponsavel,@DocumentoId,@u from plantaopro.solicitacoes_exames s where s.id=@id and s.tenant_id=@t and s.status<>'CANCELADO' and (@ItemId is null or exists(select 1 from plantaopro.solicitacao_exame_itens i where i.id=@ItemId and i.solicitacao_id=s.id)) and not exists(select 1 from plantaopro.resultados_exames r where r.tenant_id=@t and r.solicitacao_id=@id and r.item_id is not distinct from @ItemId) returning id,solicitacao_id SolicitacaoId,item_id ItemId,paciente_id PacienteId,tipo,resumo,resultado_textual ResultadoTextual,realizado_em RealizadoEm,liberado_em LiberadoEm,profissional_responsavel ProfissionalResponsavel,documento_id DocumentoId,created_at CriadoEm";
        var args=new{t,id,u,r.ItemId,r.Tipo,r.Resumo,r.ResultadoTextual,r.RealizadoEm,r.LiberadoEm,r.ProfissionalResponsavel,r.DocumentoId};
        var result=await cn.QuerySingleOrDefaultAsync<ResultadoExameDto>(Cmd(sql,args,ct,tx)); if(result is null){await tx.RollbackAsync(ct);return null;}
        if(r.ItemId is not null) await cn.ExecuteAsync(Cmd("update plantaopro.solicitacao_exame_itens set status='RESULTADO_DISPONIVEL' where id=@ItemId and solicitacao_id=@id",new{id,r.ItemId},ct,tx));
        await cn.ExecuteAsync(Cmd("update plantaopro.solicitacoes_exames s set status=case when exists(select 1 from plantaopro.solicitacao_exame_itens i where i.solicitacao_id=s.id and i.status not in ('RESULTADO_DISPONIVEL','CANCELADO')) then 'PARCIALMENTE_RESULTADO' else 'RESULTADO_DISPONIVEL' end,realizado_em=@RealizadoEm,updated_at=now(),updated_by=@u where s.id=@id and s.tenant_id=@t",new{t,id,u,r.RealizadoEm},ct,tx));
        await tx.CommitAsync(ct); return result;
    }

    public async Task<EncaminhamentoClinicoDto?> CriarEncaminhamentoAsync(Guid t,Guid consultaId,CriarEncaminhamentoClinicoRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();const string sql="insert into plantaopro.encaminhamentos_clinicos(id,tenant_id,paciente_id,consulta_id,medico_origem_id,especialidade_destino_id,profissional_destino_id,unidade_destino_id,motivo,resumo_clinico,prioridade,status,created_by) select gen_random_uuid(),c.cliente_id,c.paciente_id,c.id,c.medico_id,@EspecialidadeDestinoId,@ProfissionalDestinoId,@UnidadeDestinoId,@Motivo,@ResumoClinico,@Prioridade,'AGUARDANDO_AGENDAMENTO',@u from plantaopro.consultas c where c.id=@consultaId and c.cliente_id=@t returning id,paciente_id PacienteId,consulta_id ConsultaId,especialidade_destino_id EspecialidadeDestinoId,profissional_destino_id ProfissionalDestinoId,unidade_destino_id UnidadeDestinoId,motivo,resumo_clinico ResumoClinico,prioridade,status,criado_em CriadoEm,agendado_em AgendadoEm,concluido_em ConcluidoEm";return await cn.QuerySingleOrDefaultAsync<EncaminhamentoClinicoDto>(Cmd(sql,new{t,consultaId,u,r.EspecialidadeDestinoId,r.ProfissionalDestinoId,r.UnidadeDestinoId,r.Motivo,r.ResumoClinico,r.Prioridade},ct));}
    public async Task<IReadOnlyList<EncaminhamentoClinicoDto>> EncaminhamentosAsync(Guid t,Guid p,CancellationToken ct){await using var cn=Connection();return(await cn.QueryAsync<EncaminhamentoClinicoDto>(Cmd("select id,paciente_id PacienteId,consulta_id ConsultaId,especialidade_destino_id EspecialidadeDestinoId,profissional_destino_id ProfissionalDestinoId,unidade_destino_id UnidadeDestinoId,motivo,resumo_clinico ResumoClinico,prioridade,status,criado_em CriadoEm,agendado_em AgendadoEm,concluido_em ConcluidoEm from plantaopro.encaminhamentos_clinicos where tenant_id=@t and paciente_id=@p order by criado_em desc",new{t,p},ct))).AsList();}
    public async Task<bool> CancelarEncaminhamentoAsync(Guid t,Guid id,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.encaminhamentos_clinicos set status='CANCELADO',updated_by=@u,updated_at=now() where id=@id and tenant_id=@t and status not in ('CONCLUIDO','CANCELADO')",new{t,id,u},ct))==1;}
    public async Task<DocumentoClinicoDto?> CriarDocumentoAsync(Guid t,CriarDocumentoClinicoRequest r,Guid? u,string assinatura,CancellationToken ct){await using var cn=Connection();const string sql="insert into plantaopro.documentos_clinicos(id,tenant_id,paciente_id,consulta_id,tipo,titulo,conteudo,status,versao,emitido_por,emitido_em,hash_documento,assinatura_status,created_by,cid_exibido,quantidade_dias,inicio_afastamento) select gen_random_uuid(),@t,@PacienteId,@ConsultaId,@Tipo,@Titulo,@Conteudo,'EMITIDO',1,@u,now(),encode(digest(convert_to(@Conteudo,'UTF8'),'sha256'),'hex'),@assinatura,@u,@IncluirCid,@QuantidadeDias,@InicioAfastamento where exists(select 1 from plantaopro.pacientes where id=@PacienteId and cliente_id=@t and reg_status='A') and (@ConsultaId is null or exists(select 1 from plantaopro.consultas where id=@ConsultaId and cliente_id=@t and paciente_id=@PacienteId and reg_status='A')) returning id,paciente_id PacienteId,consulta_id ConsultaId,tipo,titulo,conteudo,status,versao,emitido_por EmitidoPor,emitido_em EmitidoEm,motivo_cancelamento MotivoCancelamento,hash_documento HashDocumento,assinatura_status AssinaturaStatus,created_at CriadoEm,updated_at AtualizadoEm";return await cn.QuerySingleOrDefaultAsync<DocumentoClinicoDto>(Cmd(sql,new{t,u,assinatura,r.PacienteId,r.ConsultaId,r.Tipo,r.Titulo,r.Conteudo,r.IncluirCid,r.QuantidadeDias,r.InicioAfastamento},ct));}
    public async Task<DocumentoClinicoDto?> DocumentoAsync(Guid t,Guid id,CancellationToken ct){await using var cn=Connection();return await cn.QuerySingleOrDefaultAsync<DocumentoClinicoDto>(Cmd("select id,paciente_id PacienteId,consulta_id ConsultaId,tipo,titulo,conteudo,status,versao,emitido_por EmitidoPor,emitido_em EmitidoEm,motivo_cancelamento MotivoCancelamento,hash_documento HashDocumento,assinatura_status AssinaturaStatus,created_at CriadoEm,updated_at AtualizadoEm from plantaopro.documentos_clinicos where tenant_id=@t and id=@id",new{t,id},ct));}
    public async Task<bool> CancelarDocumentoAsync(Guid t,Guid id,CancelarDocumentoClinicoRequest r,Guid? u,CancellationToken ct){await using var cn=Connection();return await cn.ExecuteAsync(Cmd("update plantaopro.documentos_clinicos set status='CANCELADO',cancelado_por=@u,cancelado_em=now(),motivo_cancelamento=@Motivo,assinatura_status='CANCELADO',versao=versao+1,updated_at=now() where id=@id and tenant_id=@t and versao=@Versao and status<>'CANCELADO'",new{t,id,u,r.Motivo,r.Versao},ct))==1;}
}
