using System.Security.Claims;
using Dapper;
using Npgsql;
using PlantaoPro.Api.Controllers;
namespace PlantaoPro.Api;
public sealed class ImpersonationRepository : IImpersonationRepository
{
    private readonly IConfiguration _cfg; private readonly ImpersonationTokenService _tokens; public ImpersonationRepository(IConfiguration cfg, ImpersonationTokenService tokens){_cfg=cfg;_tokens=tokens;} private NpgsqlConnection Cn()=>new(_cfg.GetConnectionString("Default")); static Guid UserId(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("uid")??u.FindFirstValue(ClaimTypes.NameIdentifier)??Guid.Empty.ToString());
    public async Task<ImpersonationSessionDto> IniciarAsync(ClaimsPrincipal user, IniciarImpersonacaoRequest r, CancellationToken ct=default){if(user.FindFirstValue("impersonation")=="true") throw new InvalidOperationException("Impersonação encadeada bloqueada."); var original=UserId(user); var exp=_tokens.ExpiresAt(r.DuracaoMinutos); await using var cn=Cn(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(ct); var cliente=await cn.ExecuteScalarAsync<Guid?>("select cliente_id from plantaopro.tenants where id=@TenantId", r, tx); var targetGlobal=await cn.ExecuteScalarAsync<bool>("select exists(select 1 from plantaopro.usuarios_perfis up join plantaopro.perfis p on p.id=up.perfil_id where up.usuario_id=@UsuarioAlvoId and upper(p.nome) like '%ADMINISTRADOR GLOBAL%')", r, tx); if(targetGlobal) throw new InvalidOperationException("Não é permitido impersonar Administrador Global."); var session=Guid.NewGuid(); await cn.ExecuteAsync("insert into plantaopro.impersonacao_sessoes(id,usuario_origem_id,usuario_alvo_id,tenant_id,cliente_id,motivo,ticket_referencia,expira_em,status,reg_date,reg_status) values(@session,@original,@UsuarioAlvoId,@TenantId,@cliente,@Motivo,@TicketReferencia,@exp,'ATIVA',now(),'A')", new{session,original,r.UsuarioAlvoId,r.TenantId,cliente,r.Motivo,r.TicketReferencia,exp}, tx); await cn.ExecuteAsync("insert into plantaopro.impersonacao_eventos(id,impersonacao_sessao_id,usuario_origem_id,usuario_alvo_id,evento,detalhes,reg_date,reg_status) values(gen_random_uuid(),@session,@original,@UsuarioAlvoId,'INICIO',jsonb_build_object('ticket',@TicketReferencia),now(),'A')", new{session,original,r.UsuarioAlvoId,r.TicketReferencia}, tx); await tx.CommitAsync(ct); return new(session,original,r.UsuarioAlvoId,r.TenantId,cliente,exp,"ATIVA",_tokens.Emitir(user,original,r.UsuarioAlvoId,session,r.TenantId,cliente,exp));}
    public async Task<object> EncerrarAsync(ClaimsPrincipal user, EncerrarImpersonacaoRequest r, CancellationToken ct=default){var sid=r.ImpersonacaoSessaoId??Guid.Parse(user.FindFirstValue("impersonation_session_id")??Guid.Empty.ToString()); await using var cn=Cn(); await cn.ExecuteAsync("update plantaopro.impersonacao_sessoes set status='ENCERRADA', encerrada_em=now(), reg_status='E' where id=@sid; insert into plantaopro.impersonacao_eventos(id,impersonacao_sessao_id,usuario_origem_id,usuario_alvo_id,evento,detalhes,reg_date,reg_status) select gen_random_uuid(),id,usuario_origem_id,usuario_alvo_id,'ENCERRAMENTO','{}'::jsonb,now(),'A' from plantaopro.impersonacao_sessoes where id=@sid", new{sid}); return new { impersonacaoSessaoId=sid, status="ENCERRADA", encerradaEm=DateTime.UtcNow};}
    public async Task<IReadOnlyCollection<object>> HistoricoAsync(ClaimsPrincipal user, CancellationToken ct=default){await using var cn=Cn(); var rows=await cn.QueryAsync<object>("select id, usuario_origem_id, usuario_alvo_id, tenant_id, status, reg_date from plantaopro.impersonacao_sessoes where usuario_origem_id=@uid order by reg_date desc limit 20", new{uid=UserId(user)}); return rows.ToArray();}
}
