using Dapper;
using Npgsql;
using PlantaoPro.Api.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.IdentityModel.Tokens;

namespace PlantaoPro.Api.Data;
public interface IAuditService { Task LogAsync(Guid? userId,string acao,string entidade,Guid? registroId,string descricao,string? valorAnterior=null,string? valorNovo=null,string? ip=null,string? userAgent=null); }
public sealed class AuditService(IConfiguration cfg):IAuditService{
    public async Task LogAsync(Guid? userId,string acao,string entidade,Guid? registroId,string descricao,string? valorAnterior=null,string? valorNovo=null,string? ip=null,string? userAgent=null){
        await using var cn = new NpgsqlConnection(cfg.GetConnectionString("Default"));
        await cn.ExecuteAsync("insert into plantaopro.auditoria(id,usuario_id,acao,entidade,registro_id,ip,descricao,valor_anterior,valor_novo,user_agent,reg_date,reg_status) values (gen_random_uuid(),@u,@a,@e,@r,@ip,@d,@va,@vn,@ua,now(),'A')",
            new{u=userId,a=acao,e=entidade,r=registroId,ip,d=descricao,va=valorAnterior,vn=valorNovo,ua=userAgent});
    }
}
public sealed class AuthService(IConfiguration cfg,IAuditService audit,ILogger<AuthService> logger){
    public async Task<ApiResponse<LoginResponse>> LoginAsync(LoginRequest req,string? ip,string? ua){
        await using var cn = new NpgsqlConnection(cfg.GetConnectionString("Default"));
        var user = await cn.QueryFirstOrDefaultAsync("select id,nome,email,senha_hash,reg_status from plantaopro.usuarios where email=@email",new{email=req.Email});
        if(user is null || (string)user.reg_status!="A" || !BCrypt.Net.BCrypt.Verify(req.Senha,(string)user.senha_hash)){
            logger.LogWarning("Login inválido para {Email}", req.Email);
            await audit.LogAsync(null,"LOGIN_FALHA","usuarios",null,$"Falha login: {req.Email}",ip:ip,userAgent:ua);
            return ApiResponse<LoginResponse>.Fail("Credenciais inválidas.",401);
        }
        var roles=(await cn.QueryAsync<string>("select p.nome from plantaopro.perfis p join plantaopro.usuarios_perfis up on up.perfil_id=p.id where up.usuario_id=@id and up.reg_status='A'",new{id=(Guid)user.id})).ToArray();
        var token = GenerateToken((Guid)user.id,(string)user.email,roles);
        logger.LogInformation("Login realizado para {Email}", req.Email);
        await audit.LogAsync((Guid)user.id,"LOGIN","usuarios",(Guid)user.id,"Login realizado",ip:ip,userAgent:ua);
        return ApiResponse<LoginResponse>.Ok(new LoginResponse(token,DateTime.UtcNow.AddHours(8),(Guid)user.id,(string)user.nome,roles),"Login realizado com sucesso.");
    }
    string GenerateToken(Guid uid,string email,string[] roles){var jwt=cfg.GetSection("Jwt"); var claims=new List<Claim>{new(JwtRegisteredClaimNames.Sub,uid.ToString()),new(ClaimTypes.Name,email),new("uid",uid.ToString())}; claims.AddRange(roles.Select(r=>new Claim(ClaimTypes.Role,r))); var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwt["Key"]!)); var creds=new SigningCredentials(key,SecurityAlgorithms.HmacSha256); var tk=new JwtSecurityToken(jwt["Issuer"],jwt["Audience"],claims,expires:DateTime.UtcNow.AddHours(8),signingCredentials:creds); return new JwtSecurityTokenHandler().WriteToken(tk);} }
public sealed class MedicoService(IConfiguration cfg,IAuditService audit,ILogger<MedicoService> logger){
  public async Task<ApiResponse<IEnumerable<MedicoDto>>> ListarAsync(){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default")); var data=await cn.QueryAsync<MedicoDto>("select id,nome,cpf,crm,uf_crm as UfCrm,email,telefone,cidade,estado,especialidade_id as EspecialidadeId,reg_status from plantaopro.medicos where reg_status='A' order by nome"); return ApiResponse<IEnumerable<MedicoDto>>.Ok(data,"Médicos carregados.");}
  public async Task<ApiResponse<MedicoDto>> CriarAsync(CreateMedicoRequest req,Guid userId,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default")); await cn.OpenAsync(); await using var tx=await cn.BeginTransactionAsync();
    var exists=await cn.ExecuteScalarAsync<int>("select count(1) from plantaopro.medicos where cpf=@cpf or (crm=@crm and uf_crm=@uf)",new{cpf=req.Cpf,crm=req.Crm,uf=req.UfCrm},tx);
    if(exists>0) return ApiResponse<MedicoDto>.Fail("CPF ou CRM já cadastrado.");
    var id=Guid.NewGuid();
    await cn.ExecuteAsync("insert into plantaopro.medicos(id,nome,cpf,crm,uf_crm,email,telefone,cidade,estado,especialidade_id,reg_date,reg_status,created_by) values(@id,@n,@cpf,@crm,@uf,@e,@t,@c,@es,@esp,now(),'A',@u)",new{id,n=req.Nome,cpf=req.Cpf,crm=req.Crm,uf=req.UfCrm,e=req.Email,t=req.Telefone,c=req.Cidade,es=req.Estado,esp=req.EspecialidadeId,u=userId},tx);
    await cn.ExecuteAsync("insert into plantaopro.auditoria(id,usuario_id,acao,entidade,registro_id,descricao,ip,user_agent,reg_date,reg_status) values(gen_random_uuid(),@u,'CREATE','medicos',@id,'Criação médico',@ip,@ua,now(),'A')",new{u=userId,id,ip,ua},tx);
    await tx.CommitAsync(); logger.LogInformation("Médico criado {MedicoId}",id);
    return ApiResponse<MedicoDto>.Ok(new MedicoDto(id,req.Nome,req.Cpf,req.Crm,req.UfCrm,req.Email,req.Telefone,req.Cidade,req.Estado,req.EspecialidadeId,'A'),"Médico cadastrado com sucesso.");
  }
}
public sealed class HospitalService(IConfiguration cfg,IAuditService audit,ILogger<HospitalService> logger){
 public async Task<ApiResponse<IEnumerable<HospitalDto>>> GetAllAsync(){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var d=await cn.QueryAsync<HospitalDto>("select id,razao_social as RazaoSocial,nome_fantasia as NomeFantasia,cnpj,telefone,email,endereco,cidade,estado,responsavel,reg_status from plantaopro.hospitais where reg_status='A' order by nome_fantasia");return ApiResponse<IEnumerable<HospitalDto>>.Ok(d,"Hospitais carregados.");}
 public async Task<ApiResponse<HospitalDto>> GetByIdAsync(Guid id){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var d=await cn.QueryFirstOrDefaultAsync<HospitalDto>("select id,razao_social as RazaoSocial,nome_fantasia as NomeFantasia,cnpj,telefone,email,endereco,cidade,estado,responsavel,reg_status from plantaopro.hospitais where id=@id",new{id});return d is null?ApiResponse<HospitalDto>.Fail("Registro não encontrado.",404):ApiResponse<HospitalDto>.Ok(d);}
 public async Task<ApiResponse<HospitalDto>> CreateAsync(CreateHospitalRequest r,Guid u,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var ex=await cn.ExecuteScalarAsync<int>("select count(1) from plantaopro.hospitais where cnpj=@c",new{c=r.Cnpj});if(ex>0)return ApiResponse<HospitalDto>.Fail("CNPJ já cadastrado.");var id=Guid.NewGuid();await cn.ExecuteAsync("insert into plantaopro.hospitais(id,razao_social,nome_fantasia,cnpj,telefone,email,endereco,cidade,estado,responsavel,reg_date,reg_status,created_by) values(@id,@rs,@nf,@cnpj,@t,@e,@en,@c,@es,@r,now(),'A',@u)",new{id,rs=r.RazaoSocial,nf=r.NomeFantasia,cnpj=r.Cnpj,t=r.Telefone,e=r.Email,en=r.Endereco,c=r.Cidade,es=r.Estado,r=r.Responsavel,u});await audit.LogAsync(u,"CREATE","hospitais",id,"Criação hospital",ip:ip,userAgent:ua);logger.LogInformation("Hospital criado {id}",id);return await GetByIdAsync(id);} 
 public async Task<ApiResponse<string>> UpdateAsync(Guid id,UpdateHospitalRequest r,Guid u,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var n=await cn.ExecuteAsync("update plantaopro.hospitais set razao_social=@rs,nome_fantasia=@nf,telefone=@t,email=@e,endereco=@en,cidade=@c,estado=@es,responsavel=@r,reg_status=@st,reg_update=now(),updated_by=@u where id=@id",new{id,rs=r.RazaoSocial,nf=r.NomeFantasia,t=r.Telefone,e=r.Email,en=r.Endereco,c=r.Cidade,es=r.Estado,r=r.Responsavel,st=r.RegStatus,u});if(n==0)return ApiResponse<string>.Fail("Registro não encontrado.",404);await audit.LogAsync(u,"UPDATE","hospitais",id,"Atualização hospital",ip:ip,userAgent:ua);return ApiResponse<string>.Ok("ok","Hospital atualizado com sucesso.");}
 public async Task<ApiResponse<string>> DeleteAsync(Guid id,Guid u,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var n=await cn.ExecuteAsync("update plantaopro.hospitais set reg_status='I',reg_update=now(),updated_by=@u where id=@id",new{id,u});if(n==0)return ApiResponse<string>.Fail("Registro não encontrado.",404);await audit.LogAsync(u,"DELETE","hospitais",id,"Inativação hospital",ip:ip,userAgent:ua);return ApiResponse<string>.Ok("ok","Hospital inativado com sucesso.");}
}
public sealed class EspecialidadeService(IConfiguration cfg,IAuditService audit){
 public async Task<ApiResponse<IEnumerable<EspecialidadeDto>>> GetAllAsync(){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var d=await cn.QueryAsync<EspecialidadeDto>("select id,nome,descricao,reg_status from plantaopro.especialidades order by nome");return ApiResponse<IEnumerable<EspecialidadeDto>>.Ok(d);} 
 public async Task<ApiResponse<EspecialidadeDto>> CreateAsync(CreateEspecialidadeRequest r,Guid u,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));if(await cn.ExecuteScalarAsync<int>("select count(1) from plantaopro.especialidades where lower(nome)=lower(@n)",new{n=r.Nome})>0)return ApiResponse<EspecialidadeDto>.Fail("Especialidade já existe.");var id=Guid.NewGuid();await cn.ExecuteAsync("insert into plantaopro.especialidades(id,nome,descricao,reg_date,reg_status,created_by) values(@id,@n,@d,now(),'A',@u)",new{id,n=r.Nome,d=r.Descricao,u});await audit.LogAsync(u,"CREATE","especialidades",id,"Criação especialidade",ip:ip,userAgent:ua);return ApiResponse<EspecialidadeDto>.Ok(new EspecialidadeDto(id,r.Nome,r.Descricao,'A'),"Especialidade criada com sucesso.");}
}
public sealed class PlantaoService(IConfiguration cfg,IAuditService audit){
 public async Task<ApiResponse<IEnumerable<PlantaoDto>>> GetAllAsync(){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var d=await cn.QueryAsync<PlantaoDto>("select id,hospital_id as HospitalId,especialidade_id as EspecialidadeId,data_inicio as DataInicio,data_fim as DataFim,valor,vagas,tipo,status,coalesce(observacoes,'') as Observacoes from plantaopro.plantoes where reg_status='A' order by data_inicio desc");return ApiResponse<IEnumerable<PlantaoDto>>.Ok(d);} 
 public async Task<ApiResponse<PlantaoDto>> CreateAsync(CreatePlantaoRequest r,Guid u,string? ip,string? ua){if(r.DataFim<=r.DataInicio||r.Valor<=0||r.Vagas<=0)return ApiResponse<PlantaoDto>.Fail("Dados do plantão inválidos.");await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var id=Guid.NewGuid();await cn.ExecuteAsync("insert into plantaopro.plantoes(id,hospital_id,especialidade_id,data_inicio,data_fim,valor,vagas,tipo,status,observacoes,reg_date,reg_status,created_by) values(@id,@h,@e,@di,@df,@v,@vg,@t,'rascunho',@o,now(),'A',@u)",new{id,h=r.HospitalId,e=r.EspecialidadeId,di=r.DataInicio,df=r.DataFim,v=r.Valor,vg=r.Vagas,t=r.Tipo,o=r.Observacoes,u});await audit.LogAsync(u,"CREATE","plantoes",id,"Criação plantão",ip:ip,userAgent:ua);return ApiResponse<PlantaoDto>.Ok(new PlantaoDto(id,r.HospitalId,r.EspecialidadeId,r.DataInicio,r.DataFim,r.Valor,r.Vagas,r.Tipo,"rascunho",r.Observacoes),"Plantão criado e publicado com sucesso.");}
 public async Task<ApiResponse<string>> ChangeStatusAsync(Guid id,string novo,string just,Guid u,string? ip,string? ua){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var old=await cn.ExecuteScalarAsync<string>("select status from plantaopro.plantoes where id=@id",new{id},tx);if(old is null) return ApiResponse<string>.Fail("Registro não encontrado.",404);await cn.ExecuteAsync("update plantaopro.plantoes set status=@s,reg_update=now(),updated_by=@u where id=@id",new{id,s=novo,u},tx);await cn.ExecuteAsync("insert into plantaopro.historico_plantao(id,plantao_id,status_anterior,status_novo,justificativa,reg_date,reg_status,created_by) values(gen_random_uuid(),@id,@a,@n,@j,now(),'A',@u)",new{id,a=old,n=novo,j=just,u},tx);await cn.ExecuteAsync("insert into plantaopro.notificacoes(id,usuario_id,titulo,mensagem,tipo,lida,reg_date,reg_status,created_by) select gen_random_uuid(),m.usuario_id,'Atualização de plantão',@msg,'PLANTAO',false,now(),'A',@u from plantaopro.escalas e join plantaopro.medicos m on m.id=e.medico_id where e.plantao_id=@id",new{id,msg=$"Plantão alterado para {novo}",u},tx);await tx.CommitAsync();await audit.LogAsync(u,"STATUS_CHANGE","plantoes",id,$"{old}->{novo}",ip:ip,userAgent:ua);return ApiResponse<string>.Ok("ok","Status do plantão atualizado com sucesso.");}
}
public sealed class DashboardService(IConfiguration cfg){ public async Task<ApiResponse<DashboardDto>> GetAsync(Guid uid){await using var cn=new NpgsqlConnection(cfg.GetConnectionString("Default"));var d=await cn.QueryFirstAsync<DashboardDto>("select (select count(1) from plantaopro.medicos where reg_status='A') as TotalMedicos,(select count(1) from plantaopro.hospitais where reg_status='A') as TotalHospitais,(select count(1) from plantaopro.especialidades where reg_status='A') as TotalEspecialidades,(select count(1) from plantaopro.plantoes where reg_status='A') as TotalPlantoes,(select count(1) from plantaopro.plantoes where status='aberto') as PlantoesAbertos,(select count(1) from plantaopro.plantoes where status='confirmado') as PlantoesConfirmados,(select count(1) from plantaopro.plantoes where status='realizado') as PlantoesRealizados,(select count(1) from plantaopro.plantoes where status='cancelado') as PlantoesCancelados,(select count(1) from plantaopro.pagamentos where status='pendente') as PagamentosPendentes,(select count(1) from plantaopro.pagamentos where status='pago') as PagamentosPagos,(select coalesce(sum(valor_previsto),0) from plantaopro.pagamentos where status='pendente') as ValorPendente,(select coalesce(sum(valor_pago),0) from plantaopro.pagamentos where status='pago' and date_trunc('month',coalesce(data_pagamento,now()))=date_trunc('month',now())) as ValorPagoMes,(select count(1) from plantaopro.notificacoes where usuario_id=@uid and lida=false) as NotificacoesNaoLidas",new{uid});return ApiResponse<DashboardDto>.Ok(d);} }
