using Dapper;
using Npgsql;
using PlantaoPro.Api.Models;
using System.Text.Json;

namespace PlantaoPro.Api;

public sealed class ExecutionConferenceService
{
    private readonly IConfiguration configuration; private readonly ICurrentUserService current;
    public ExecutionConferenceService(IConfiguration configuration,ICurrentUserService current){this.configuration=configuration;this.current=current;}
    private NpgsqlConnection Connection()=>new(configuration.GetConnectionString("Default"));
    private (Guid Tenant,Guid Cliente,Guid User) Context()=> (current.TenantId??throw new UnauthorizedAccessException(),current.ClienteId??throw new UnauthorizedAccessException(),current.UserId??throw new UnauthorizedAccessException());
    public async Task<ApiResponse<ExecutionConferencePageDto>> ListAsync(ExecutionConferenceFilter filter,CancellationToken ct)
    {
        if(filter.Inicio.HasValue!=filter.Fim.HasValue||filter.Inicio>filter.Fim)return ApiResponse<ExecutionConferencePageDto>.Fail("Informe um período válido.",422);
        var c=Context();var page=Math.Max(1,filter.Page);var size=Math.Clamp(filter.PageSize,1,100);var status=(filter.Status??"").Trim().ToUpperInvariant();await using var cn=Connection();
        const string where=@" from medico_presenca_correcoes x join medico_checkins c on c.id=x.presenca_id and c.tenant_id=x.tenant_id join plantaopro.escalas e on e.id=x.escala_id and e.reg_status='A' join plantaopro.plantoes p on p.id=e.plantao_id and p.cliente_id=x.cliente_id join plantaopro.medicos m on m.id=x.medico_id join plantaopro.hospitais h on h.id=p.hospital_id where x.tenant_id=@Tenant and x.cliente_id=@Cliente and (@inicio is null or p.data_inicio::date>=@inicio) and (@fim is null or p.data_inicio::date<=@fim) and (@UnidadeId is null or p.hospital_id=@UnidadeId) and (@ProfissionalId is null or x.medico_id=@ProfissionalId) and (@status='' or x.status=@status)";
        var args=new{c.Tenant,c.Cliente,inicio=filter.Inicio,fim=filter.Fim,filter.UnidadeId,filter.ProfissionalId,status,limit=size,offset=(page-1)*size};
        var items=(await cn.QueryAsync<ExecutionConferenceItemDto>(new CommandDefinition(@"select x.id CorrecaoId,c.id PresencaId,x.escala_id EscalaId,x.medico_id MedicoId,m.nome Profissional,coalesce(h.nome_fantasia,h.razao_social) Unidade,p.data_inicio InicioPrevisto,p.data_fim FimPrevisto,c.checkin_em InicioRegistrado,c.checkout_em FimRegistrado,x.inicio_proposto_em InicioProposto,x.fim_proposto_em FimProposto,c.inicio_aprovado_em InicioAprovado,c.fim_aprovado_em FimAprovado,x.status,x.justificativa,x.versao,x.solicitado_em SolicitadoEm"+where+" order by x.solicitado_em desc limit @limit offset @offset",args,cancellationToken:ct))).AsList();
        var counts=await cn.QuerySingleAsync<(long Total,long Pendentes,long Aprovadas,long Recusadas)>(new CommandDefinition("select count(*) Total,count(*) filter(where x.status='PENDENTE') Pendentes,count(*) filter(where x.status='APROVADA') Aprovadas,count(*) filter(where x.status='RECUSADA') Recusadas"+where,args,cancellationToken:ct));
        return ApiResponse<ExecutionConferencePageDto>.Ok(new(items,counts.Total,counts.Pendentes,counts.Aprovadas,counts.Recusadas,page,size));
    }
    public async Task<ApiResponse<object>> DecideAsync(Guid id,DecideExecutionCorrectionRequest request,CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(request.Justificativa))return ApiResponse<object>.Fail("Registre a justificativa da decisão.",422);var c=Context();await using var cn=Connection();await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);
        var row=await cn.QueryFirstOrDefaultAsync<DecisionRow>(new CommandDefinition("select x.id,x.presenca_id PresencaId,x.solicitado_por SolicitadoPor,x.status,x.versao,x.inicio_original_em InicioOriginal,x.fim_original_em FimOriginal,x.inicio_proposto_em InicioProposto,x.fim_proposto_em FimProposto from medico_presenca_correcoes x where x.id=@id and x.tenant_id=@Tenant and x.cliente_id=@Cliente for update",new{id,c.Tenant,c.Cliente},tx,cancellationToken:ct));
        if(row is null)return ApiResponse<object>.Fail("Correção não encontrada no contexto atual.",404);if(row.SolicitadoPor==c.User)return ApiResponse<object>.Fail("O solicitante não pode aprovar a própria correção.",403);if(row.Status!="PENDENTE"||row.Versao!=request.Versao)return ApiResponse<object>.Fail("A correção já foi decidida ou alterada.",409);
        var consolidated=await cn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from plantaopro.financeiro_pagamento_origem o join plantaopro.pagamentos pg on pg.id=o.pagamento_id where o.tenant_id=@Tenant and o.escala_id=(select escala_id from medico_presenca_correcoes where id=@id) and lower(pg.status) in ('pago','aprovado'))",new{id,c.Tenant},tx,cancellationToken:ct));
        var status=request.Aprovar?"APROVADA":"RECUSADA";await cn.ExecuteAsync(new CommandDefinition("update medico_presenca_correcoes set status=@status,decidido_por=@User,decidido_em=now(),justificativa_decisao=@reason,inicio_aprovado_em=case when @approve then inicio_proposto_em end,fim_aprovado_em=case when @approve then fim_proposto_em end,versao=versao+1 where id=@id and versao=@Versao;update medico_checkins set inicio_aprovado_em=case when @approve and not @consolidated then coalesce(@InicioProposto,checkin_em) else inicio_aprovado_em end,fim_aprovado_em=case when @approve and not @consolidated then coalesce(@FimProposto,checkout_em) else fim_aprovado_em end,status_conferencia=case when @consolidated and @approve then 'AJUSTE_POS_APURACAO' when @approve then 'APROVADA' else 'PENDENTE' end,versao=versao+1 where id=@PresenceId",new{id,c.User,reason=request.Justificativa.Trim(),approve=request.Aprovar,consolidated,row.InicioProposto,row.FimProposto,row.PresenceId,row.Versao},tx,cancellationToken:ct));
        await cn.ExecuteAsync(new CommandDefinition("insert into medico_presenca_historico(tenant_id,cliente_id,presenca_id,correcao_id,evento,valores_anteriores,valores_posteriores,justificativa,executado_por) values(@Tenant,@Cliente,@PresenceId,@id,@Event,@before::jsonb,@after::jsonb,@reason,@User)",new{c.Tenant,c.Cliente,row.PresenceId,id,Event=request.Aprovar?"CORRECAO_APROVADA":"CORRECAO_RECUSADA",before=JsonSerializer.Serialize(new{row.InicioOriginal,row.FimOriginal}),after=JsonSerializer.Serialize(new{row.InicioProposto,row.FimProposto,consolidated}),reason=request.Justificativa.Trim(),c.User},tx,cancellationToken:ct));await tx.CommitAsync(ct);return ApiResponse<object>.Ok(new{id,status,consolidated},consolidated?"Correção encaminhada ao fluxo de ajuste; valores consolidados foram preservados.":"Decisão registrada.");
    }
    private sealed record DecisionRow(Guid Id,Guid PresenceId,Guid SolicitadoPor,string Status,long Versao,DateTimeOffset? InicioOriginal,DateTimeOffset? FimOriginal,DateTimeOffset? InicioProposto,DateTimeOffset? FimProposto);
}
