using Dapper;
using Npgsql;
using PlantaoPro.Api.Models;

namespace PlantaoPro.Api.Data;

public sealed class FechamentoOperacionalService
{
    private readonly IConfiguration cfg; private readonly ICurrentUserService user; private readonly IAuditService audit;
    public FechamentoOperacionalService(IConfiguration cfg, ICurrentUserService user, IAuditService audit) { this.cfg=cfg; this.user=user; this.audit=audit; }
    private NpgsqlConnection Cn()=>new(cfg.GetConnectionString("Default"));
    private Guid Tenant=>user.ClienteId??user.TenantId??throw new UnauthorizedAccessException("Tenant não informado.");
    private Guid UserId=>user.UserId??throw new UnauthorizedAccessException("Usuário não informado.");
    private const string Summary=@"select f.id Id,f.plantao_id PlantaoId,f.status Status,f.data_referencia DataReferencia,coalesce(h.nome_fantasia,'') Hospital,coalesce(e.nome,'') Especialidade,f.valor_previsto ValorPrevisto,f.valor_apurado ValorApurado,f.horas_previstas HorasPrevistas,f.horas_realizadas HorasRealizadas,f.quantidade_escalas QuantidadeEscalas,(select count(*) from plantaopro.fechamento_divergencias d where d.fechamento_id=f.id and d.status='ABERTA') DivergenciasAbertas from plantaopro.fechamentos_operacionais f join plantaopro.plantoes p on p.id=f.plantao_id left join plantaopro.hospitais h on h.id=p.hospital_id left join plantaopro.especialidades e on e.id=p.especialidade_id where f.tenant_id=@tenant";
    public async Task<ApiResponse<IReadOnlyList<FechamentoResumoDto>>> ListAsync(bool pending=false){await using var cn=Cn();var sql=Summary+(pending?" and f.status not in ('CONCLUIDO','CANCELADO')":"")+" order by f.created_at desc limit 200";return ApiResponse<IReadOnlyList<FechamentoResumoDto>>.Ok((await cn.QueryAsync<FechamentoResumoDto>(sql,new{tenant=Tenant})).AsList());}
    public async Task<ApiResponse<FechamentoDetalheDto>> GetAsync(Guid id){await using var cn=Cn();var dto=await cn.QuerySingleOrDefaultAsync<FechamentoDetalheDto>(Summary+" and f.id=@id",new{tenant=Tenant,id});if(dto is null)return ApiResponse<FechamentoDetalheDto>.Fail("Fechamento não encontrado.",404);dto.Itens=(await cn.QueryAsync<FechamentoItemDto>(@"select i.id Id,i.escala_id EscalaId,i.medico_id MedicoId,coalesce(m.nome,'') Medico,coalesce(m.crm,'') Crm,i.status_escala StatusEscala,i.horas_previstas HorasPrevistas,i.horas_realizadas HorasRealizadas,i.valor_previsto ValorPrevisto,i.valor_apurado ValorApurado,fp.pagamento_id PagamentoId from plantaopro.fechamento_operacional_itens i join plantaopro.medicos m on m.id=i.medico_id left join plantaopro.fechamento_pagamentos fp on fp.fechamento_item_id=i.id where i.fechamento_id=@id order by m.nome",new{id})).AsList();dto.Divergencias=(await cn.QueryAsync<FechamentoDivergenciaDto>("select id Id,fechamento_item_id FechamentoItemId,tipo Tipo,descricao Descricao,status Status,resolucao Resolucao,created_at CriadoEm from plantaopro.fechamento_divergencias where fechamento_id=@id order by created_at",new{id})).AsList();return ApiResponse<FechamentoDetalheDto>.Ok(dto);}
    public async Task<ApiResponse<IReadOnlyList<FechamentoTimelineDto>>> TimelineAsync(Guid id){await using var cn=Cn();if(!await Owns(cn,id))return ApiResponse<IReadOnlyList<FechamentoTimelineDto>>.Fail("Fechamento não encontrado.",404);return ApiResponse<IReadOnlyList<FechamentoTimelineDto>>.Ok((await cn.QueryAsync<FechamentoTimelineDto>("select id Id,coalesce(status_anterior,'') StatusAnterior,status_novo StatusNovo,acao Acao,motivo Motivo,created_at CriadoEm from plantaopro.fechamento_historico where fechamento_id=@id order by created_at",new{id})).AsList());}
    public async Task<ApiResponse<Guid>> GenerateAsync(Guid plantaoId){await using var cn=Cn();await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var p=await cn.QuerySingleOrDefaultAsync<(Guid Id,string Status,DateTime Inicio,DateTime Fim,decimal Valor)>("select id Id,status Status,data_inicio Inicio,data_fim Fim,coalesce(valor,0) Valor from plantaopro.plantoes where id=@plantaoId and cliente_id=@tenant and reg_status='A' for update",new{plantaoId,tenant=Tenant},tx);if(p.Id==Guid.Empty)return ApiResponse<Guid>.Fail("Plantão não encontrado.",404);if(p.Status!="realizado")return ApiResponse<Guid>.Fail("Somente plantão realizado pode ser fechado.",409);var existing=await cn.ExecuteScalarAsync<Guid?>("select id from plantaopro.fechamentos_operacionais where tenant_id=@tenant and plantao_id=@plantaoId",new{tenant=Tenant,plantaoId},tx);if(existing.HasValue){await tx.RollbackAsync();return ApiResponse<Guid>.Ok(existing.Value,"Fechamento já existente.");}var scales=(await cn.QueryAsync<(Guid Id,Guid MedicoId,string Status)>("select id Id,medico_id MedicoId,status Status from plantaopro.escalas where plantao_id=@plantaoId and reg_status='A' and status in ('realizado','nao_compareceu') for update",new{plantaoId},tx)).AsList();if(scales.Count==0)return ApiResponse<Guid>.Fail("Plantão não possui escalas realizadas ou ausências.",422);var hours=Math.Max(0m,(decimal)(p.Fim-p.Inicio).TotalHours);var unit=Math.Round((p.Valor/12m)*Math.Max(1m,hours),2);var id=Guid.NewGuid();var realized=scales.Count(x=>x.Status=="realizado");await cn.ExecuteAsync(@"insert into plantaopro.fechamentos_operacionais(id,tenant_id,cliente_id,plantao_id,status,data_referencia,valor_previsto,valor_apurado,horas_previstas,horas_realizadas,quantidade_escalas,created_by,created_at) values(@id,@tenant,@tenant,@plantaoId,'ABERTO',@date,@expected,@actual,@hp,@hr,@count,@user,now())",new{id,tenant=Tenant,plantaoId,date=p.Fim,expected=unit*scales.Count,actual=unit*realized,hp=hours*scales.Count,hr=hours*realized,count=scales.Count,user=UserId},tx);foreach(var s in scales)await cn.ExecuteAsync(@"insert into plantaopro.fechamento_operacional_itens(id,fechamento_id,escala_id,medico_id,plantao_id,status_escala,horas_previstas,horas_realizadas,valor_previsto,valor_apurado,created_at) values(gen_random_uuid(),@id,@escala,@medico,@plantaoId,@status,@hours,@realHours,@unit,@actual,now())",new{id,escala=s.Id,medico=s.MedicoId,plantaoId,status=s.Status,hours,realHours=s.Status=="realizado"?hours:0,unit,actual=s.Status=="realizado"?unit:0},tx);await History(cn,tx,id,null,"ABERTO","GERADO",null);await tx.CommitAsync();await audit.RegistrarAsync(UserId,Tenant,"FECHAMENTO_OPERACIONAL",id,"GERAR",new{plantaoId},true,null,string.Join(',',user.Roles));return ApiResponse<Guid>.Ok(id,"Fechamento gerado.");}
    public Task<ApiResponse<string>> StartAsync(Guid id)=>Transition(id,new[]{"ABERTO","DEVOLVIDO"},"EM_CONFERENCIA","INICIAR_CONFERENCIA",null);
    public async Task<ApiResponse<string>> FinishAsync(Guid id){await using var cn=Cn();var open=await cn.ExecuteScalarAsync<int>("select count(*) from plantaopro.fechamento_divergencias d join plantaopro.fechamentos_operacionais f on f.id=d.fechamento_id where d.fechamento_id=@id and d.status='ABERTA' and f.tenant_id=@tenant",new{id,tenant=Tenant});if(open>0)return ApiResponse<string>.Fail("Resolva as divergências abertas.",409);return await Transition(id,new[]{"EM_CONFERENCIA","COM_DIVERGENCIA"},"AGUARDANDO_APROVACAO","CONCLUIR_CONFERENCIA",null);}
    public Task<ApiResponse<string>> ApproveAsync(Guid id)=>Transition(id,new[]{"AGUARDANDO_APROVACAO"},"APROVADO","APROVAR",null,"aprovado_por", "aprovado_em");
    public async Task<ApiResponse<string>> ReturnAsync(Guid id,string reason){reason=(reason??"").Trim();if(reason.Length is < 5 or > 500)return ApiResponse<string>.Fail("Motivo deve ter entre 5 e 500 caracteres.",422);return await Transition(id,new[]{"AGUARDANDO_APROVACAO"},"DEVOLVIDO","DEVOLVER",reason,"devolvido_por","devolvido_em","motivo_devolucao");}
    public async Task<ApiResponse<Guid>> AddDivergenceAsync(Guid id,CriarDivergenciaRequest r){var types=new[]{"HORAS","VALOR","AUSENCIA","PRESENCA","SUBSTITUICAO","ESCALA","OUTRA"};if(!types.Contains(r.Tipo?.Trim().ToUpperInvariant())||string.IsNullOrWhiteSpace(r.Descricao))return ApiResponse<Guid>.Fail("Tipo e descrição válidos são obrigatórios.",422);await using var cn=Cn();await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var status=await Lock(cn,tx,id);if(status is not ("EM_CONFERENCIA" or "COM_DIVERGENCIA"))return ApiResponse<Guid>.Fail("Status incompatível.",409);if(r.FechamentoItemId.HasValue&&!await cn.ExecuteScalarAsync<bool>("select exists(select 1 from plantaopro.fechamento_operacional_itens where id=@item and fechamento_id=@id)",new{item=r.FechamentoItemId,id},tx))return ApiResponse<Guid>.Fail("Item inválido.",422);var did=Guid.NewGuid();await cn.ExecuteAsync("insert into plantaopro.fechamento_divergencias(id,fechamento_id,fechamento_item_id,tipo,descricao,valor_anterior,valor_proposto,status,motivo,created_by,created_at) values(@did,@id,@item,@tipo,@descricao,@anterior,@proposto,'ABERTA',@motivo,@user,now())",new{did,id,item=r.FechamentoItemId,tipo=r.Tipo.Trim().ToUpperInvariant(),descricao=r.Descricao.Trim(),anterior=r.ValorAnterior,proposto=r.ValorProposto,motivo=r.Motivo,user=UserId},tx);await cn.ExecuteAsync("update plantaopro.fechamentos_operacionais set status='COM_DIVERGENCIA',updated_by=@user,updated_at=now() where id=@id",new{id,user=UserId},tx);await History(cn,tx,id,status,"COM_DIVERGENCIA","DIVERGENCIA_CRIADA",r.Descricao.Trim());await tx.CommitAsync();return ApiResponse<Guid>.Ok(did,"Divergência criada.");}
    public async Task<ApiResponse<string>> ResolveDivergenceAsync(Guid id,Guid divergenceId,string resolution){resolution=(resolution??"").Trim();if(resolution.Length<3)return ApiResponse<string>.Fail("Resolução obrigatória.",422);await using var cn=Cn();await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();if(!await Owns(cn,id,tx))return ApiResponse<string>.Fail("Fechamento não encontrado.",404);var changed=await cn.ExecuteAsync("update plantaopro.fechamento_divergencias set status='RESOLVIDA',resolucao=@resolution,resolved_by=@user,resolved_at=now(),updated_at=now() where id=@divergenceId and fechamento_id=@id and status='ABERTA'",new{id,divergenceId,resolution,user=UserId},tx);if(changed==0)return ApiResponse<string>.Fail("Divergência inexistente ou já resolvida.",409);await History(cn,tx,id,"COM_DIVERGENCIA","COM_DIVERGENCIA","DIVERGENCIA_RESOLVIDA",resolution);await tx.CommitAsync();return ApiResponse<string>.Ok("ok","Divergência resolvida.");}
    public async Task<ApiResponse<string>> GenerateFinancialAsync(Guid id){await using var cn=Cn();await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var status=await Lock(cn,tx,id);if(status=="FINANCEIRO_GERADO"){await tx.RollbackAsync();return ApiResponse<string>.Ok("ok","Financeiro já gerado.");}if(status!="APROVADO")return ApiResponse<string>.Fail("Fechamento precisa estar aprovado.",409);var items=(await cn.QueryAsync<(Guid Id,Guid EscalaId,Guid MedicoId,Guid PlantaoId,decimal Valor,string Status)>("select id Id,escala_id EscalaId,medico_id MedicoId,plantao_id PlantaoId,valor_apurado Valor,status_escala Status from plantaopro.fechamento_operacional_itens where fechamento_id=@id for update",new{id},tx)).AsList();foreach(var item in items.Where(x=>x.Status=="realizado")){var payment=await cn.ExecuteScalarAsync<Guid?>("select id from plantaopro.pagamentos where escala_id=@escala and reg_status='A'",new{escala=item.EscalaId},tx);if(!payment.HasValue){payment=Guid.NewGuid();await cn.ExecuteAsync("insert into plantaopro.pagamentos(id,escala_id,medico_id,plantao_id,valor_previsto,status,data_prevista,reg_date,reg_status,created_by) values(@payment,@escala,@medico,@plantao,@valor,'pendente',current_date+7,now(),'A',@user)",new{payment,escala=item.EscalaId,medico=item.MedicoId,plantao=item.PlantaoId,valor=item.Valor,user=UserId},tx);await cn.ExecuteAsync("insert into plantaopro.historico_pagamento(id,pagamento_id,status_novo,justificativa,usuario_id,reg_date) values(gen_random_uuid(),@payment,'pendente','Gerado pelo fechamento operacional',@user,now())",new{payment,user=UserId},tx);}await cn.ExecuteAsync("insert into plantaopro.fechamento_pagamentos(fechamento_id,fechamento_item_id,pagamento_id,created_at) values(@id,@item,@payment,now()) on conflict do nothing",new{id,item=item.Id,payment},tx);}await cn.ExecuteAsync("update plantaopro.fechamentos_operacionais set status='FINANCEIRO_GERADO',financeiro_gerado_por=@user,financeiro_gerado_em=now(),updated_at=now() where id=@id and status='APROVADO'",new{id,user=UserId},tx);await History(cn,tx,id,status,"FINANCEIRO_GERADO","GERAR_FINANCEIRO",null);await tx.CommitAsync();return ApiResponse<string>.Ok("ok","Financeiro gerado.");}
    private async Task<ApiResponse<string>> Transition(Guid id,string[] from,string to,string action,string? reason,string? userColumn=null,string? dateColumn=null,string? reasonColumn=null){await using var cn=Cn();await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var old=await Lock(cn,tx,id);if(old is null)return ApiResponse<string>.Fail("Fechamento não encontrado.",404);if(!from.Contains(old))return ApiResponse<string>.Fail($"Transição {old} → {to} não permitida.",409);var extra=(userColumn is null?"":$",{userColumn}=@user")+(dateColumn is null?"":$",{dateColumn}=now()")+(reasonColumn is null?"":$",{reasonColumn}=@reason");var changed=await cn.ExecuteAsync($"update plantaopro.fechamentos_operacionais set status=@to,updated_by=@user,updated_at=now(){extra} where id=@id and tenant_id=@tenant and status=@old",new{id,tenant=Tenant,old,to,user=UserId,reason},tx);if(changed!=1)return ApiResponse<string>.Fail("Fechamento alterado por outra operação.",409);await History(cn,tx,id,old,to,action,reason);await tx.CommitAsync();return ApiResponse<string>.Ok("ok","Fechamento atualizado.");}
    private Task<string?> Lock(NpgsqlConnection cn,NpgsqlTransaction tx,Guid id)=>cn.ExecuteScalarAsync<string?>("select status from plantaopro.fechamentos_operacionais where id=@id and tenant_id=@tenant for update",new{id,tenant=Tenant},tx);
    private Task<bool> Owns(NpgsqlConnection cn,Guid id,NpgsqlTransaction? tx=null)=>cn.ExecuteScalarAsync<bool>("select exists(select 1 from plantaopro.fechamentos_operacionais where id=@id and tenant_id=@tenant)",new{id,tenant=Tenant},tx);
    private Task History(NpgsqlConnection cn,NpgsqlTransaction tx,Guid id,string? old,string next,string action,string? reason)=>cn.ExecuteAsync("insert into plantaopro.fechamento_historico(id,fechamento_id,status_anterior,status_novo,acao,motivo,created_by,created_at) values(gen_random_uuid(),@id,@old,@next,@action,@reason,@user,now())",new{id,old,next,action,reason,user=UserId},tx);
}
