using Dapper;
using Npgsql;
using PlantaoPro.Api.Controllers;
using PlantaoPro.Api.Data;
using PlantaoPro.Api.Models;

namespace PlantaoPro.Api;

public sealed class V115GlosaService
{
    private readonly IConfiguration cfg; private readonly ICurrentUserService currentUser; private readonly IAuditService audit; private readonly ILogger<V115GlosaService> logger;
    public V115GlosaService(IConfiguration cfg, ICurrentUserService currentUser, IAuditService audit, ILogger<V115GlosaService> logger) { this.cfg = cfg; this.currentUser = currentUser; this.audit = audit; this.logger = logger; }
    private NpgsqlConnection Cn() => new NpgsqlConnection(cfg.GetConnectionString("Default")); private Guid? TenantId => currentUser.ClienteId ?? currentUser.TenantId; private Guid? UserId => currentUser.UserId; private bool Global => currentUser.IsGlobalAdmin(); private string Perfil => string.Join(',', currentUser.Roles);
    public async Task<ApiResponse<IEnumerable<object>>> ListarAsync() => await QueryList("select id,conta_receber_id as contaReceberId,titulo_id as tituloId,convenio_id as convenioId,motivo,valor_glosado as valorGlosado,prazo_recurso as prazoRecurso,status from plantaopro.v115_regras_glosa where reg_status='A' and (@isGlobal or @tenantId is null or tenant_id=@tenantId or cliente_id=@tenantId) order by created_at desc", "Glosas v1.15 carregadas.");
    public async Task<ApiResponse<object>> RegistrarAsync(V115GlosaRequest request) { try { if (request.ValorGlosado <= 0) return ApiResponse<object>.Fail("Valor glosado deve ser informado ou calculado pela regra do convênio.", 400); await using var cn = Cn(); var id = Guid.NewGuid(); await cn.ExecuteAsync("insert into plantaopro.v115_regras_glosa(id,cliente_id,tenant_id,conta_receber_id,titulo_id,convenio_id,motivo,valor_glosado,prazo_recurso,status,reg_status,created_at,created_by) values(@id,@tenantId,@tenantId,@contaReceberId,@tituloId,@convenioId,@motivo,@valorGlosado,@prazoRecurso,'ABERTA','A',now(),@userId); insert into plantaopro.v115_alertas_operacionais(id,cliente_id,tenant_id,tipo,prioridade,perfil_responsavel,modulo,entidade_id,cta,rota,prazo,status,origem_regra,reg_status,created_at,created_by) values(gen_random_uuid(),@tenantId,@tenantId,'GLOSA_ABERTA','ALTA','FATURAMENTO_CONVENIO','Faturamento Clínico',@id,'Resolver glosa','/FaturamentoClinico/Glosas',@prazoRecurso,'ABERTA','v115_glosa','A',now(),@userId)", ScopeWith(new { id, contaReceberId = request.ContaReceberId, tituloId = request.TituloId, convenioId = request.ConvenioId, motivo = request.Motivo, valorGlosado = request.ValorGlosado, prazoRecurso = request.PrazoRecurso ?? DateTime.UtcNow.AddDays(7), userId = UserId })); await AuditAsync("v115_glosas", id, "REGISTRAR_GLOSA", new { request.ConvenioId, request.Motivo }); return ApiResponse<object>.Ok(new { id, status = "ABERTA", request.ValorGlosado }, "Glosa registrada com alerta operacional."); } catch (Exception ex) { return Fail<object>(ex, "Falha ao registrar glosa."); } }
    public async Task<ApiResponse<object>> ResolverAsync(Guid id, V115ContestacaoRequest request) { try { await using var cn = Cn(); var affected = await cn.ExecuteAsync("update plantaopro.v115_regras_glosa set status='RESOLVIDA',resolucao=@motivo,updated_at=now(),updated_by=@userId where id=@id and reg_status='A' and (@isGlobal or @tenantId is null or tenant_id=@tenantId or cliente_id=@tenantId)", ScopeWith(new { id, motivo = request.Motivo, userId = UserId })); if (affected == 0) return ApiResponse<object>.Fail("Glosa não encontrada.", 404); await AuditAsync("v115_glosas", id, "RESOLVER_GLOSA", new { request.Motivo }); return ApiResponse<object>.Ok(new { id, status = "RESOLVIDA" }, "Glosa resolvida."); } catch (Exception ex) { return Fail<object>(ex, "Falha ao resolver glosa."); } }
    public async Task<ApiResponse<IEnumerable<object>>> AlertasAsync() => await QueryList("select id,tipo,prioridade,perfil_responsavel as perfilResponsavel,modulo,entidade_id as entidadeId,cta,rota,prazo,status,origem_regra as origemRegra from plantaopro.v115_alertas_operacionais where reg_status='A' and (@isGlobal or @tenantId is null or tenant_id=@tenantId or cliente_id=@tenantId) order by prioridade, prazo nulls last", "Alertas financeiros/operacionais v1.15 carregados.");
    private async Task<ApiResponse<IEnumerable<object>>> QueryList(string sql, string ok) { try { await using var cn = Cn(); return ApiResponse<IEnumerable<object>>.Ok((await cn.QueryAsync<object>(sql, ScopeWith(new { }))).ToList(), ok); } catch (Exception ex) { return Fail<IEnumerable<object>>(ex, ok); } }
    private async Task AuditAsync(string entity, Guid id, string action, object details) => await audit.RegistrarAsync(UserId, TenantId, entity, id, action, details, true, null, Perfil);
    private ApiResponse<T> Fail<T>(Exception ex, string message) { logger.LogError(ex, "V1.15 glosa: {Message}", message); return ApiResponse<T>.Fail(message, 500); }
    private object ScopeWith(object values) { var dict = new Dictionary<string, object?> { { "tenantId", TenantId }, { "isGlobal", Global } }; foreach (var p in values.GetType().GetProperties()) dict[p.Name] = p.GetValue(values); return dict; }
}
public sealed record V115GlosaRequest(Guid? ContaReceberId, Guid? TituloId, Guid? ConvenioId, string Motivo, decimal ValorGlosado, DateTime? PrazoRecurso);
