using Dapper;
using Npgsql;
using PlantaoPro.Api.Controllers;
using PlantaoPro.Api.Data;
using PlantaoPro.Api.Models;

namespace PlantaoPro.Api;

public sealed class V115GlosaService
{
    private readonly IConfiguration cfg; private readonly ICurrentUserService currentUser; private readonly FinancialTenantContext context; private readonly IAuditService audit; private readonly ILogger<V115GlosaService> logger;
    public V115GlosaService(IConfiguration cfg, ICurrentUserService currentUser, FinancialTenantContext context, IAuditService audit, ILogger<V115GlosaService> logger) { this.cfg = cfg; this.currentUser = currentUser; this.context = context; this.audit = audit; this.logger = logger; }
    private NpgsqlConnection Cn() => new NpgsqlConnection(cfg.GetConnectionString("Default")); private Guid? TenantId => currentUser.ClienteId ?? currentUser.TenantId; private Guid? UserId => currentUser.UserId; private bool Global => currentUser.IsGlobalAdmin(); private string Perfil => string.Join(',', currentUser.Roles);
    public async Task<ApiResponse<IEnumerable<GlosaDto>>> ListarAsync() { if (!context.HasTenant) return context.MissingTenant<IEnumerable<GlosaDto>>(); try { await using var cn=Cn(); var rows=await cn.QueryAsync<GlosaDto>("select id,conta_receber_id as contaReceberId,titulo_id as tituloId,convenio_id as convenioId,motivo,valor_glosado as valorGlosado,coalesce(valor_recuperado,0) as valorRecuperado,prazo_recurso as prazoRecurso,status from plantaopro.v115_regras_glosa where reg_status='A' and tenant_id=@tenantId order by created_at desc", new { tenantId=context.TenantId }); return ApiResponse<IEnumerable<GlosaDto>>.Ok(rows,"Glosas carregadas."); } catch(Exception ex) { return Fail<IEnumerable<GlosaDto>>(ex,"Falha ao listar glosas."); } }
    public async Task<ApiResponse<object>> RegistrarAsync(V115GlosaRequest request) { if(!context.HasTenant) return context.MissingTenant<object>(); try { if(request.ContaReceberId is null || request.ConvenioId is null || string.IsNullOrWhiteSpace(request.Motivo)) return ApiResponse<object>.Fail("Conta, convenio e motivo sao obrigatorios.",422); if (request.ValorGlosado <= 0) return ApiResponse<object>.Fail("Valor glosado deve ser informado ou calculado pela regra do convênio.", 400); await using var cn = Cn(); var elegivel=await cn.ExecuteScalarAsync<decimal?>("select valor from plantaopro.v113_faturas where id=@id and tenant_id=@tenantId and reg_status='A'",new{id=request.ContaReceberId,tenantId=context.TenantId}); if(!elegivel.HasValue)return ApiResponse<object>.Fail("Conta nao pertence ao tenant.",404); if(request.ValorGlosado>elegivel.Value)return ApiResponse<object>.Fail("Glosa excede valor elegivel.",422); var id = Guid.NewGuid(); await cn.ExecuteAsync("insert into plantaopro.v115_regras_glosa(id,cliente_id,tenant_id,conta_receber_id,titulo_id,convenio_id,motivo,valor_glosado,prazo_recurso,status,reg_status,created_at,created_by) values(@id,@tenantId,@tenantId,@contaReceberId,@tituloId,@convenioId,@motivo,@valorGlosado,@prazoRecurso,'ABERTA','A',now(),@userId); insert into plantaopro.v115_alertas_operacionais(id,cliente_id,tenant_id,tipo,prioridade,perfil_responsavel,modulo,entidade_id,cta,rota,prazo,status,origem_regra,reg_status,created_at,created_by) values(gen_random_uuid(),@tenantId,@tenantId,'GLOSA_ANALISAR',case when @prazoRecurso is not null and @prazoRecurso <= now()+interval '2 days' then 'ALTA' else 'MEDIA' end,'FATURAMENTO_CONVENIO','Faturamento Clínico',@id,'Resolver glosa','/FaturamentoClinico/Glosas',@prazoRecurso,'ABERTA','v115_glosa','A',now(),@userId)", ScopeWith(new { id, contaReceberId = request.ContaReceberId, tituloId = request.TituloId, convenioId = request.ConvenioId, motivo = request.Motivo, valorGlosado = request.ValorGlosado, prazoRecurso = request.PrazoRecurso, userId = UserId })); await AuditAsync("v115_glosas", id, "REGISTRAR_GLOSA", new { request.ConvenioId, request.Motivo }); return ApiResponse<object>.Ok(new { id, status = "ABERTA", request.ValorGlosado }, "Glosa registrada com alerta operacional."); } catch (Exception ex) { return Fail<object>(ex, "Falha ao registrar glosa."); } }
    public async Task<ApiResponse<object>> ResolverAsync(Guid id, V115ContestacaoRequest request) { if(!context.HasTenant)return context.MissingTenant<object>(); if(string.IsNullOrWhiteSpace(request.Motivo))return ApiResponse<object>.Fail("Resultado da glosa obrigatorio.",422); try { await using var cn = Cn(); var affected = await cn.ExecuteAsync("update plantaopro.v115_regras_glosa set status='RESOLVIDA',resolucao=@motivo,updated_at=now(),updated_by=@userId where id=@id and reg_status='A' and tenant_id=@tenantId", ScopeWith(new { id, motivo = request.Motivo, userId = UserId })); if (affected == 0) return ApiResponse<object>.Fail("Glosa não encontrada.", 404); await AuditAsync("v115_glosas", id, "RESOLVER_GLOSA", new { request.Motivo }); return ApiResponse<object>.Ok(new { id, status = "RESOLVIDA" }, "Glosa resolvida."); } catch (Exception ex) { return Fail<object>(ex, "Falha ao resolver glosa."); } }
    public async Task<ApiResponse<IEnumerable<AlertaFinanceiroDto>>> AlertasAsync() { if(!context.HasTenant)return context.MissingTenant<IEnumerable<AlertaFinanceiroDto>>(); try { await using var cn=Cn(); var rows=await cn.QueryAsync<AlertaFinanceiroDto>("select id,tipo,prioridade,entidade_id as entidadeId,cta,rota,prazo,status from plantaopro.v115_alertas_operacionais where reg_status='A' and tenant_id=@tenantId order by prioridade, prazo nulls last",new{tenantId=context.TenantId}); return ApiResponse<IEnumerable<AlertaFinanceiroDto>>.Ok(rows,"Alertas carregados."); } catch(Exception ex){return Fail<IEnumerable<AlertaFinanceiroDto>>(ex,"Falha ao listar alertas.");} }
    private async Task AuditAsync(string entity, Guid id, string action, object details) => await audit.RegistrarAsync(UserId, TenantId, entity, id, action, details, true, null, Perfil);
    private ApiResponse<T> Fail<T>(Exception ex, string message) { logger.LogError(ex, "V1.15 glosa: {Message}", message); return ApiResponse<T>.Fail(message, 500); }
    private object ScopeWith(object values) { var dict = new Dictionary<string, object?> { { "tenantId", TenantId }, { "isGlobal", Global } }; foreach (var p in values.GetType().GetProperties()) dict[p.Name] = p.GetValue(values); return dict; }
}
public sealed record V115GlosaRequest(Guid? ContaReceberId, Guid? TituloId, Guid? ConvenioId, string Motivo, decimal ValorGlosado, DateTime? PrazoRecurso);
