using Dapper; using Npgsql;
namespace PlantaoPro.Api.Operation360.Productivity;
public sealed record ProductivityItemDto(Guid Id,string Tipo,Guid? ReferenciaId,string Titulo,string Url,DateTimeOffset Data);
public sealed record FavoriteRequest(string Tipo,Guid? ReferenciaId,string Titulo,string Url);
public interface IProductivityRepository { Task<IReadOnlyList<ProductivityItemDto>> FavoritesAsync(Guid tenantId,Guid userId,CancellationToken ct); Task<ProductivityItemDto> AddFavoriteAsync(Guid tenantId,Guid userId,FavoriteRequest request,CancellationToken ct); Task<bool> DeleteFavoriteAsync(Guid tenantId,Guid userId,Guid id,CancellationToken ct); Task<IReadOnlyList<ProductivityItemDto>> RecentAsync(Guid tenantId,Guid userId,CancellationToken ct); Task<int> ClearRecentAsync(Guid tenantId,Guid userId,Guid? id,CancellationToken ct); }
public sealed class ProductivityRepository:IProductivityRepository
{
 private readonly string cs;public ProductivityRepository(IConfiguration cfg)=>cs=cfg.GetConnectionString("Default")??throw new InvalidOperationException("ConnectionStrings:Default não configurada.");private NpgsqlConnection Cn()=>new(cs);
 public async Task<IReadOnlyList<ProductivityItemDto>> FavoritesAsync(Guid tenantId,Guid userId,CancellationToken ct){await using var cn=Cn();return(await cn.QueryAsync<ProductivityItemDto>(new CommandDefinition("select id,tipo,referencia_id as ReferenciaId,titulo,url,criado_em as Data from plantaopro.user_favorites where tenant_id=@tenantId and usuario_id=@userId order by criado_em desc",new{tenantId,userId},cancellationToken:ct))).AsList();}
 public async Task<ProductivityItemDto> AddFavoriteAsync(Guid tenantId,Guid userId,FavoriteRequest r,CancellationToken ct){await using var cn=Cn();return await cn.QuerySingleAsync<ProductivityItemDto>(new CommandDefinition(@"insert into plantaopro.user_favorites(id,tenant_id,usuario_id,tipo,referencia_id,titulo,url) values(gen_random_uuid(),@tenantId,@userId,@Tipo,@ReferenciaId,@Titulo,@Url) on conflict(tenant_id,usuario_id,tipo,referencia_id) do update set titulo=excluded.titulo,url=excluded.url returning id,tipo,referencia_id as ReferenciaId,titulo,url,criado_em as Data",new{tenantId,userId,r.Tipo,r.ReferenciaId,r.Titulo,r.Url},cancellationToken:ct));}
 public async Task<bool> DeleteFavoriteAsync(Guid tenantId,Guid userId,Guid id,CancellationToken ct){await using var cn=Cn();return await cn.ExecuteAsync(new CommandDefinition("delete from plantaopro.user_favorites where id=@id and tenant_id=@tenantId and usuario_id=@userId",new{id,tenantId,userId},cancellationToken:ct))>0;}
 public async Task<IReadOnlyList<ProductivityItemDto>> RecentAsync(Guid tenantId,Guid userId,CancellationToken ct){await using var cn=Cn();return(await cn.QueryAsync<ProductivityItemDto>(new CommandDefinition("select id,tipo,referencia_id as ReferenciaId,titulo,url,acessado_em as Data from plantaopro.recent_items where tenant_id=@tenantId and usuario_id=@userId order by acessado_em desc limit 12",new{tenantId,userId},cancellationToken:ct))).AsList();}
 public async Task<int> ClearRecentAsync(Guid tenantId,Guid userId,Guid? id,CancellationToken ct){await using var cn=Cn();return await cn.ExecuteAsync(new CommandDefinition("delete from plantaopro.recent_items where tenant_id=@tenantId and usuario_id=@userId and (@id is null or id=@id)",new{tenantId,userId,id},cancellationToken:ct));}
}
public interface IProductivityService{Task<IReadOnlyList<ProductivityItemDto>> FavoritesAsync(CancellationToken ct);Task<ProductivityItemDto> AddFavoriteAsync(FavoriteRequest request,CancellationToken ct);Task<bool> DeleteFavoriteAsync(Guid id,CancellationToken ct);Task<IReadOnlyList<ProductivityItemDto>> RecentAsync(CancellationToken ct);Task<int> ClearRecentAsync(Guid? id,CancellationToken ct);}
public sealed class ProductivityService:IProductivityService
{private readonly IProductivityRepository repo;private readonly ICurrentUserService user;public ProductivityService(IProductivityRepository repo,ICurrentUserService user){this.repo=repo;this.user=user;}private Guid Tenant=>user.TenantId??throw new UnauthorizedAccessException();private Guid User=>user.UserId??throw new UnauthorizedAccessException();private static readonly HashSet<string> Allowed=new(new[]{"PLANTAO","ESCALA","MEDICO","PACIENTE"});public Task<IReadOnlyList<ProductivityItemDto>> FavoritesAsync(CancellationToken ct)=>repo.FavoritesAsync(Tenant,User,ct);public Task<ProductivityItemDto>AddFavoriteAsync(FavoriteRequest r,CancellationToken ct){if(!Allowed.Contains(r.Tipo)||string.IsNullOrWhiteSpace(r.Titulo)||!r.Url.StartsWith('/'))throw new ArgumentException("Favorito inválido ou rota não permitida.");return repo.AddFavoriteAsync(Tenant,User,r,ct);}public Task<bool>DeleteFavoriteAsync(Guid id,CancellationToken ct)=>repo.DeleteFavoriteAsync(Tenant,User,id,ct);public Task<IReadOnlyList<ProductivityItemDto>>RecentAsync(CancellationToken ct)=>repo.RecentAsync(Tenant,User,ct);public Task<int>ClearRecentAsync(Guid? id,CancellationToken ct)=>repo.ClearRecentAsync(Tenant,User,id,ct);}
