create schema if not exists plantaopro;
create extension if not exists pgcrypto;

create table if not exists plantaopro.v115_regras_faturamento(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, codigo text not null, nome text not null, tipo_faturamento text not null, item_faturavel_id uuid null, convenio_id uuid null, valor_base numeric(12,2) not null default 0, percentual_desconto numeric(6,2) not null default 0, percentual_acrescimo numeric(6,2) not null default 0, status text not null default 'ATIVA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_regras_repasse(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, referencia_id uuid null, medico_id uuid null, convenio_id uuid null, tipo_regra text not null default 'PERCENTUAL', percentual numeric(6,2) not null default 0, valor_fixo numeric(12,2) not null default 0, valor_base numeric(12,2) not null default 0, valor_repasse numeric(12,2) not null default 0, contestacao text null, status text not null default 'REGRA_ATIVA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_regras_glosa(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, conta_receber_id uuid null, titulo_id uuid null, convenio_id uuid null, motivo text not null default 'REGRA_CONVENIO', valor_glosado numeric(12,2) not null default 0, percentual_glosa numeric(6,2) not null default 0, prazo_recurso timestamptz null, resolucao text null, status text not null default 'ABERTA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_convenio_regras(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, convenio_id uuid null, nome text not null, prazo_recebimento_dias int not null default 30, exige_autorizacao boolean not null default false, status text not null default 'ATIVA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_faturamento_eventos(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, tipo text not null, entidade_id uuid null, payload jsonb not null default '{}'::jsonb, status text not null default 'PENDENTE', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_recebimentos(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, conta_receber_id uuid null, valor_recebido numeric(12,2) not null default 0, forma text not null default 'MANUAL_AUDITADO', status text not null default 'RECEBIDO', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_configuracoes_financeiras(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, chave text not null, valor text not null, escopo text not null default 'TENANT', status text not null default 'ATIVA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_jornada_perfil_progresso(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, perfil text not null, passo text not null, rota text not null, cta text not null, pendencia_relacionada text null, status text not null default 'PENDENTE', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_alertas_operacionais(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, tipo text not null, prioridade text not null, perfil_responsavel text not null, modulo text not null, entidade_id uuid null, cta text not null, rota text not null, prazo timestamptz null, status text not null default 'ABERTA', origem_regra text not null, reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);
create table if not exists plantaopro.v115_configuracoes_mobile(id uuid primary key default gen_random_uuid(), cliente_id uuid null, tenant_id uuid null, perfil text not null, chave text not null, valor jsonb not null default '{}'::jsonb, status text not null default 'ATIVA', reg_status char(1) not null default 'A', created_at timestamptz not null default now(), created_by uuid null, updated_at timestamptz null, updated_by uuid null);

alter table if exists plantaopro.v115_regras_faturamento add column if not exists updated_by uuid null;
alter table if exists plantaopro.v115_regras_repasse add column if not exists contestacao text null;
alter table if exists plantaopro.v115_regras_glosa add column if not exists resolucao text null;
alter table if exists plantaopro.v115_alertas_operacionais add column if not exists origem_regra text not null default 'v115';

create index if not exists ix_v115_regras_faturamento_tenant_status_data on plantaopro.v115_regras_faturamento(tenant_id,reg_status,created_at);
create index if not exists ix_v115_regras_repasse_tenant_status_data on plantaopro.v115_regras_repasse(tenant_id,reg_status,created_at);
create index if not exists ix_v115_regras_glosa_tenant_status_data on plantaopro.v115_regras_glosa(tenant_id,reg_status,created_at);
create index if not exists ix_v115_convenio_regras_tenant_status_data on plantaopro.v115_convenio_regras(tenant_id,reg_status,created_at);
create index if not exists ix_v115_faturamento_eventos_tenant_status_data on plantaopro.v115_faturamento_eventos(tenant_id,reg_status,created_at);
create index if not exists ix_v115_recebimentos_tenant_status_data on plantaopro.v115_recebimentos(tenant_id,reg_status,created_at);
create index if not exists ix_v115_config_fin_tenant_status_data on plantaopro.v115_configuracoes_financeiras(tenant_id,reg_status,created_at);
create index if not exists ix_v115_jornada_tenant_status_data on plantaopro.v115_jornada_perfil_progresso(tenant_id,reg_status,created_at);
create index if not exists ix_v115_alertas_tenant_status_data on plantaopro.v115_alertas_operacionais(tenant_id,reg_status,created_at);
create index if not exists ix_v115_mobile_tenant_status_data on plantaopro.v115_configuracoes_mobile(tenant_id,reg_status,created_at);
