create schema if not exists plantaopro;
create extension if not exists pgcrypto;

create table if not exists plantaopro.saas_clientes (id uuid primary key default gen_random_uuid(), nome_fantasia text not null, razao_social text not null, cnpj text not null, email text not null, telefone text, responsavel text, segmento text, cidade text, estado text, status text not null default 'ATIVO', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_planos (id uuid primary key default gen_random_uuid(), nome text not null unique, descricao text, valor_mensal numeric(12,2) not null default 0, status text not null default 'ATIVO', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_tenants (id uuid primary key default gen_random_uuid(), cliente_id uuid not null references plantaopro.saas_clientes(id), plano_id uuid references plantaopro.saas_planos(id), nome text not null, subdominio text not null unique, status text not null default 'ATIVO', data_ativacao timestamptz, observacoes text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_modulos (id uuid primary key default gen_random_uuid(), codigo text not null unique, nome text not null, descricao text, categoria text, status text not null default 'ATIVO', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_plano_modulos (id uuid primary key default gen_random_uuid(), plano_id uuid not null references plantaopro.saas_planos(id), modulo_id uuid not null references plantaopro.saas_modulos(id), habilitado boolean not null default true, reg_status char(1) not null default 'A', reg_date timestamptz not null default now(), unique(plano_id, modulo_id));
create table if not exists plantaopro.saas_assinaturas (id uuid primary key default gen_random_uuid(), cliente_id uuid not null references plantaopro.saas_clientes(id), tenant_id uuid references plantaopro.saas_tenants(id), plano_id uuid references plantaopro.saas_planos(id), valor_mensal numeric(12,2) not null default 0, dia_vencimento int not null default 10, status text not null default 'ATIVA', data_inicio date not null default current_date, data_fim date, renovacao_automatica boolean not null default true, observacoes text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_assinatura_historico (id uuid primary key default gen_random_uuid(), assinatura_id uuid not null references plantaopro.saas_assinaturas(id), cliente_id uuid, tenant_id uuid, acao text not null, plano_anterior_id uuid, plano_novo_id uuid, observacoes text, usuario_id uuid, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_limites (id uuid primary key default gen_random_uuid(), plano_id uuid not null references plantaopro.saas_planos(id), codigo text not null, nome text not null, limite int, bloqueante boolean not null default true, reg_status char(1) not null default 'A', reg_date timestamptz not null default now(), unique(plano_id,codigo));
create table if not exists plantaopro.saas_uso_mensal (id uuid primary key default gen_random_uuid(), cliente_id uuid not null, tenant_id uuid not null, competencia date not null, codigo_limite text not null, quantidade int not null default 0, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_bloqueios (id uuid primary key default gen_random_uuid(), cliente_id uuid, tenant_id uuid, codigo text not null, motivo text not null, status text not null default 'ATIVO', liberado_por uuid, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_onboarding (id uuid primary key default gen_random_uuid(), cliente_id uuid not null, tenant_id uuid, percentual int not null default 0, status text not null default 'EM_ANDAMENTO', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_onboarding_etapas (id uuid primary key default gen_random_uuid(), onboarding_id uuid not null references plantaopro.saas_onboarding(id), tenant_id uuid, ordem int not null, nome text not null, descricao text, responsavel text, status text not null default 'PENDENTE', link_tela text, dica_contextual text, documento_apoio text, data_conclusao timestamptz, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_white_label (id uuid primary key default gen_random_uuid(), cliente_id uuid not null, tenant_id uuid, logo_url text, nome_comercial text, slogan text, cor_primaria text, cor_secundaria text, cor_destaque text, favicon_url text, email_remetente text, url_publica text, texto_rodape text, modo_tema text, tema_institucional text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_marketplace_modulos (id uuid primary key default gen_random_uuid(), modulo_id uuid references plantaopro.saas_modulos(id), nome text not null, descricao text, beneficios text, plano_minimo text, status text not null default 'DISPONIVEL', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_marketplace_contratacoes (id uuid primary key default gen_random_uuid(), cliente_id uuid not null, tenant_id uuid, marketplace_modulo_id uuid not null references plantaopro.saas_marketplace_modulos(id), status text not null default 'SOLICITADO', solicitado_por uuid, aprovado_por uuid, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_billing_faturas (id uuid primary key default gen_random_uuid(), assinatura_id uuid not null references plantaopro.saas_assinaturas(id), cliente_id uuid, tenant_id uuid, competencia date not null, vencimento date not null, valor numeric(12,2) not null, status text not null default 'ABERTA', data_pagamento date, metodo_informativo text, observacoes text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_billing_pagamentos (id uuid primary key default gen_random_uuid(), fatura_id uuid not null references plantaopro.saas_billing_faturas(id), valor numeric(12,2) not null, data_pagamento date not null, metodo_informativo text, observacoes text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.saas_billing_eventos (id uuid primary key default gen_random_uuid(), assinatura_id uuid, fatura_id uuid, cliente_id uuid, tenant_id uuid, tipo text not null, descricao text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.suporte_chamados (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid, solicitante_id uuid, titulo text not null, descricao text not null, categoria text not null, prioridade text not null, status text not null default 'ABERTO', sla_horas int not null default 24, data_abertura timestamptz not null default now(), data_primeira_resposta timestamptz, data_fechamento timestamptz, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.suporte_chamado_mensagens (id uuid primary key default gen_random_uuid(), chamado_id uuid not null references plantaopro.suporte_chamados(id), autor_id uuid, mensagem text not null, interno boolean not null default false, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.suporte_chamado_anexos (id uuid primary key default gen_random_uuid(), chamado_id uuid not null references plantaopro.suporte_chamados(id), nome_arquivo text not null, content_type text not null, tamanho_bytes bigint not null, url text not null, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.suporte_sla_politicas (id uuid primary key default gen_random_uuid(), prioridade text not null unique, primeira_resposta_horas int not null, resolucao_horas int not null, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create table if not exists plantaopro.suporte_base_conhecimento (id uuid primary key default gen_random_uuid(), titulo text not null, categoria text not null, conteudo text not null, status text not null default 'PUBLICADO', reg_status char(1) not null default 'A', reg_date timestamptz not null default now());

DO $$ begin if not exists (select 1 from pg_constraint where conname='ck_saas_clientes_status') then alter table plantaopro.saas_clientes add constraint ck_saas_clientes_status check (status in ('ATIVO','SUSPENSO','INATIVO')); end if; end $$;

create index if not exists ix_saas_clientes_status_date on plantaopro.saas_clientes(status, reg_date);
create index if not exists ix_saas_tenants_cliente_status on plantaopro.saas_tenants(cliente_id,status,reg_date);
create index if not exists ix_saas_assinaturas_cliente_tenant on plantaopro.saas_assinaturas(cliente_id,tenant_id,status,reg_date);
create index if not exists ix_saas_uso_tenant_competencia on plantaopro.saas_uso_mensal(tenant_id,competencia,reg_date);
create index if not exists ix_suporte_chamados_tenant_status on plantaopro.suporte_chamados(tenant_id,status,reg_date);
insert into plantaopro.saas_planos(nome, descricao, valor_mensal) values
('Essencial','Até 5 usuários, 2 médicos, atendimento e plantões básicos.',299),
('Profissional','Operação clínica completa com financeiro, CID, prescrição e relatórios.',799),
('Enterprise','Limites configuráveis, convênios, API pública, webhooks e suporte premium.',1990),
('White Label','Enterprise com marca, domínio, e-mail e marketplace próprios.',2990)
on conflict (nome) do update set descricao=excluded.descricao, valor_mensal=excluded.valor_mensal;

insert into plantaopro.saas_modulos(codigo,nome,descricao,categoria) values
('ATENDIMENTO','Atendimento','Fluxo de atendimento clínico.','Clinico'),('PLANTOES','Plantões','Gestão de plantões.','Operacao'),('ESCALAS','Escalas','Escalas médicas.','Operacao'),('FINANCEIRO','Financeiro','Rotinas financeiras.','Financeiro'),('CONVENIOS','Convênios','Convênios e autorizações.','Clinico'),('CID','CID','Consulta e importação CID.','Clinico'),('PRESCRICOES','Prescrições','Prescrições médicas.','Clinico'),('RELATORIOS','Relatórios','Relatórios operacionais.','Gestao'),('DASHBOARD_GESTOR','Dashboard Gestor','Painéis executivos.','Gestao'),('API_PUBLICA','API Pública','Integrações públicas.','Integracao'),('WEBHOOKS','Webhooks','Eventos externos.','Integracao'),('WHITE_LABEL','White Label','Marca própria.','SaaS'),('MARKETPLACE','Marketplace','Loja de módulos.','SaaS'),('SUPORTE_PREMIUM','Suporte Premium','SLA premium.','Suporte')
on conflict (codigo) do update set nome=excluded.nome, descricao=excluded.descricao;
create table if not exists plantaopro.saas_billing_assinaturas (id uuid primary key default gen_random_uuid(), cliente_id uuid not null, tenant_id uuid, plano_id uuid, valor_mensal numeric(12,2) not null default 0, dia_vencimento int not null default 10, status text not null default 'ATIVA', data_inicio date not null default current_date, data_fim date, renovacao_automatica boolean not null default true, observacoes text, reg_status char(1) not null default 'A', reg_date timestamptz not null default now());
create index if not exists ix_saas_billing_assinaturas_cliente_tenant on plantaopro.saas_billing_assinaturas(cliente_id,tenant_id,status,reg_date);
