create schema if not exists plantaopro;
create extension if not exists pgcrypto;

create table if not exists plantaopro.bi_indicadores_config (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, codigo varchar(80) not null, nome varchar(160) not null, perfil varchar(60) not null, ativo boolean not null default true, configuracao_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_relatorios_modelos (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, codigo varchar(80) not null, nome varchar(160) not null, tipo varchar(60) not null, requer_dados_sensiveis boolean not null default false, configuracao_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_relatorios_execucoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, modelo_id uuid, tipo varchar(60) not null, filtros_json jsonb not null default '{}'::jsonb, status varchar(40) not null default 'CONCLUIDO', total_linhas int not null default 0, finalidade text, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_relatorios_filtros_salvos (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, nome varchar(120) not null, tipo varchar(60) not null, filtros_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_exportacoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, tipo varchar(60) not null, formato varchar(20) not null, periodo_inicio date, periodo_fim date, finalidade text not null, status varchar(40) not null default 'CONCLUIDA', total_linhas int not null default 0, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_dashboard_widgets (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, codigo varchar(80) not null, titulo varchar(160) not null, perfil varchar(60) not null, tipo varchar(40) not null, configuracao_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.bi_dashboard_usuario_config (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, widgets_json jsonb not null default '[]'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');

create table if not exists plantaopro.api_keys (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, nome varchar(120) not null, prefixo varchar(16) not null, chave_hash text not null, status varchar(30) not null default 'ATIVA', criado_por uuid not null, expira_em timestamptz, ultimo_uso_em timestamptz, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.api_key_permissoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, api_key_id uuid not null references plantaopro.api_keys(id), escopo varchar(80) not null, permitido boolean not null default true, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.api_key_logs (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid, api_key_id uuid, endpoint text not null, metodo varchar(10) not null, status_code int not null, ip varchar(80), user_agent text, detalhe_seguro text, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.webhooks (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, nome varchar(120) not null, url text not null, secret_hash text not null, eventos text[] not null default array[]::text[], ativo boolean not null default true, incluir_dados_sensiveis boolean not null default false, criado_por uuid not null, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.webhook_eventos (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, evento varchar(100) not null, entidade_id uuid, metadados_json jsonb not null default '{}'::jsonb, status varchar(40) not null default 'PENDENTE', reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.webhook_entregas (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, webhook_id uuid not null references plantaopro.webhooks(id), evento_id uuid, tentativa int not null default 1, status varchar(40) not null default 'PENDENTE', http_status int, assinatura varchar(128), resposta_resumo text, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.webhook_logs (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, webhook_id uuid, entrega_id uuid, acao varchar(80) not null, detalhe_seguro text, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.integracao_configuracoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, tipo varchar(80) not null, nome varchar(120) not null, config_segura_json jsonb not null default '{}'::jsonb, ativo boolean not null default true, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.integracao_execucoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, configuracao_id uuid, tipo varchar(80) not null, status varchar(40) not null, resumo_seguro text, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.integracao_erros (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, execucao_id uuid, codigo varchar(80), mensagem_segura text not null, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');

create table if not exists plantaopro.mobile_dispositivos (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, plataforma varchar(30) not null, device_id_hash text not null, ativo boolean not null default true, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.mobile_push_tokens (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, dispositivo_id uuid, token_hash text not null, provedor varchar(30) not null, ativo boolean not null default true, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.mobile_sessoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, dispositivo_id uuid, status varchar(30) not null default 'ATIVA', ip varchar(80), reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.mobile_notificacoes (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, tipo varchar(80) not null, titulo varchar(140) not null, mensagem text not null, lida boolean not null default false, metadados_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.mobile_preferencias (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid not null, preferencias_json jsonb not null default '{}'::jsonb, reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.mobile_auditoria (id uuid primary key default gen_random_uuid(), tenant_id uuid, cliente_id uuid not null, usuario_id uuid, acao varchar(80) not null, detalhe_seguro text, ip varchar(80), reg_date timestamptz not null default now(), reg_status char(1) not null default 'A');

create index if not exists ix_bi_indicadores_cliente_codigo on plantaopro.bi_indicadores_config(cliente_id,codigo);
create index if not exists ix_bi_exportacoes_cliente_usuario_reg on plantaopro.bi_exportacoes(cliente_id,usuario_id,reg_date);
create index if not exists ix_api_keys_cliente_status on plantaopro.api_keys(cliente_id,status);
create index if not exists ix_api_key_logs_cliente_reg on plantaopro.api_key_logs(cliente_id,reg_date);
create index if not exists ix_webhooks_cliente_ativo on plantaopro.webhooks(cliente_id,ativo);
create index if not exists ix_webhook_entregas_cliente_status on plantaopro.webhook_entregas(cliente_id,status,reg_date);
create index if not exists ix_integracao_execucoes_cliente_status on plantaopro.integracao_execucoes(cliente_id,status,reg_date);
create index if not exists ix_mobile_dispositivos_cliente_usuario on plantaopro.mobile_dispositivos(cliente_id,usuario_id,ativo);
create index if not exists ix_mobile_notificacoes_cliente_usuario_lida on plantaopro.mobile_notificacoes(cliente_id,usuario_id,lida,reg_date);
