create schema if not exists plantaopro;
create extension if not exists pgcrypto;

create table if not exists plantaopro.clinica_contas_receber (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, paciente_id uuid null, agendamento_id uuid null, consulta_id uuid null, convenio_id uuid null, plano_saude_id uuid null, medico_id uuid null, descricao text not null default '', origem text not null default 'MANUAL', tipo_recebimento text not null default 'PARTICULAR', valor_total numeric(14,2) not null default 0, valor_pago numeric(14,2) not null default 0, valor_desconto numeric(14,2) not null default 0, valor_pendente numeric(14,2) not null default 0, vencimento date null, status text not null default 'ABERTO', observacoes text not null default '', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_recebimentos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, conta_receber_id uuid null, paciente_id uuid null, valor numeric(14,2) not null default 0, forma_pagamento text not null default '', data_recebimento timestamp without time zone not null default now(), comprovante text not null default '', observacoes text not null default '', status text not null default 'CONFIRMADO', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_caixa (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, unidade_id uuid null, usuario_abertura_id uuid null, usuario_fechamento_id uuid null, data_abertura timestamp without time zone not null default now(), data_fechamento timestamp without time zone null, saldo_inicial numeric(14,2) not null default 0, total_entradas numeric(14,2) not null default 0, total_saidas numeric(14,2) not null default 0, saldo_final numeric(14,2) not null default 0, status text not null default 'ABERTO', observacoes text not null default '', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_fechamentos_caixa (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, caixa_id uuid null, saldo_informado numeric(14,2) not null default 0, divergencia numeric(14,2) not null default 0, status text not null default 'FECHADO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_repasses (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, medico_id uuid null, valor numeric(14,2) not null default 0, status text not null default 'ABERTO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_lancamentos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, caixa_id uuid null, tipo text not null default 'ENTRADA', descricao text not null default '', valor numeric(14,2) not null default 0, status text not null default 'CONFIRMADO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_estornos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, recebimento_id uuid null, motivo text not null default '', valor numeric(14,2) not null default 0, status text not null default 'ESTORNADO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_glosas (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, conta_receber_id uuid null, motivo text not null default '', valor numeric(14,2) not null default 0, status text not null default 'ABERTA', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.clinica_financeiro_historico (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, entidade text not null default '', entidade_id uuid null, acao text not null default '', detalhes jsonb not null default '{}'::jsonb, usuario_id uuid null, reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');

create index if not exists ix_clinica_contas_receber_cliente_id on plantaopro.clinica_contas_receber(cliente_id); create index if not exists ix_clinica_contas_receber_paciente_id on plantaopro.clinica_contas_receber(paciente_id); create index if not exists ix_clinica_contas_receber_consulta_id on plantaopro.clinica_contas_receber(consulta_id); create index if not exists ix_clinica_contas_receber_agendamento_id on plantaopro.clinica_contas_receber(agendamento_id); create index if not exists ix_clinica_contas_receber_convenio_id on plantaopro.clinica_contas_receber(convenio_id); create index if not exists ix_clinica_contas_receber_status on plantaopro.clinica_contas_receber(status); create index if not exists ix_clinica_contas_receber_reg_date on plantaopro.clinica_contas_receber(reg_date);
create index if not exists ix_clinica_recebimentos_cliente_id on plantaopro.clinica_recebimentos(cliente_id); create index if not exists ix_clinica_recebimentos_paciente_id on plantaopro.clinica_recebimentos(paciente_id); create index if not exists ix_clinica_recebimentos_status on plantaopro.clinica_recebimentos(status); create index if not exists ix_clinica_recebimentos_reg_date on plantaopro.clinica_recebimentos(reg_date);
create index if not exists ix_clinica_caixa_cliente_id on plantaopro.clinica_caixa(cliente_id); create index if not exists ix_clinica_caixa_status on plantaopro.clinica_caixa(status); create index if not exists ix_clinica_caixa_reg_date on plantaopro.clinica_caixa(reg_date);
