create schema if not exists plantaopro;
create extension if not exists pgcrypto;

create table if not exists plantaopro.convenios (
    id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null,
    nome text not null default '', codigo text not null default '', codigo_ans text not null default '',
    cnpj text not null default '', telefone text not null default '', email text not null default '', responsavel text not null default '',
    status text not null default 'ATIVO', observacoes text not null default '', created_by uuid null, updated_by uuid null,
    created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null,
    reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A'
);
alter table plantaopro.convenios add column if not exists codigo text not null default '';
alter table plantaopro.convenios add column if not exists codigo_ans text not null default '';
update plantaopro.convenios set codigo = coalesce(nullif(codigo,''), codigo_ans, '') where codigo = '';
create index if not exists ix_convenios_cliente_id on plantaopro.convenios(cliente_id);
create index if not exists ix_convenios_nome on plantaopro.convenios(nome);
create index if not exists ix_convenios_codigo on plantaopro.convenios(codigo);
create index if not exists ix_convenios_cnpj on plantaopro.convenios(cnpj);
create index if not exists ix_convenios_status on plantaopro.convenios(status);
create index if not exists ix_convenios_reg_date on plantaopro.convenios(reg_date);
create unique index if not exists ux_convenios_cliente_codigo_ativo on plantaopro.convenios(cliente_id, upper(codigo)) where reg_status='A' and codigo <> '';

create table if not exists plantaopro.convenio_contratos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, numero_contrato text not null default '', vigencia_inicio date null, vigencia_fim date null, status text not null default 'ATIVO', observacoes text not null default '', created_by uuid null, updated_by uuid null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_planos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, nome text not null default '', codigo text not null default '', registro_ans text not null default '', tipo_acomodacao text not null default '', coparticipacao_percentual numeric(7,2) not null default 0, status text not null default 'ATIVO', observacoes text not null default '', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
alter table plantaopro.convenio_planos add column if not exists codigo text not null default '';
alter table plantaopro.convenio_planos add column if not exists registro_ans text not null default '';
update plantaopro.convenio_planos set codigo=coalesce(nullif(codigo,''), registro_ans, '') where codigo='';
create table if not exists plantaopro.convenio_tabelas (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, nome text not null default '', codigo text not null default '', status text not null default 'ATIVO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_procedimentos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, tabela_id uuid null, convenio_id uuid null, codigo text not null default '', descricao text not null default '', valor numeric(14,2) not null default 0, status text not null default 'ATIVO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_autorizacoes (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, paciente_id uuid null, convenio_id uuid null, plano_saude_id uuid null, agendamento_id uuid null, consulta_id uuid null, numero_guia text not null default '', senha_autorizacao text not null default '', procedimento text not null default '', procedimento_id uuid null, motivo text not null default '', valor_autorizado numeric(14,2) not null default 0, status text not null default 'PENDENTE', motivo_negativa text not null default '', validade date null, created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_glosas (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, faturamento_id uuid null, motivo text not null default '', valor numeric(14,2) not null default 0, status text not null default 'ABERTA', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_glosa_recursos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, glosa_id uuid null, justificativa text not null default '', status text not null default 'ENVIADO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_faturamentos (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, competencia text not null default '', valor_total numeric(14,2) not null default 0, status text not null default 'ABERTO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_faturamento_itens (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, faturamento_id uuid null, autorizacao_id uuid null, descricao text not null default '', valor numeric(14,2) not null default 0, status text not null default 'ABERTO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.convenio_historico (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, acao text not null default '', detalhes jsonb not null default '{}'::jsonb, usuario_id uuid null, reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.planos_saude (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, convenio_id uuid null, nome text not null default '', codigo text not null default '', operadora text not null default '', registro_ans text not null default '', tipo text not null default '', status text not null default 'ATIVO', observacoes text not null default '', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
alter table plantaopro.planos_saude add column if not exists codigo text not null default '';
alter table plantaopro.planos_saude add column if not exists operadora text not null default '';
alter table plantaopro.planos_saude add column if not exists registro_ans text not null default '';
update plantaopro.planos_saude set codigo=coalesce(nullif(codigo,''), registro_ans, '') where codigo='';
create table if not exists plantaopro.plano_saude_coberturas (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, plano_saude_id uuid null, descricao text not null default '', status text not null default 'ATIVO', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.plano_saude_pacientes (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, paciente_id uuid null, plano_saude_id uuid null, convenio_id uuid null, numero_carteirinha text not null default '', validade date null, titular_nome text not null default '', titular_documento text not null default '', dependente boolean not null default false, principal boolean not null default false, status text not null default 'ATIVO', observacoes text not null default '', created_by uuid null, updated_by uuid null, created_at timestamp without time zone not null default now(), updated_at timestamp without time zone null, reg_date timestamp without time zone not null default now(), reg_update timestamp without time zone null, reg_status char(1) not null default 'A');
create table if not exists plantaopro.plano_saude_autorizacoes (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, plano_saude_id uuid null, paciente_id uuid null, procedimento text not null default '', status text not null default 'PENDENTE', reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');
create table if not exists plantaopro.plano_saude_historico (id uuid primary key default gen_random_uuid(), tenant_id uuid null, cliente_id uuid null, plano_saude_id uuid null, acao text not null default '', detalhes jsonb not null default '{}'::jsonb, reg_date timestamp without time zone not null default now(), reg_status char(1) not null default 'A');

create index if not exists ix_convenio_planos_cliente_id on plantaopro.convenio_planos(cliente_id); create index if not exists ix_convenio_planos_convenio_id on plantaopro.convenio_planos(convenio_id); create index if not exists ix_convenio_planos_status on plantaopro.convenio_planos(status); create index if not exists ix_convenio_planos_reg_date on plantaopro.convenio_planos(reg_date);
create index if not exists ix_convenio_autorizacoes_cliente_id on plantaopro.convenio_autorizacoes(cliente_id); create index if not exists ix_convenio_autorizacoes_paciente_id on plantaopro.convenio_autorizacoes(paciente_id); create index if not exists ix_convenio_autorizacoes_agendamento_id on plantaopro.convenio_autorizacoes(agendamento_id); create index if not exists ix_convenio_autorizacoes_consulta_id on plantaopro.convenio_autorizacoes(consulta_id); create index if not exists ix_convenio_autorizacoes_convenio_id on plantaopro.convenio_autorizacoes(convenio_id); create index if not exists ix_convenio_autorizacoes_status on plantaopro.convenio_autorizacoes(status); create index if not exists ix_convenio_autorizacoes_reg_date on plantaopro.convenio_autorizacoes(reg_date);
create index if not exists ix_planos_saude_cliente_id on plantaopro.planos_saude(cliente_id); create index if not exists ix_planos_saude_convenio_id on plantaopro.planos_saude(convenio_id); create index if not exists ix_planos_saude_codigo on plantaopro.planos_saude(codigo); create index if not exists ix_planos_saude_status on plantaopro.planos_saude(status); create index if not exists ix_planos_saude_reg_date on plantaopro.planos_saude(reg_date);
create index if not exists ix_plano_saude_pacientes_cliente_id on plantaopro.plano_saude_pacientes(cliente_id); create index if not exists ix_plano_saude_pacientes_paciente_id on plantaopro.plano_saude_pacientes(paciente_id); create index if not exists ix_plano_saude_pacientes_plano on plantaopro.plano_saude_pacientes(plano_saude_id); create index if not exists ix_plano_saude_pacientes_status on plantaopro.plano_saude_pacientes(status); create index if not exists ix_plano_saude_pacientes_reg_date on plantaopro.plano_saude_pacientes(reg_date);
