using System.Security.Claims;
using Dapper;
using Npgsql;
using PlantaoPro.CrossCutting.Security;

namespace PlantaoPro.Api;

public sealed class ContextoRepository : IContextoRepository
{
    private readonly IConfiguration _cfg; private readonly ContextTokenService _tokens;
    public ContextoRepository(IConfiguration cfg, ContextTokenService tokens){_cfg=cfg;_tokens=tokens;}
    private NpgsqlConnection Cn()=>new(_cfg.GetConnectionString("Default"));
    public Task<ContextoAtualDto> AtualAsync(ClaimsPrincipal user, CancellationToken ct=default)=>Task.FromResult(new ContextoAtualDto(Parse(user.FindFirstValue("uid")??user.FindFirstValue(ClaimTypes.NameIdentifier)),Parse(user.FindFirstValue("tenant_id")),Parse(user.FindFirstValue("cliente_id")),user.FindFirstValue("context_mode")??"GLOBAL",user.FindFirstValue("access_scope")??AccessScopes.Global,user.FindFirstValue("primary_role")??user.FindFirstValue(ClaimTypes.Role),user.FindFirstValue("tenant_context_id")));
    public async Task<IReadOnlyCollection<TenantDisponivelDto>> TenantsDisponiveisAsync(Guid usuarioId, CancellationToken ct=default){await using var cn=Cn(); var rows=await cn.QueryAsync<TenantDisponivelDto>(@"select t.id TenantId, coalesce(t.nome,'Unidade') TenantNome, c.id ClienteId, coalesce(c.nome,'Cliente') ClienteNome, null CnpjMascarado, coalesce(t.status,'ATIVO') Status, 'Plano ativo' Plano, coalesce(a.status,'SEM_ASSINATURA') AssinaturaStatus, array[]::text[] ModulosAtivos, ucr.ultimo_acesso_em UltimoAcesso, (coalesce(t.status,'ATIVO')='ATIVO' and coalesce(a.status,'ATIVA') in ('ATIVA','TRIAL','SEM_ASSINATURA')) PodeSelecionar, case when coalesce(t.status,'ATIVO')<>'ATIVO' then 'Tenant inativo' when coalesce(a.status,'ATIVA') not in ('ATIVA','TRIAL','SEM_ASSINATURA') then 'Assinatura indisponível' else null end MotivoBloqueio from plantaopro.usuario_tenant_acessos uca join plantaopro.tenants t on t.id=uca.tenant_id left join plantaopro.clientes c on c.id=uca.cliente_id left join plantaopro.assinaturas a on a.tenant_id=t.id left join plantaopro.usuario_contextos_recentes ucr on ucr.usuario_id=uca.usuario_id and ucr.tenant_id=t.id where uca.usuario_id=@usuarioId and coalesce(uca.reg_status,'A')='A' order by ucr.ultimo_acesso_em desc nulls last, ClienteNome, TenantNome", new{usuarioId}); return rows.ToArray();}
    public async Task<IReadOnlyCollection<ContextoTrocaDto>> TrocasAsync(Guid usuarioId, CancellationToken ct=default){await using var cn=Cn(); var rows=await cn.QueryAsync<ContextoTrocaDto>("select id, tenant_destino_id TenantId, modo_destino Evento, reg_date TimestampUtc from plantaopro.contexto_trocas where usuario_id=@usuarioId order by reg_date desc limit 20", new{usuarioId}); return rows.ToArray();}
    public async Task<SelecionarContextoResponse> SelecionarAsync(ClaimsPrincipal user, Guid tenantId, string? motivo, CancellationToken ct=default){var uid=Parse(user.FindFirstValue("uid")??user.FindFirstValue(ClaimTypes.NameIdentifier))??throw new UnauthorizedAccessException(); await using var cn=Cn(); await cn.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(ct); var clienteId=await cn.ExecuteScalarAsync<Guid>("select uca.cliente_id from plantaopro.usuario_tenant_acessos uca where uca.usuario_id=@uid and uca.tenant_id=@tenantId and coalesce(uca.reg_status,'A')='A'", new{uid,tenantId}, tx); var ctx=Guid.NewGuid(); var sessionId=Guid.NewGuid().ToString("N"); var perfil=user.FindFirstValue(ClaimTypes.Role)??"USUARIO"; await cn.ExecuteAsync("update plantaopro.contexto_sessoes set encerrado_em=now(), reg_status='E' where usuario_id=@uid and encerrado_em is null", new{uid}, tx); await cn.ExecuteAsync("insert into plantaopro.contexto_sessoes(id,sessao_id,usuario_id,tenant_id,cliente_id,modo,perfil_efetivo,iniciado_em,ultimo_uso_em,reg_status) values(@ctx,@sessionId,@uid,@tenantId,@clienteId,'TENANT',@perfil,now(),now(),'A')", new{ctx,sessionId,uid,tenantId,clienteId,perfil}, tx); await cn.ExecuteAsync("insert into plantaopro.contexto_trocas(id,contexto_sessao_id,usuario_id,tenant_destino_id,modo_destino,motivo,reg_date,reg_status) values(gen_random_uuid(),@ctx,@uid,@tenantId,'TENANT',@motivo,now(),'A')", new{ctx,uid,tenantId,motivo}, tx); await cn.ExecuteAsync("insert into plantaopro.usuario_contextos_recentes(usuario_id,tenant_id,cliente_id,ultimo_acesso_em,total_acessos,reg_status) values(@uid,@tenantId,@clienteId,now(),1,'A')", new{uid,tenantId,clienteId,ctx}, tx); await tx.CommitAsync(ct); var token=_tokens.Emitir(user,tenantId,clienteId,ctx,"TENANT",AccessScopes.Hybrid); return new(tenantId,clienteId,ctx,"TENANT",AccessScopes.Hybrid,Guid.NewGuid().ToString("N"),token);}
    public async Task<RetornarContextoGlobalResponse> RetornarGlobalAsync(ClaimsPrincipal user, CancellationToken ct=default){var uid=Parse(user.FindFirstValue("uid")??user.FindFirstValue(ClaimTypes.NameIdentifier))??throw new UnauthorizedAccessException(); await using var cn=Cn(); await cn.ExecuteAsync("update plantaopro.contexto_sessoes set encerrado_em=now(), reg_status='E' where usuario_id=@uid and encerrado_em is null", new{uid}); return new("GLOBAL",AccessScopes.Global,null,null,_tokens.Emitir(user,null,null,null,"GLOBAL",AccessScopes.Global));}
    static Guid? Parse(string? v)=>Guid.TryParse(v,out var id)?id:null;
}
